version: 0.2

env:
  shell: bash
  variables:
    STAGE: 'dev'
    DEPLOYMENT_BUCKET: 'dev-mvx-sso-integration-bucket'
    STACK_NAME: 'dev-sso-integration'

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps

  pre_build:
    commands:
      - echo "Making scripts executable..."
      - chmod +x services/sso-integration/ci/*.sh

  build:
    commands:
      - echo "Starting build..."
      - services/sso-integration/ci/build.sh

  post_build:
    commands:
      - echo "Running deployment verification..."
      - services/sso-integration/ci/verify-artifacts.sh

artifacts:
  files:
    - services/sso-integration/packaged.yaml
    - services/sso-integration/.serverless/**/*
  discard-paths: no