version: 0.2

env:
  variables:
    STAGE: 'prd'
    DEPLOYMENT_BUCKET: 'prd-mvx-sso-integration-bucket'
    STACK_NAME: 'prd-sso-integration'
    SEED_META: ''

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps

  pre_build:
    commands:
      - echo "Making scripts executable..."
      - chmod +x services/sso-integration/ci/*.sh

  build:
    commands:
      - echo "Starting build..."
      - services/sso-integration/ci/build.sh

  post_build:
    commands:
      - echo "Running deployment verification..."
      - services/sso-integration/ci/verify-artifacts.sh

artifacts:
  files:
    - services/sso-integration/packaged.yaml
    - services/sso-integration/.serverless/**/*
  discard-paths: no