/**
 * CDN: add these keys under `ERROR_MESSAGES_CDN_URL` / `error-messages/{lang}.json`
 * (same pipeline as other services). Titles/descriptions are resolved at runtime.
 */
export const TEMPLATE_CDN_MESSAGE_KEYS = [
  'TEMPLATE.TEMPLATE_CREATED_SUCCESS',
  'TEMPLATE.TEMPLATE_RETRIEVED_SUCCESS',
  'TEMPLATE.TEMPLATE_UPDATED_SUCCESS',
  'TEMPLATE.TEMPLATE_PUBLISHED_SUCCESS',
  'TEMPLATE.TEMPLATE_EXECUTED_SUCCESS',
  'TEMPLATE.TEMPLATE_VALIDATION_FAILED',
  'TEMPLATE.TEMPLATE_NOT_FOUND',
  'TEMPLATE.TEMPLATE_CREATE_FAILED',
  'TEMPLATE.TEMPLATE_GET_FAILED',
  'TEMPLATE.TEMPLATE_UPDATE_FAILED',
  'TEMPLATE.TEMPLATE_PUBLISH_FAILED',
  'TEMPLATE.TEMPLATE_EXECUTE_FAILED',
  'TEMPLATE.TEMPLATE_INVALID_STATE_TRANSITION',
  'TEMPLATE.TEMPLATE_RESOLVE_FAILED',
  'CARE_PLAN.CARE_PLAN_DRAFT_SUCCESS',
] as const;
