/**
 * ListUserFiles Adapter
 * Converts internal ListUserFilesDTO DTO to FHIR R4 ListUserFiles resource
 * Auto-generated by FHIR Mapper Generator
 */

import { ListUserFiles } from '../../models/r4/listuserfiles'
import { ListUserFilesDTO } from '../../types/internal'
import { getCurrentFhirDateTime } from '../../utils/date'

/**
 * Convert internal ListUserFilesDTO to FHIR ListUserFiles
 * @param dto - ListUserFilesDTO DTO
 * @param baseUrl - Base URL for references
 */
export function toListUserFiles(dto: ListUserFilesDTO, baseUrl?: string): ListUserFiles {
  const listuserfilesId = dto.userId

  // Resource ID mapping - Direct mapping

  const listuserfiles: ListUserFiles = {
    resourceType: 'ListUserFiles',
    id: listuserfilesId,
    ...(id && { id: id }),
    meta: {
      lastUpdated: getCurrentFhirDateTime(),
      ...(baseUrl && { source: baseUrl }),
    },
  }

  return listuserfiles
}
