/**
 * ListUserOrganizations Adapter
 * Converts internal ListUserOrganizationsDTO DTO to FHIR R4 ListUserOrganizations resource
 * Auto-generated by FHIR Mapper Generator
 */

import { ListUserOrganizations } from '../../models/r4/listuserorganizations'
import { ListUserOrganizationsDTO } from '../../types/internal'
import { getCurrentFhirDateTime } from '../../utils/date'

/**
 * Convert internal ListUserOrganizationsDTO to FHIR ListUserOrganizations
 * @param dto - ListUserOrganizationsDTO DTO
 * @param baseUrl - Base URL for references
 */
export function toListUserOrganizations(
  dto: ListUserOrganizationsDTO,
  baseUrl?: string
): ListUserOrganizations {
  const listuserorganizationsId = dto.userId

  // Resource ID mapping - Direct mapping

  const listuserorganizations: ListUserOrganizations = {
    resourceType: 'ListUserOrganizations',
    id: listuserorganizationsId,
    ...(id && { id: id }),
    meta: {
      lastUpdated: getCurrentFhirDateTime(),
      ...(baseUrl && { source: baseUrl }),
    },
  }

  return listuserorganizations
}
