/**
 * User Adapter
 * Converts internal UserDTO DTO to FHIR R4 User resource
 * Auto-generated by FHIR Mapper Generator
 */

import { User } from '../../models/r4/user'
import { UserDTO } from '../../types/internal'
import { getCurrentFhirDateTime, toFhirDate } from '../../utils/date'
import { createOrganizationReference } from '../../utils/reference'
import { createCodeableConcept } from '../../utils/coding'
import { HumanName, ContactPoint, Address, Identifier } from '../../models/r4/common'

/**
 * Convert internal UserDTO to FHIR User
 * @param dto - UserDTO DTO
 * @param baseUrl - Base URL for references
 */
export function toUser(dto: UserDTO, baseUrl?: string): User {
  const userId = dto.userID

  // Build names
  const names: HumanName[] = []
  if (dto.firstName || dto.lastName || dto.fullName) {
    const given: string[] = []
    if (dto.firstName) {
      given.push(dto.firstName)
    }
    if (dto.middleName) {
      given.push(dto.middleName)
    }
    const name: HumanName = {
      use: 'official',
      ...(given.length > 0 && { given }),
      ...(dto.lastName && { family: dto.lastName }),
      ...(dto.namePrefix && { prefix: [dto.namePrefix] }),
      ...(dto.fullName && !dto.firstName && !dto.lastName && { text: dto.fullName }),
    }
    if (name.given?.length || name.family || name.text) {
      names.push(name)
    }
  }

  // Build telecom (contact points)
  const telecom: ContactPoint[] = []
  if (dto.emailAddress) {
    telecom.push({
      system: 'email',
      value: dto.emailAddress,
      use: 'home',
    })
  }
  if (dto.phoneNumber) {
    telecom.push({
      system: 'phone',
      value: dto.phoneCode ? `${dto.phoneCode}${dto.phoneNumber}` : dto.phoneNumber,
      use: 'mobile',
    })
  }
  if (dto.additionalEmailIDs?.length) {
    dto.additionalEmailIDs.forEach((email) => {
      telecom.push({
        system: 'email',
        value: email,
        use: 'temp',
      })
    })
  }
  if (dto.additionalPhoneNumbers?.length) {
    dto.additionalPhoneNumbers.forEach((phone) => {
      telecom.push({
        system: 'phone',
        value: phone,
        use: 'temp',
      })
    })
  }

  // Build addresses
  const addresses: Address[] = []
  if (dto.address || dto.street || dto.city || dto.state || dto.postalCode || dto.country) {
    const address: Address = {
      use: 'home',
      type: 'both',
      ...(dto.street && { line: [dto.street] }),
      ...(dto.address && !dto.street && { line: [dto.address] }),
      ...(dto.city && { city: dto.city }),
      ...(dto.state && { state: dto.state }),
      ...(dto.stateCode && { state: dto.stateCode }),
      ...(dto.postalCode && { postalCode: dto.postalCode }),
      ...(dto.zip && !dto.postalCode && { postalCode: dto.zip }),
      ...(dto.country && { country: dto.country }),
      ...(dto.countryCode && { country: dto.countryCode }),
    }
    if (address.line?.length || address.city || address.state || address.postalCode || address.country) {
      addresses.push(address)
    }
  }

  // Build identifiers
  const identifiers: Identifier[] = []
  if (dto.userID) {
    identifiers.push({
      use: 'official',
      system: baseUrl ? `${baseUrl}/fhir/User` : undefined,
      value: dto.userID,
    })
  }
  if (dto.mrn) {
    identifiers.push({
      use: 'usual',
      type: createCodeableConcept(
        'http://terminology.hl7.org/CodeSystem/v2-0203',
        'MR',
        'Medical Record Number'
      ),
      value: dto.mrn,
    })
  }
  if (dto.emailAddress) {
    identifiers.push({
      use: 'secondary',
      system: 'http://hl7.org/fhir/sid/email',
      value: dto.emailAddress,
    })
  }

  // Build photo if profilePic exists
  const photo = dto.profilePic
    ? [
        {
          url: dto.profilePic,
        },
      ]
    : undefined

  // Build the User resource
  const user: User = {
    resourceType: 'User',
    id: userId,
    ...(identifiers.length > 0 && { identifier: identifiers }),
    active: dto.isActive !== false,
    ...(names.length > 0 && { name: names }),
    ...(telecom.length > 0 && { telecom }),
    ...(dto.gender && {
      gender: mapGender(dto.gender),
    }),
    ...(dto.dateOfBirth && { birthDate: toFhirDate(dto.dateOfBirth) }),
    ...(addresses.length > 0 && { address: addresses }),
    ...(dto.organizationID && {
      managingOrganization: createOrganizationReference(dto.organizationID),
    }),
    ...(photo && { photo }),
    meta: {
      lastUpdated: getCurrentFhirDateTime(),
      ...(baseUrl && { source: baseUrl }),
    },
  }

  return user
}

/**
 * Map internal gender to FHIR gender
 */
function mapGender(gender: string): 'male' | 'female' | 'other' | 'unknown' {
  const normalized = gender.toLowerCase().trim()
  if (normalized === 'm' || normalized === 'male' || normalized === 'man') {
    return 'male'
  }
  if (normalized === 'f' || normalized === 'female' || normalized === 'woman') {
    return 'female'
  }
  if (normalized === 'other' || normalized === 'non-binary' || normalized === 'nonbinary') {
    return 'other'
  }
  return 'unknown'
}
