/**
 * User Adapter
 * Converts internal UserDTO DTO to FHIR R4 User resource
 * Auto-generated by FHIR Mapper Generator
 */

import { User } from '../../models/r4/user'
import { UserDTO } from '../../types/internal'
import { getCurrentFhirDateTime } from '../../utils/date'

/**
 * Convert internal UserDTO to FHIR User
 * @param dto - UserDTO DTO
 * @param baseUrl - Base URL for references
 */
export function toUser(dto: UserDTO, baseUrl?: string): User {
  const userId = dto.userID

  // Resource ID mapping - Direct mapping

  const user: User = {
    resourceType: 'User',
    id: userId,
    ...(id && { id: id }),
    meta: {
      lastUpdated: getCurrentFhirDateTime(),
      ...(baseUrl && { source: baseUrl }),
    },
  }

  return user
}
