REMINDER_SCHEDULER_GROUP_NAME: ${ssm:${self:custom.taskSsmPaths.${self:provider.stage}.reminderSchedulerGroupName}}
REMINDER_SCHEDULER_TARGET_ROLE_ARN: ${ssm:${self:custom.taskSsmPaths.${self:provider.stage}.reminderSchedulerTargetRoleArn}}
PROCESS_REMINDER_LAMBDA_ARN: ${ssm:${self:custom.taskSsmPaths.${self:provider.stage}.processReminderLambdaArn}}
