// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Beauty on Wheels - Service Catalog Service API",
    "version": "1"
  },
  "paths": {
    "/categories": {
      "get": {
        "summary": "List categories",
        "description": "",
        "tags": [
          "Categories"
        ],
        "operationId": "getcategories.get./categories",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "summary": "Create category",
        "description": "",
        "tags": [
          "Categories"
        ],
        "operationId": "postcategories.post./categories",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Category"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/categories/{categoryId}": {
      "get": {
        "summary": "Get category",
        "description": "",
        "tags": [
          "Categories"
        ],
        "operationId": "getcategoryid.get./categories/{categoryId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "categoryId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "put": {
        "summary": "Update category",
        "description": "",
        "tags": [
          "Categories"
        ],
        "operationId": "putcategoryid.put./categories/{categoryId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Category"
            }
          },
          {
            "name": "categoryId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Delete category",
        "description": "",
        "tags": [
          "Categories"
        ],
        "operationId": "deletecategoryid.delete./categories/{categoryId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "categoryId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          }
        }
      }
    },
    "/services": {
      "get": {
        "summary": "List services",
        "description": "",
        "tags": [
          "Services"
        ],
        "operationId": "getservices.get./services",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "summary": "Create service",
        "description": "",
        "tags": [
          "Services"
        ],
        "operationId": "postservices.post./services",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Service"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/services/{serviceId}": {
      "get": {
        "summary": "Get service",
        "description": "",
        "tags": [
          "Services"
        ],
        "operationId": "getserviceid.get./services/{serviceId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "serviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "put": {
        "summary": "Update service",
        "description": "",
        "tags": [
          "Services"
        ],
        "operationId": "putserviceid.put./services/{serviceId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Service"
            }
          },
          {
            "name": "serviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Delete service",
        "description": "",
        "tags": [
          "Services"
        ],
        "operationId": "deleteserviceid.delete./services/{serviceId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "serviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          }
        }
      }
    },
    "/packages": {
      "get": {
        "summary": "List packages",
        "description": "",
        "tags": [
          "Packages"
        ],
        "operationId": "getpackages.get./packages",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "summary": "Create package",
        "description": "",
        "tags": [
          "Packages"
        ],
        "operationId": "postpackages.post./packages",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Package"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/packages/{packageId}": {
      "get": {
        "summary": "Get package",
        "description": "",
        "tags": [
          "Packages"
        ],
        "operationId": "getpackageid.get./packages/{packageId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "packageId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "put": {
        "summary": "Update package",
        "description": "",
        "tags": [
          "Packages"
        ],
        "operationId": "putpackageid.put./packages/{packageId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Package"
            }
          },
          {
            "name": "packageId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Delete package",
        "description": "",
        "tags": [
          "Packages"
        ],
        "operationId": "deletepackageid.delete./packages/{packageId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "packageId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          }
        }
      }
    },
    "/addons": {
      "get": {
        "summary": "List add-ons",
        "description": "",
        "tags": [
          "Add-ons"
        ],
        "operationId": "getaddons.get./addons",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "summary": "Create add-on",
        "description": "",
        "tags": [
          "Add-ons"
        ],
        "operationId": "postaddons.post./addons",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddOn"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          }
        }
      }
    },
    "/addons/{addonId}": {
      "get": {
        "summary": "Get add-on",
        "description": "",
        "tags": [
          "Add-ons"
        ],
        "operationId": "getaddonid.get./addons/{addonId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "addonId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "put": {
        "summary": "Update add-on",
        "description": "",
        "tags": [
          "Add-ons"
        ],
        "operationId": "putaddonid.put./addons/{addonId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AddOn"
            }
          },
          {
            "name": "addonId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Delete add-on",
        "description": "",
        "tags": [
          "Add-ons"
        ],
        "operationId": "deleteaddonid.delete./addons/{addonId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "addonId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          }
        }
      }
    }
  },
  "definitions": {
    "Category": {
      "properties": {
        "id": {
          "title": "Category.id",
          "type": "string"
        },
        "name": {
          "title": "Category.name",
          "type": "string"
        },
        "description": {
          "title": "Category.description",
          "type": "string"
        },
        "displayOrder": {
          "title": "Category.displayOrder",
          "type": "number"
        },
        "active": {
          "title": "Category.active",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "title": "Category",
      "description": "This file was automatically generated from the OpenAPI specification.\nDO NOT EDIT DIRECTLY.",
      "type": "object"
    },
    "Service": {
      "properties": {
        "id": {
          "title": "Service.id",
          "type": "string"
        },
        "categoryId": {
          "title": "Service.categoryId",
          "type": "string"
        },
        "name": {
          "title": "Service.name",
          "type": "string"
        },
        "description": {
          "title": "Service.description",
          "type": "string"
        },
        "durationMinutes": {
          "title": "Service.durationMinutes",
          "type": "number"
        },
        "vehicleTypes": {
          "items": {
            "title": "Service.vehicleTypes.[]",
            "type": "string"
          },
          "title": "Service.vehicleTypes",
          "type": "array"
        },
        "basePrice": {
          "title": "Service.basePrice",
          "type": "number"
        },
        "active": {
          "title": "Service.active",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "title": "Service",
      "type": "object"
    },
    "Package": {
      "properties": {
        "id": {
          "title": "Package.id",
          "type": "string"
        },
        "name": {
          "title": "Package.name",
          "type": "string"
        },
        "description": {
          "title": "Package.description",
          "type": "string"
        },
        "services": {
          "items": {
            "title": "Package.services.[]",
            "type": "string"
          },
          "title": "Package.services",
          "type": "array"
        },
        "discountedPrice": {
          "title": "Package.discountedPrice",
          "type": "number"
        }
      },
      "additionalProperties": false,
      "title": "Package",
      "type": "object"
    },
    "AddOn": {
      "properties": {
        "id": {
          "title": "AddOn.id",
          "type": "string"
        },
        "name": {
          "title": "AddOn.name",
          "type": "string"
        },
        "price": {
          "title": "AddOn.price",
          "type": "number"
        },
        "durationMinutes": {
          "title": "AddOn.durationMinutes",
          "type": "number"
        }
      },
      "additionalProperties": false,
      "title": "AddOn",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};