/**
 * FHIR R4 ListUserFiles Resource
 * Based on FHIR R4 (4.0.1) specification
 * Auto-generated by FHIR Mapper Generator
 * @generated
 */

import { Resource, Reference } from './common';

export interface ListUserFiles extends Resource {
  resourceType: 'ListUserFiles';
  /** The current state of the list */
  status: 'current' | 'retired' | 'entered-in-error';
  /** How this list was prepared */
  mode?: 'working' | 'snapshot' | 'changes';
  /** A label for the list */
  title?: string;
  /** Entries in the list */
  entry?: Array<{ item: Reference }>;
}

