/**
 * FHIR R4 User Resource
 * Based on FHIR R4 (4.0.1) specification
 * Auto-generated by FHIR Mapper Generator
 * @generated
 */

import { Resource } from './common'

export interface User extends Resource {
  resourceType: 'User'
  /** Resource ID mapping */
  id: string
}
