Effect: Allow
Action:
  - dynamodb:GetItem
  - dynamodb:PutItem
  - dynamodb:UpdateItem
  - dynamodb:DeleteItem
  - dynamodb:Query
  - dynamodb:BatchGetItem
  - dynamodb:TransactWriteItems
  - dynamodb:DescribeTable
Resource:
  - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.bundle.templateDynamoTableName}
  - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.bundle.templateDynamoTableName}/index/*
