packages:
  - 'apps/*'
  - 'libs/*'
  - 'services/*'
  - 'tools/*'
  - 'backend'
  - 'api-center'
  - 'data-access'
  - 'event-platform'
  - 'packages/eslint-mavrix'
  - 'tools'
autoInstallPeers: true
