import { Command } from 'commander';
import { writeFileSync } from 'fs'; 

export function registerInitCommand(program: Command) {
  program
    .command('init')
    .description('Generate a configuration template file')
    .argument('[service-name]', 'Service name (e.g., medication-service)')
    .option('-o, --output <path>', 'Output file path (default: mapping-config.yaml)')
    .action(async (serviceName: string | undefined, options: { output?: string }) => {
      try {
        const outputPath = options.output || 'mapping-config.yaml';
        
        const template = `# FHIR Mapping Configuration
# Generated by fhir-mapper init

service:
  name: "${serviceName || 'example-service'}"
  baseUrl: "\${env:SERVICE_URL, 'http://localhost:3000'}"
  apiEndpoint: "/resources/{id}"
  method: "GET"
  authRequired: true
  responseType: "ResourceDTO"
  
  queryParameters:
    - name: "includeHistory"
      type: "boolean"
      optional: true

fhirResource:
  resourceType: "Resource"
  category: "identity"
  path: "resource"

# Field mappings from source DTO to FHIR resource
mappings:
  # Direct ID mapping
  - source: "resourceId"
    target: "id"
    transformation: "dto.resourceId"
  
  # Example: Status mapping with transformation
  - source: "status"
    target: "status"
    transformation: "mapStatus(dto.status)"
    customFunction: "mapStatus"
  
  # Example: CodeableConcept mapping
  - source: "code"
    target: "code"
    transformation: |
      createCodeableConcept(
        'http://example.com/codesystem',
        dto.code,
        dto.codeDisplay
      )
    utilityFunctions:
      - "createCodeableConcept"
    optional: true
    condition: "dto.code"

# Custom transformation functions
customTransformations:
  - name: "mapStatus"
    parameters:
      - name: "status"
        type: "string"
    returnType: "'active' | 'inactive' | 'entered-in-error'"
    code: |
      function mapStatus(status: string): 'active' | 'inactive' | 'entered-in-error' {
        const normalized = status?.toLowerCase().trim();
        if (normalized === 'active' || normalized === 'available') {
          return 'active';
        }
        if (normalized === 'inactive' || normalized === 'discontinued') {
          return 'inactive';
        }
        return 'entered-in-error';
      }

# Generation options
generation:
  generateFiles:
    - "service-client"
    - "adapter"
    - "handler"
  options:
    addComments: true
    addJSDoc: true
    includeValidation: true
    formatCode: true

# AI configuration (optional)
ai:
  enabled: true
  model: "gpt-4"
  temperature: 0.3
  maxTokens: 2000
  useForMissingMappings: true
`;

        writeFileSync(outputPath, template, 'utf-8');
        // console.log(`✅ Configuration template created: ${outputPath}`);
        // console.log('\n📝 Next steps:');
        // console.log('   1. Edit the configuration file with your service details');
        // console.log('   2. Define field mappings');
        // console.log('   3. Run: fhir-mapper generate -c mapping-config.yaml');
      } catch (error) {
        console.error('❌ Error creating template:', error);
        if (error instanceof Error) {
          console.error('   ', error.message);
        }
        process.exit(1);
      }
    });
}

