Resources:
  TemplateEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: ${self:custom.bundle.eventBusName}
      Tags:
        - Key: Service
          Value: ${self:service}
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: ManagedBy
          Value: serverless
