// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Beauty on Wheels - Vehicle Service API",
    "version": "1"
  },
  "paths": {
    "/vehicles": {
      "get": {
        "summary": "List my vehicles",
        "description": "Requires a bearer access token. Returns only vehicles owned by the authenticated user. Query status (ACTIVE or INACTIVE) or vehicleType. The platform envelope puts the list at data.items.",
        "tags": [
          "Vehicles"
        ],
        "operationId": "getvehicles.get./vehicles",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Vehicle list in data.items",
            "schema": {
              "$ref": "#/definitions/Vehicle"
            }
          }
        }
      },
      "post": {
        "summary": "Add vehicle",
        "description": "Requires a bearer access token. The vehicle is stored for the authenticated user. A client-supplied userId is ignored. HTTP 200 platform envelope; the vehicle is in data.",
        "tags": [
          "Vehicles"
        ],
        "operationId": "postvehicles.post./vehicles",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Vehicle"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Vehicle created"
          }
        }
      }
    },
    "/vehicles/{vehicleId}": {
      "get": {
        "summary": "Get vehicle",
        "description": "",
        "tags": [
          "Vehicles"
        ],
        "operationId": "getvehicleid.get./vehicles/{vehicleId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vehicleId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vehicle",
            "schema": {
              "$ref": "#/definitions/Vehicle"
            }
          }
        }
      },
      "put": {
        "summary": "Update vehicle",
        "description": "",
        "tags": [
          "Vehicles"
        ],
        "operationId": "putvehicleid.put./vehicles/{vehicleId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Vehicle"
            }
          },
          {
            "name": "vehicleId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Delete vehicle",
        "description": "Requires a bearer access token. Deletes a vehicle owned by the authenticated user. Success is HTTP 200 with the platform envelope and data null.",
        "tags": [
          "Vehicles"
        ],
        "operationId": "deletevehicleid.delete./vehicles/{vehicleId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vehicleId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Deleted"
          }
        }
      }
    },
    "/vehicles/{vehicleId}/default": {
      "put": {
        "summary": "Set default vehicle",
        "description": "",
        "tags": [
          "Vehicles"
        ],
        "operationId": "putdefault.put./vehicles/{vehicleId}/default",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vehicleId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Default vehicle updated"
          }
        }
      }
    },
    "/vehicle-types": {
      "get": {
        "summary": "List supported vehicle types",
        "description": "Requires a bearer access token. Canonical success body is the platform envelope. data.items is the vehicle type array. Clients must not expect a bare JSON array.",
        "tags": [
          "Vehicles"
        ],
        "operationId": "getvehicletypes.get./vehicle-types",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Vehicle types in data.items",
            "schema": {
              "$ref": "#/definitions/VehicleTypeList"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "VehicleTypeList": {
      "properties": {
        "items": {
          "items": {
            "enum": [
              "HATCHBACK",
              "SEDAN",
              "SUV",
              "MUV",
              "LUXURY",
              "BIKE"
            ],
            "type": "string"
          },
          "title": "VehicleTypeList.items",
          "type": "array"
        }
      },
      "required": [
        "items"
      ],
      "additionalProperties": false,
      "title": "VehicleTypeList",
      "description": "This file was automatically generated from the OpenAPI specification.\nDO NOT EDIT DIRECTLY.",
      "type": "object"
    },
    "Vehicle": {
      "properties": {
        "id": {
          "title": "Vehicle.id",
          "type": "string"
        },
        "userId": {
          "title": "Vehicle.userId",
          "type": "string"
        },
        "registrationNumber": {
          "title": "Vehicle.registrationNumber",
          "type": "string"
        },
        "vehicleType": {
          "enum": [
            "HATCHBACK",
            "SEDAN",
            "SUV",
            "MUV",
            "LUXURY",
            "BIKE"
          ],
          "title": "Vehicle.vehicleType",
          "type": "string"
        },
        "brand": {
          "title": "Vehicle.brand",
          "description": "Canonical set lives in `@api-hub/utils` `VEHICLE_TYPE_VALUES`.",
          "type": "string"
        },
        "model": {
          "title": "Vehicle.model",
          "type": "string"
        },
        "variant": {
          "title": "Vehicle.variant",
          "type": "string"
        },
        "color": {
          "title": "Vehicle.color",
          "type": "string"
        },
        "fuelType": {
          "enum": [
            "PETROL",
            "DIESEL",
            "EV",
            "HYBRID",
            "CNG"
          ],
          "title": "Vehicle.fuelType",
          "type": "string"
        },
        "manufactureYear": {
          "title": "Vehicle.manufactureYear",
          "type": "number"
        },
        "defaultVehicle": {
          "title": "Vehicle.defaultVehicle",
          "type": "boolean"
        }
      },
      "required": [
        "registrationNumber",
        "vehicleType"
      ],
      "additionalProperties": false,
      "title": "Vehicle",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};