// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "WhatsApp Channel Service API",
    "version": "1.0.0",
    "description": "Public Meta webhook and health endpoints for the Beauty on Wheels WhatsApp channel. Downstream catalog, vendor, vehicle, availability, booking, and user calls are not exposed here."
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "Health check",
        "description": "",
        "operationId": "webhook.get./health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/webhooks/whatsapp": {
      "get": {
        "summary": "Verify the Meta WhatsApp webhook",
        "description": "Returns the hub.challenge when hub.verify_token matches. This route is public because Meta calls it.",
        "operationId": "webhook.get./webhooks/whatsapp",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "Receive Meta WhatsApp webhook events",
        "description": "Validates the X-Hub-Signature-256 header, then enqueues the payload for conversation processing.",
        "operationId": "webhook.post./webhooks/whatsapp",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https"
  ]
};