service: order-service
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  # deploymentBucket:
  #   name: ${self:provider.stage}-order-service-bucket

  environment:
    STAGE: ${self:provider.stage}
    NODE_OPTIONS: "--enable-source-maps"
    LOG_LEVEL: "info"
    CORRELATION_HEADER: "x-correlation-id"
    PAYMENTS_API_BASE_URL: ${self:custom.stageConfig.${self:provider.stage}.PAYMENTS_API_BASE_URL}
    ORDERS_TABLE: ${self:custom.stageConfig.${self:provider.stage}.ORDERS_TABLE}
    PAYMENTS_SERVICE_LAMBDA_ARN: "${env:PAYMENTS_SERVICE_LAMBDA_ARN, 'arn:aws:lambda::${self:provider.region}:542476693486:function:payments-create'}"
    SKIP_EXTERNAL_INTEGRATIONS: "${env:SKIP_EXTERNAL_INTEGRATIONS, 'false'}"
    PACKAGE_TABLE: "${self:provider.stage}_global_common_packages"
    USER_TABLE: "${self:provider.stage}_global_common_user_data"
    PACKAGE_BASE_URL: ${self:custom.stageConfig.${self:provider.stage}.PACKAGE_BASE_URL}
    ERROR_MESSAGES_CDN_URL: https://d2p9v61861q1ox.cloudfront.net/
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            Fn::Sub: arn:aws:sns:${AWS::Region}:${AWS::AccountId}:*
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.stage}_global_common_orders
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.stage}_global_common_orders/index/*
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.stage}_global_common_payments
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.stage}_global_common_packages
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:provider.stage}_global_common_user_data
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: ${env:PAYMENTS_SERVICE_LAMBDA_ARN, 'arn:aws:lambda::${self:provider.region}:542476693486:function:payments-create'}
  apiGateway:
    shouldStartNameWithService: true
    metrics: true
    minimumCompressionSize: 1024
    binaryMediaTypes:
      - "*/*"
plugins:
  - serverless-esbuild
  - serverless-auto-swagger
  - serverless-dotenv-plugin
  - serverless-offline
package:
  exclude:
    - node_modules/serverless-offline/**
    - docs/**
  patterns:
    - src/utils/fonts/**
    - src/handlers/data/**

custom:
  stageConfig:
    dev:
      ORDERS_TABLE: dev_global_common_orders
      ORDERS_STREAM_ARN: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/dev_global_common_orders/stream/2025-09-29T10:44:34.117
      PAYMENTS_API_BASE_URL: https://ajrqngz4k4.execute-api.us-east-1.amazonaws.com/dev
      PACKAGE_BASE_URL: https://v1w4b4vunl.execute-api.us-east-1.amazonaws.com/dev
      DEPLOYMENT_BUCKET: dev-order-service-bucket
      STACK_NAME: dev-order-service
    stg:
      ORDERS_TABLE: stg_global_common_orders
      ORDERS_STREAM_ARN: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/stg_global_common_orders/stream/2025-10-07T14:15:16.104
      PAYMENTS_API_BASE_URL: https://ewvm7643kk.execute-api.us-east-1.amazonaws.com/stg
      PACKAGE_BASE_URL: https://7cksvft1m2.execute-api.us-east-1.amazonaws.com/stg
      DEPLOYMENT_BUCKET: stg-order-service-bucket
      STACK_NAME: stg-order-service
    prd:
      ORDERS_TABLE: prd_global_common_orders
      ORDERS_STREAM_ARN: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/prd_global_common_orders/stream/2025-10-31T14:13:18.707
      PAYMENTS_API_BASE_URL: https://ge6rykjfdc.execute-api.us-east-1.amazonaws.com/prd
      PACKAGE_BASE_URL: https://t9iqf5gu49.execute-api.us-east-1.amazonaws.com/prd
      DEPLOYMENT_BUCKET: prd-order-service-bucket
      STACK_NAME: prd-order-service
  autoswagger:
    title: "Domain API"
    apiType: "http"
    generateSwaggerOnDeploy: true
    typefiles:
      - "./src/types/api-types.d.ts"
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3010

  corsAny: &corsAny
    origin: "*"
    headers:
      - Content-Type
      - Authorization
      - Idempotency-Key
      - X-Correlation-Id
      - X-Requested-With
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token
    allowCredentials: false
    methods:
      - GET
      - POST
      - OPTIONS
functions:
  healthCheck:
    handler: src/handlers/health.healthCheck
    events:
      - http:
          path: health
          method: get
          cors: *corsAny

  orderStreamHandler:
    handler: src/handlers/orderStreamHandler.handler
    name: ${self:provider.stage}_order_stream_handler
    # events:
    #   - stream:
    #       type: dynamodb
    #       arn: ${self:custom.stageConfig.${self:provider.stage}.ORDERS_STREAM_ARN}
    #       batchSize: 10
    #       startingPosition: LATEST
    #       bisectBatchOnFunctionError: true
  createOrgOrder:
    handler: src/handlers/orders.createOrder
    events:
      - http:
          path: order/create
          method: post
          cors: *corsAny
          swaggerTags:
            - Orders
          bodyType: CreateOrgOrderRequest
          responseData:
            201:
              description: Created
              bodyType: CreateOrgOrderResponse
            202:
              description: Accepted (payment pending)
              bodyType: CreateOrgOrderResponse
  getOrder:
    handler: src/handlers/orders.getOrder
    events:
      - http:
          path: order/review
          method: post
          cors: *corsAny
  getOrderById:
    handler: src/handlers/orders.getOrderById
    events:
      - http:
          path: order/{orderId}
          method: get
          cors: *corsAny
          request:
            parameters:
              paths:
                orderId: true
              querystrings:
                orgId: true
          swaggerTags:
            - Orders
          responseData:
            200:
              description: Order fetched
  listOrders:
    handler: src/handlers/orders.listOrders
    events:
      - http:
          path: orders
          method: get
          cors: *corsAny
  requestPayment:
    handler: src/handlers/orders.requestPayment
    events:
      - http:
          path: order/{orderId}/payments
          method: post
          cors: *corsAny
          swaggerTags:
            - Orders
          request:
            parameters:
              querystrings:
                orgId: true
          queryStringParameters:
            - name: orgId
              required: true
          responseData:
            200:
              description: Payment order created
              bodyType: CreateOrgOrderResponse
  paymentEvents:
    handler: src/handlers/orders.paymentEvents
    events:
      - http:
          path: internal/payments/events
          method: post
          cors: *corsAny
          swaggerTags:
            - Payments
          bodyType: PaymentEventWebhook
          responseData:
            200:
              description: OK
  cancelOrder:
    handler: src/handlers/orders.cancelOrder
    events:
      - http:
          path: order/cancel
          method: post
          cors: *corsAny
          swaggerTags:
            - Orders
          bodyType: CancelOrderRequest
          responseData:
            200:
              description: Order cancelled
              bodyType: CancelOrderResponse
  refundPayment:
    handler: src/handlers/orders.refundPayment
    timeout: 15
    events:
      - http:
          path: order/refund
          method: post
          cors: *corsAny
          swaggerTags:
            - Orders
          bodyType: RefundOrderRequest
          responseData:
            200:
              description: Refund processed
              bodyType: RefundOrderResponse
  createPharmacyOrder:
    handler: src/handlers/orders.createPharmacyOrder
    events:
      - http:
          path: pharmacy/order
          method: post
          cors: *corsAny
          swaggerTags:
            - Orders
          bodyType: CreateOrgOrderRequest
          responseData:
            201:
              description: Created
              bodyType: CreateOrgOrderResponse
  markPaid:
    handler: src/handlers/orders.markPaid
    events:
      - http:
          path: order/complete
          method: post
          cors: *corsAny
          swaggerTags:
            - Orders
          bodyType: MarkPaidRequest
          responseData:
            200:
              description: Order marked as paid
              bodyType: MarkPaidResponse
  generateInvoice:
    handler: src/handlers/orders.generateInvoice
    events:
      - http:
          path: order/invoice
          method: post
          cors: *corsAny
          swaggerTags:
            - Orders
          bodyType: GenerateInvoiceRequest
          responseData:
            200:
              description: Invoice generated
              bodyType: GenerateInvoiceResponse

  getPaymentStatus:
    handler: src/handlers/orders.getPaymentStatus
    events:
      - http:
          path: order/payments/{paymentId}/status
          method: get
          cors: *corsAny
          pathParameters:
            - name: paymentId
              required: true
              in: path
              description: ID of the payment to retrieve status for
          swaggerTags:
            - Orders
          responseData:
            200:
              description: Invoice status retrieved
              bodyType: GenerateInvoiceResponse
            404:
              description: Invoice not found
              bodyType: ErrorResponse

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseType: DEFAULT_4XX
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,Idempotency-Key,X-Correlation-Id,X-Requested-With,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS,PUT,DELETE'"
    GatewayResponseDefault5XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        RestApiId: { Ref: ApiGatewayRestApi }
        ResponseType: DEFAULT_5XX
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,Idempotency-Key,X-Correlation-Id,X-Requested-With,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS,PUT,DELETE'"