// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "identity Service API",
    "version": "1.0.0",
    "description": "identitys: HTTP APIs. **Deployed Swagger UI uses this file + serverless-auto-swagger** — it does not load `docs/services/identity-service/api/open-api.yaml`. Rich multi-example narratives live there; this spec carries **Swagger 2–compatible `example` / `x-example`** values for Try-it-out and model panels."
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "health",
        "description": "",
        "operationId": "health.get./health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/identitys/workflow": {
      "post": {
        "summary": "Apply identity workflow command",
        "description": "Command-style workflow for one identity. Body requires `action` (START_WORK, WAIT, RESUME, RESOLVE, DISMISS, or aliases ASSIGN, MOVE_TO_WAITING, RESUME_WORK). RESOLVE/DISMISS require `reasonCode`; when reasonCode is OTHER, `comment` or `closureComment` is required. ASSIGN requires `assignedToUserId`. Organization from JWT only.\n",
        "operationId": "updateidentityWorkflow.post.identitys/workflow",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK — updated identity detail in envelope `data`"
          },
          "400": {
            "description": "Bad request (e.g. missing path context)"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "identity not found"
          }
        }
      }
    },
    "/identitys/assignment": {
      "post": {
        "summary": "Apply identity assignment action",
        "description": "Assignment actions for one or many identitys. Body requires `identityIds` and `action` (ASSIGN, REASSIGN, UNASSIGN, ASSIGN_TO_SELF). ASSIGN/REASSIGN require `assignToUserId`. ASSIGN_TO_SELF derives assignee from JWT. **All-or-nothing**: if any identity fails, none are updated. Organization from JWT only.\n",
        "operationId": "updateidentityAssignment.post.identitys/assignment",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK — updated identity detail for single-select, or `{ identityIds }` for multi-select"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "identity not found"
          },
          "409": {
            "description": "Not allowed from terminal state"
          },
          "422": {
            "description": "Validation error"
          }
        }
      }
    },
    "/identitys/priority": {
      "patch": {
        "summary": "Update identity priority",
        "description": "Priority update for one or many identitys. Body requires `identityIds` and `priority` (P0..P3). **All-or-nothing**: if any identity fails, none are updated. Organization from JWT only.\n",
        "operationId": "updateidentityPriority.patch.identitys/priority",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK — updated identity detail for single-select, or `{ identityIds }` for multi-select"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "identity not found"
          },
          "422": {
            "description": "Validation error"
          }
        }
      }
    },
    "/identitys": {
      "get": {
        "summary": "List identitys (Team, My, or Patient)",
        "description": "Use query `queue=TEAM` (default), `MY`, or `PATIENT`. For `queue=PATIENT`, `patientId` is required. For `TEAM` or `MY`, do not send `patientId` (patient timeline uses `queue=PATIENT` only). Organization scope from JWT; results are restricted to that org.\n",
        "operationId": "listidentitys.get.identitys",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "queue",
            "type": "string",
            "description": "TEAM (default), MY, or PATIENT",
            "required": false
          },
          {
            "in": "query",
            "name": "patientId",
            "type": "string",
            "description": "Required when queue=PATIENT; omit for TEAM and MY",
            "required": false
          },
          {
            "in": "query",
            "name": "state",
            "type": "string",
            "description": "Filter by identity workflow/UI state — UNASSIGNED, ASSIGNED, IN_PROGRESS, WAITING, RESOLVED, DISMISSED",
            "required": false
          },
          {
            "in": "query",
            "name": "priority",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "inputType",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "assignment",
            "type": "string",
            "description": "Assignee user id to filter by (persisted assignedToUserId — same id as workflow ASSIGN)",
            "required": false
          },
          {
            "in": "query",
            "name": "dateFrom",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "dateTo",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "search",
            "type": "string",
            "required": false
          },
          {
            "in": "query",
            "name": "pageSize",
            "type": "integer",
            "required": false
          },
          {
            "in": "query",
            "name": "nextToken",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Server error"
          }
        }
      },
      "post": {
        "summary": "Create identity",
        "description": "Requires `inputEventId` (client/UI idempotency key), `inputType`, `sourceType`, `patientId`, `triggerTimestamp`, and `evidencePayload`. Organization scope is taken from the JWT only, not the body.",
        "operationId": "createidentity.post.identitys",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateidentityRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK — identityDetail in envelope (new identity or same-org idempotent replay on inputEventId)"
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "409": {
            "description": "Conflict (e.g. IDEMPOTENCY_KEY_IN_USE for different org)"
          },
          "422": {
            "description": "Validation or business rule error"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/identitys/{identityId}": {
      "get": {
        "summary": "Get identity by id",
        "description": "identity detail for the authenticated organization (tenant from JWT only).",
        "operationId": "getidentity.get.identitys/{identityId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "identityId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/identitys/{identityId}/activity": {
      "get": {
        "summary": "Get identity activity timeline",
        "description": "Activity / audit list for the identity (newest first; no pagination). Tenant from JWT only. Optional query Optional query `notesOnly=true` or `false` (`true` = NOTE_ADDED only). 404 when identity not found for org.\n",
        "operationId": "getidentityActivity.get.identitys/{identityId}/activity",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "identityId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/identitys/{identityId}/notes": {
      "post": {
        "summary": "Add an operational note",
        "description": "Add a note to the identity activity timeline. Organization comes from JWT.",
        "operationId": "addidentityNote.post.identitys/{identityId}/notes",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NoteRequest"
            }
          },
          {
            "name": "identityId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Created (NOTE_ADDED activity)"
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Not found"
          },
          "409": {
            "description": "Illegal state transition (ILLEGAL_TRANSITION)"
          },
          "422": {
            "description": "Validation (body, reason codes, OTHER without comment, MISSING_REASON_CODE)"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/upload-url": {
      "post": {
        "summary": "Get upload URL for a file",
        "description": "Get an upload URL for a file",
        "operationId": "getUploadUrl.post.upload-url",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UploadUrlRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/download-url": {
      "post": {
        "summary": "Get download URL for a file",
        "description": "Get a presigned download URL for a single file in a folder",
        "operationId": "getDownloadUrl.post.download-url",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/list-files": {
      "get": {
        "summary": "List files in a folder",
        "description": "List S3 objects under a folder prefix",
        "operationId": "listFiles.get.list-files",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/dev/events/ingest/create-identity": {
      "post": {
        "summary": "testPublishCreateidentityIngest",
        "description": "",
        "operationId": "testPublishCreateidentityIngest.post.dev/events/ingest/create-identity",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/identitys/metadata": {
      "get": {
        "summary": "identity UI metadata (workaround)",
        "description": "Static lists for priorities, workflow statuses, resolve reasons, and dismiss reasons until a metadata registry is available. Organization scope from JWT; response is the same for all tenants.\n",
        "operationId": "getidentityMetadata.get.identitys/metadata",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },
  "definitions": {
    "InputType": {
      "type": "string",
      "enum": [
        "THRESHOLD_BREACH",
        "MISSED_READING",
        "MISSING_DEVICE",
        "SYMPTOM_RISK_TRIGGER",
        "ENGAGEMENT_TRIGGER"
      ]
    },
    "CreateidentityInputType": {
      "type": "string",
      "description": "POST /identitys only — §5.1.3.1 (MISSED_READING | MISSING_DEVICE).",
      "enum": [
        "MISSED_READING",
        "MISSING_DEVICE"
      ]
    },
    "SourceType": {
      "type": "string",
      "enum": [
        "MONITORING_SERVICE",
        "DEVICE_MONITORING",
        "DEVICE_WORKFLOW",
        "SYMPTOM_ENGINE",
        "ENGAGEMENT_SERVICE",
        "USER_INTERFACE"
      ]
    },
    "AppliesToType": {
      "type": "string",
      "description": "Product-defined label for what the identity applies to (e.g. VITAL_SIGN, DEVICE)."
    },
    "SeverityHint": {
      "type": "string",
      "description": "Optional severity label from the producer (any string; not restricted to LOW/MEDIUM/HIGH/CRITICAL)."
    },
    "EvidenceMissedReading": {
      "type": "object",
      "description": "MISSED_READING evidence (strict). Required: eventTimestamp, source, inputType, appliesToType, linkedEntityCode, lastSuccessfulReadingTimestamp, missedDuration, readingType. Must match top-level inputType; source must match sourceType.",
      "required": [
        "eventTimestamp",
        "source",
        "inputType",
        "appliesToType",
        "linkedEntityCode",
        "lastSuccessfulReadingTimestamp",
        "missedDuration",
        "readingType"
      ],
      "properties": {
        "eventTimestamp": {
          "type": "string",
          "minLength": 1,
          "format": "date-time",
          "description": "When the missed-reading condition was observed (ISO-8601 date-time)."
        },
        "source": {
          "$ref": "#/definitions/SourceType"
        },
        "inputType": {
          "type": "string",
          "enum": [
            "MISSED_READING"
          ]
        },
        "appliesToType": {
          "$ref": "#/definitions/AppliesToType"
        },
        "linkedEntityCode": {
          "type": "string",
          "minLength": 1,
          "description": "Product code for the linked entity (e.g. BP_SYSTOLIC); non-empty."
        },
        "lastSuccessfulReadingTimestamp": {
          "type": "string",
          "minLength": 1,
          "format": "date-time",
          "description": "Last good reading time before the miss (ISO-8601 date-time)."
        },
        "missedDuration": {
          "type": "string",
          "minLength": 1,
          "description": "Non-empty duration string (e.g. ISO-8601 P3D) or product-specific token."
        },
        "readingType": {
          "type": "string",
          "minLength": 1,
          "description": "Reading / vital family label (e.g. BLOOD_PRESSURE); non-empty."
        }
      },
      "additionalProperties": false,
      "example": {
        "eventTimestamp": "2026-04-17T10:00:00.000Z",
        "source": "DEVICE_MONITORING",
        "inputType": "MISSED_READING",
        "appliesToType": "VITAL_SIGN",
        "linkedEntityCode": "BP_SYSTOLIC",
        "lastSuccessfulReadingTimestamp": "2026-04-14T08:00:00.000Z",
        "missedDuration": "P3D",
        "readingType": "BLOOD_PRESSURE"
      }
    },
    "EvidenceMissingDevice": {
      "type": "object",
      "description": "MISSING_DEVICE evidence (strict). Required: eventTimestamp, source, inputType, appliesToType, linkedEntityCode, deviceLinked.",
      "required": [
        "eventTimestamp",
        "source",
        "inputType",
        "appliesToType",
        "linkedEntityCode",
        "deviceLinked"
      ],
      "properties": {
        "eventTimestamp": {
          "type": "string",
          "minLength": 1,
          "format": "date-time",
          "description": "When the missing-device condition was observed (ISO-8601 date-time)."
        },
        "source": {
          "$ref": "#/definitions/SourceType"
        },
        "inputType": {
          "type": "string",
          "enum": [
            "MISSING_DEVICE"
          ]
        },
        "appliesToType": {
          "$ref": "#/definitions/AppliesToType"
        },
        "linkedEntityCode": {
          "type": "string",
          "minLength": 1,
          "description": "Product code for the device or catalog entry (e.g. WEIGHING_SCALE); non-empty."
        },
        "deviceLinked": {
          "type": "boolean",
          "description": "Whether the patient has an active link to the device in context."
        }
      },
      "additionalProperties": false,
      "example": {
        "eventTimestamp": "2026-04-17T10:00:00.000Z",
        "source": "DEVICE_WORKFLOW",
        "inputType": "MISSING_DEVICE",
        "appliesToType": "DEVICE",
        "linkedEntityCode": "WEIGHING_SCALE",
        "deviceLinked": false
      }
    },
    "EvidencePayload": {
      "type": "object",
      "description": "POST /identitys: discriminated by inputType (MISSED_READING | MISSING_DEVICE). Common fields: eventTimestamp, source, inputType, appliesToType, linkedEntityCode; plus variant fields. Strict: no extra properties. source must equal top-level sourceType.",
      "oneOf": [
        {
          "$ref": "#/definitions/EvidenceMissedReading"
        },
        {
          "$ref": "#/definitions/EvidenceMissingDevice"
        }
      ]
    },
    "CreateidentityRequest": {
      "type": "object",
      "description": "Create-identity body; organization from JWT. Required: inputEventId, inputType, sourceType, patientId, triggerTimestamp, evidencePayload. Optional: patientName, actorName (client display names). evidencePayload is EvidenceMissedReading or EvidenceMissingDevice (strict). Unknown top-level properties rejected.",
      "additionalProperties": false,
      "required": [
        "inputEventId",
        "inputType",
        "sourceType",
        "patientId",
        "triggerTimestamp",
        "evidencePayload"
      ],
      "properties": {
        "inputEventId": {
          "type": "string",
          "description": "Required. Client-generated idempotency key (e.g. from UI)."
        },
        "inputType": {
          "allOf": [
            {
              "$ref": "#/definitions/CreateidentityInputType"
            }
          ],
          "description": "Required. MISSED_READING or MISSING_DEVICE."
        },
        "sourceType": {
          "allOf": [
            {
              "$ref": "#/definitions/SourceType"
            }
          ],
          "description": "Required. Must match evidencePayload.source."
        },
        "patientId": {
          "type": "string",
          "description": "Required."
        },
        "patientName": {
          "type": "string",
          "description": "Optional. Patient display name from the UI; stored for list/detail."
        },
        "actorName": {
          "type": "string",
          "description": "Optional. Display name of the API caller (actor); not from JWT."
        },
        "carePlanInstanceId": {
          "type": "string",
          "description": "Optional. When the event is tied to an active care plan."
        },
        "packageAssignmentId": {
          "type": "string",
          "description": "Optional. Package context when relevant."
        },
        "triggerTimestamp": {
          "type": "string",
          "format": "date-time",
          "description": "Required. When the condition occurred (ISO 8601 date-time)."
        },
        "severityHint": {
          "allOf": [
            {
              "$ref": "#/definitions/SeverityHint"
            }
          ],
          "description": "Optional."
        },
        "priority": {
          "type": "string",
          "enum": [
            "P0",
            "P1",
            "P2",
            "P3"
          ],
          "description": "Optional. Resolved priority; derived from policy when omitted."
        },
        "identityPolicyTemplateVersionId": {
          "type": "string",
          "description": "Optional. Policy template version."
        },
        "thresholdTemplateVersionId": {
          "type": "string",
          "description": "Optional. Threshold template version when applicable."
        },
        "groupingKey": {
          "type": "string",
          "description": "Optional. Runtime grouping; may be computed server-side if omitted."
        },
        "triggerSummary": {
          "type": "string",
          "description": "Optional. Pre-rendered summary when not using a template."
        },
        "triggerSummaryTemplateCode": {
          "type": "string",
          "description": "Optional. Pair with triggerSummaryParams when set."
        },
        "triggerSummaryParams": {
          "type": "object",
          "additionalProperties": true,
          "description": "Optional unless triggerSummaryTemplateCode is set; then required (may be {})."
        },
        "evidencePayload": {
          "allOf": [
            {
              "$ref": "#/definitions/EvidencePayload"
            }
          ],
          "description": "Required. Per inputType; see EvidenceMissedReading or EvidenceMissingDevice."
        }
      },
      "example": {
        "inputEventId": "ui-missed-reading-001",
        "inputType": "MISSED_READING",
        "sourceType": "MONITORING_SERVICE",
        "patientId": "pat-123",
        "patientName": "Jane Doe",
        "actorName": "Dr. Smith",
        "triggerTimestamp": "2026-04-17T10:00:00.000Z",
        "evidencePayload": {
          "eventTimestamp": "2026-04-17T10:00:00.000Z",
          "source": "MONITORING_SERVICE",
          "inputType": "MISSED_READING",
          "appliesToType": "VITAL_SIGN",
          "linkedEntityCode": "BP_SYSTOLIC",
          "lastSuccessfulReadingTimestamp": "2026-04-14T08:00:00.000Z",
          "missedDuration": "P3D",
          "readingType": "BLOOD_PRESSURE"
        }
      }
    },
    "PatchidentityRequest": {
      "type": "object",
      "properties": {
        "identityState": {
          "type": "string",
          "enum": [
            "UNASSIGNED",
            "ASSIGNED",
            "IN_PROGRESS",
            "WAITING",
            "RESOLVED",
            "DISMISSED"
          ]
        },
        "assignedToUserId": {
          "type": "string",
          "description": "Assignee user id or null to clear assignment",
          "x-nullable": true
        },
        "slaBreachIndicator": {
          "type": "boolean"
        }
      },
      "example": {
        "identityState": "IN_PROGRESS",
        "assignedToUserId": "5fa85f64-5717-4562-b3fc-2c963f66afa8",
        "slaBreachIndicator": false
      }
    },
    "identityIds": {
      "type": "array",
      "description": "One or many identity ids (single-select = array of one element).",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 100
    },
    "WorkflowAction": {
      "type": "string",
      "enum": [
        "ASSIGN",
        "START_WORK",
        "MOVE_TO_WAITING",
        "RESUME_WORK",
        "RESOLVE",
        "DISMISS"
      ]
    },
    "WorkflowRequest": {
      "type": "object",
      "required": [
        "identityIds",
        "action",
        "performedByDisplayName"
      ],
      "properties": {
        "identityIds": {
          "$ref": "#/definitions/identityIds"
        },
        "action": {
          "$ref": "#/definitions/WorkflowAction"
        },
        "assignedToUserId": {
          "type": "string"
        },
        "assigneeDisplayName": {
          "type": "string"
        },
        "reasonCode": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        },
        "closureComment": {
          "type": "string"
        },
        "performedByDisplayName": {
          "type": "string"
        }
      },
      "example": {
        "identityIds": [
          "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        ],
        "action": "START_WORK",
        "performedByDisplayName": "Nurse Lee"
      }
    },
    "AssignmentAction": {
      "type": "string",
      "enum": [
        "ASSIGN",
        "ASSIGN_TO_SELF",
        "REASSIGN",
        "UNASSIGN"
      ]
    },
    "AssignmentRequest": {
      "type": "object",
      "required": [
        "action",
        "performedByDisplayName"
      ],
      "properties": {
        "action": {
          "$ref": "#/definitions/AssignmentAction"
        },
        "assignToUserId": {
          "type": "string",
          "description": "Required for ASSIGN and REASSIGN."
        },
        "assigneeDisplayName": {
          "type": "string",
          "description": "Required for ASSIGN, REASSIGN, and ASSIGN_TO_SELF."
        },
        "performedByDisplayName": {
          "type": "string"
        }
      },
      "example": {
        "action": "ASSIGN",
        "assignToUserId": "5fa85f64-5717-4562-b3fc-2c963f66afa8",
        "assigneeDisplayName": "Dr Smith",
        "performedByDisplayName": "Nurse Lee"
      }
    },
    "AssignmentRequestBody": {
      "allOf": [
        {
          "type": "object",
          "required": [
            "identityIds"
          ],
          "properties": {
            "identityIds": {
              "$ref": "#/definitions/identityIds"
            }
          }
        },
        {
          "$ref": "#/definitions/AssignmentRequest"
        }
      ]
    },
    "PriorityUpdateRequestBody": {
      "type": "object",
      "required": [
        "identityIds",
        "priority",
        "performedByDisplayName"
      ],
      "properties": {
        "identityIds": {
          "$ref": "#/definitions/identityIds"
        },
        "priority": {
          "type": "string",
          "enum": [
            "P0",
            "P1",
            "P2",
            "P3"
          ]
        },
        "performedByDisplayName": {
          "type": "string"
        }
      },
      "example": {
        "identityIds": [
          "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        ],
        "priority": "P1",
        "performedByDisplayName": "Nurse Lee"
      }
    },
    "NoteRequest": {
      "type": "object",
      "required": [
        "comment",
        "performedByDisplayName"
      ],
      "properties": {
        "comment": {
          "type": "string"
        },
        "performedByDisplayName": {
          "type": "string"
        }
      },
      "example": {
        "comment": "Reviewed identity; will follow up.",
        "performedByDisplayName": "Nurse Lee"
      }
    },
    "ActivityType": {
      "type": "string",
      "enum": [
        "identity_CREATED",
        "identity_GROUPED",
        "identity_ASSIGNED",
        "identity_REASSIGNED",
        "identity_STATE_CHANGED",
        "EVIDENCE_ADDED_OR_UPDATED",
        "identity_RESOLVED",
        "identity_DISMISSED",
        "SLA_BREACHED",
        "NOTE_ADDED",
        "PRIORITY_CHANGED"
      ]
    },
    "EpochMillis": {
      "type": "integer",
      "format": "int64",
      "description": "Unix epoch milliseconds (UTC) for identity SLA instants and activity rows."
    },
    "Paginatedidentitys": {
      "type": "object",
      "description": "`data` for GET /identitys — items are identityDetail (`toidentityDetail`).",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/identityDetail"
          }
        },
        "nextToken": {
          "type": "string",
          "description": "Opaque pagination cursor."
        }
      }
    },
    "identitySummary": {
      "type": "object",
      "description": "Subset of persisted identity fields exposed on detail; instants are epoch ms (`toidentityDetail`).",
      "properties": {
        "identityId": {
          "type": "string"
        },
        "priority": {
          "type": "string"
        },
        "identityState": {
          "type": "string"
        },
        "inputType": {
          "type": "string"
        },
        "sourceType": {
          "type": "string"
        },
        "triggerSummary": {
          "type": "string"
        },
        "triggerTimestamp": {
          "$ref": "#/definitions/EpochMillis"
        },
        "groupingKey": {
          "type": "string"
        },
        "patientId": {
          "type": "string"
        },
        "patientName": {
          "type": "string"
        },
        "actorName": {
          "type": "string"
        },
        "assignedToUserId": {
          "type": "string",
          "x-nullable": true
        },
        "assignedToDisplayName": {
          "type": "string"
        },
        "slaBreachIndicator": {
          "type": "boolean"
        },
        "assignSlaDueAt": {
          "$ref": "#/definitions/EpochMillis"
        },
        "resolveSlaDueAt": {
          "$ref": "#/definitions/EpochMillis"
        },
        "createdAt": {
          "$ref": "#/definitions/EpochMillis"
        }
      }
    },
    "identityDetail": {
      "allOf": [
        {
          "$ref": "#/definitions/identitySummary"
        },
        {
          "type": "object",
          "properties": {
            "inputEventId": {
              "type": "string"
            },
            "orgId": {
              "type": "string"
            },
            "evidencePayload": {
              "type": "object",
              "additionalProperties": true
            },
            "groupId": {
              "type": "string"
            },
            "assignedAt": {
              "$ref": "#/definitions/EpochMillis"
            },
            "assignedBy": {
              "type": "string"
            },
            "statusUpdatedAt": {
              "$ref": "#/definitions/EpochMillis"
            },
            "statusUpdatedBy": {
              "type": "string"
            },
            "closureComment": {
              "type": "string"
            },
            "resolutionCode": {
              "type": "string"
            },
            "dismissReason": {
              "type": "string"
            },
            "assignSla": {
              "type": "integer"
            },
            "resolveSla": {
              "type": "integer"
            },
            "assignSlaBreachedAt": {
              "$ref": "#/definitions/EpochMillis"
            },
            "resolveSlaBreachedAt": {
              "$ref": "#/definitions/EpochMillis"
            },
            "updatedAt": {
              "$ref": "#/definitions/EpochMillis"
            },
            "carePlanInstanceId": {
              "type": "string"
            },
            "packageAssignmentId": {
              "type": "string"
            },
            "identityPolicyTemplateVersionId": {
              "type": "string"
            },
            "thresholdTemplateVersionId": {
              "type": "string"
            }
          }
        }
      ]
    },
    "SuccessEnvelopeidentityDetail": {
      "type": "object",
      "description": "ApiResponse.ok body with identityDetail in `data` (POST /identitys, GET /identitys/{id}).",
      "properties": {
        "success": {
          "type": "boolean",
          "example": true
        },
        "statusCode": {
          "type": "integer",
          "example": 200
        },
        "message": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "severity": {
              "type": "string"
            }
          }
        },
        "data": {
          "$ref": "#/definitions/identityDetail"
        },
        "error": {
          "type": "object",
          "x-nullable": true
        },
        "meta": {
          "type": "object",
          "properties": {
            "requestId": {
              "type": "string"
            },
            "timestamp": {
              "type": "string",
              "format": "date-time"
            },
            "version": {
              "type": "string",
              "enum": [
                "v1"
              ]
            }
          }
        }
      }
    },
    "SuccessEnvelopePaginatedidentitys": {
      "type": "object",
      "description": "ApiResponse.ok body for GET /identitys.",
      "properties": {
        "success": {
          "type": "boolean",
          "example": true
        },
        "statusCode": {
          "type": "integer",
          "example": 200
        },
        "message": {
          "type": "object"
        },
        "data": {
          "$ref": "#/definitions/Paginatedidentitys"
        },
        "error": {
          "type": "object",
          "x-nullable": true
        },
        "meta": {
          "type": "object"
        }
      }
    },
    "ActivityRecord": {
      "type": "object",
      "description": "One audit / timeline row for an identity.",
      "properties": {
        "activityId": {
          "type": "string"
        },
        "identityId": {
          "type": "string"
        },
        "activityType": {
          "$ref": "#/definitions/ActivityType"
        },
        "activityTimestamp": {
          "$ref": "#/definitions/EpochMillis"
        },
        "performedBy": {
          "type": "string"
        },
        "performedByDisplayName": {
          "type": "string"
        },
        "activityComment": {
          "type": "string"
        },
        "previousState": {
          "type": "string"
        },
        "newState": {
          "type": "string"
        },
        "previousPriority": {
          "type": "string"
        },
        "newPriority": {
          "type": "string"
        },
        "previousAssignee": {
          "type": "string"
        },
        "newAssignee": {
          "type": "string"
        },
        "previousAssigneeDisplayName": {
          "type": "string"
        },
        "newAssigneeDisplayName": {
          "type": "string"
        },
        "evidencePayload": {
          "type": "object",
          "additionalProperties": true
        }
      }
    },
    "ActivityList": {
      "type": "object",
      "description": "Full activity timeline for one identity (no pagination).",
      "required": [
        "items"
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ActivityRecord"
          }
        }
      },
      "example": {
        "items": [
          {
            "activityId": "a1b2c3d4-0000-0000-0000-000000000001",
            "identityId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "activityType": "identity_CREATED",
            "activityTimestamp": 1735890300000,
            "performedBy": "SYSTEM"
          }
        ]
      }
    },
    "SuccessEnvelopeActivityList": {
      "type": "object",
      "description": "Standard ApiResponse.ok body; full activity list is in `data.items`.",
      "properties": {
        "success": {
          "type": "boolean",
          "example": true
        },
        "statusCode": {
          "type": "integer",
          "example": 200
        },
        "data": {
          "$ref": "#/definitions/ActivityList"
        },
        "error": {
          "type": "object",
          "x-nullable": true
        },
        "message": {
          "type": "object"
        },
        "meta": {
          "type": "object"
        }
      },
      "example": {
        "success": true,
        "statusCode": 200,
        "data": {
          "items": [
            {
              "activityId": "a1b2c3d4-0000-0000-0000-000000000001",
              "identityId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "activityType": "identity_CREATED",
              "activityTimestamp": 1735890300000,
              "performedBy": "SYSTEM"
            }
          ]
        },
        "error": null,
        "message": {
          "title": "SUCCESS",
          "description": "Request processed successfully",
          "severity": "SUCCESS"
        },
        "meta": {
          "requestId": "req-example",
          "timestamp": "2026-04-17T10:05:01.000Z",
          "version": "v1"
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "Bearer JWT from the identity provider."
    }
  },
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ]
};