import { z } from 'zod';

const supportedVitalsSchema = z
  .array(z.string())
  .or(z.array(z.record(z.string(), z.unknown())))
  .optional();

export const createOrganizationSchema = z.object({
  organizationId: z.string().optional(),
  parentOrgId: z.string().optional(),
  createdAt: z.number().optional(),
  createdBy: z.string().optional(),
  modifiedBy: z.string().optional(),
  traceId: z.string().optional(),
  name: z.string().min(1).max(255),
  email: z.string().email().optional(),
  phone: z.string().optional(),
  phoneCode: z.string().optional(),
  phoneNumber: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string().optional(),
  countryCode: z.string().optional(),
  postalCode: z.string().optional(),
  status: z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING']).optional().default('PENDING'),
  lsi_createdAt: z.number().optional(),
  lsi_entityType: z.string().optional(),
  lsi_organizationType: z.string().optional(),
  lsi_status: z.string().optional(),
  organizationType: z.string().optional(),
  organizationSize: z.string().optional(),
  noOfBranches: z.string().optional(),
  hospitalImage: z.string().optional(),
  googleMapsLink: z.string().optional(),
  hospitalBio: z.string().optional(),
  licenseNumber: z.string().optional(),
  scheduleConf: z.unknown().optional(),
  defaultSetting: z.unknown().optional(),
  goals: z.unknown().optional(),
  thresholds: z.unknown().optional(),
  workingHours: z.unknown().optional(),
  specialization: z.unknown().optional(),
  certifications: z.unknown().optional(),
  servicesOffered: z.unknown().optional(),
  appointmentType: z.unknown().optional(),
  facilityType: z.unknown().optional(),
  equipmentAvailable: z.unknown().optional(),
  emergencySupport: z.unknown().optional(),
  industryType: z.unknown().optional(),
  wellnessPrograms: z.unknown().optional(),
  onsiteFacilities: z.unknown().optional(),
  employeeCoverage: z.unknown().optional(),
  insurancePartnerships: z.boolean().optional(),
  remoteWellnessSupport: z.boolean().optional(),
  corporateDiscounts: z.boolean().optional(),
  adminDetails: z.unknown().optional(),
  modules: z.unknown().optional(),
  devices: z.unknown().optional(),
  supportedVitals: supportedVitalsSchema,
  organizationInfo: z.unknown().optional(),
  searchFields: z.unknown().optional(),
  website: z.string().optional(),
  taxId: z.string().optional(),
  registrationNumber: z.string().optional(),
  description: z.string().optional(),
  industry: z.string().optional(),
  size: z.enum(['SMALL', 'MEDIUM', 'LARGE']).optional(),
});

export const updateOrganizationSchema = z.object({
  name: z.string().min(1).max(255).optional(),
  parentOrgId: z.string().optional(),
  createdAt: z.number().optional(),
  createdBy: z.string().optional(),
  modifiedBy: z.string().optional(),
  traceId: z.string().optional(),
  email: z.string().email().optional(),
  phone: z.string().optional(),
  phoneCode: z.string().optional(),
  phoneNumber: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string().optional(),
  countryCode: z.string().optional(),
  postalCode: z.string().optional(),
  status: z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING']).optional(),
  lsi_createdAt: z.number().optional(),
  lsi_entityType: z.string().optional(),
  lsi_organizationType: z.string().optional(),
  lsi_status: z.string().optional(),
  organizationType: z.string().optional(),
  organizationSize: z.string().optional(),
  noOfBranches: z.string().optional(),
  hospitalImage: z.string().optional(),
  googleMapsLink: z.string().optional(),
  hospitalBio: z.string().optional(),
  licenseNumber: z.string().optional(),
  scheduleConf: z.unknown().optional(),
  defaultSetting: z.unknown().optional(),
  goals: z.unknown().optional(),
  thresholds: z.unknown().optional(),
  workingHours: z.unknown().optional(),
  specialization: z.unknown().optional(),
  certifications: z.unknown().optional(),
  servicesOffered: z.unknown().optional(),
  appointmentType: z.unknown().optional(),
  facilityType: z.unknown().optional(),
  equipmentAvailable: z.unknown().optional(),
  emergencySupport: z.unknown().optional(),
  industryType: z.unknown().optional(),
  wellnessPrograms: z.unknown().optional(),
  onsiteFacilities: z.unknown().optional(),
  employeeCoverage: z.unknown().optional(),
  insurancePartnerships: z.boolean().optional(),
  remoteWellnessSupport: z.boolean().optional(),
  corporateDiscounts: z.boolean().optional(),
  adminDetails: z.unknown().optional(),
  modules: z.unknown().optional(),
  devices: z.unknown().optional(),
  supportedVitals: supportedVitalsSchema,
  organizationInfo: z.unknown().optional(),
  searchFields: z.unknown().optional(),
  website: z.string().optional(),
  taxId: z.string().optional(),
  registrationNumber: z.string().optional(),
  description: z.string().optional(),
  industry: z.string().optional(),
  size: z.enum(['SMALL', 'MEDIUM', 'LARGE']).optional(),
});

export const updateOrganizationMetadataSchema = z.object({
  metadata: z.record(z.string(), z.unknown()).refine((obj) => Object.keys(obj).length > 0, {
    message: 'Metadata must be a non-empty object',
  }),
  updatedBy: z.string().optional(),
  version: z.number().int().nonnegative().optional(),
});

export const linkUnlinkOrganizationSchema = z.object({
  fromOrg: z.string().min(1, 'fromOrg is required'),
  toOrg: z.string().min(1, 'toOrg is required'),
  action: z.enum(['LINK', 'UNLINK'], { message: 'action must be LINK or UNLINK' }),
});

export const getLinkedOrganizationsSchema = z.object({
  organizationId: z.string().min(1, 'organizationId is required'),
  orgType: z.string().optional(),
  userId: z.string().optional(),
  preferredOrgId: z.string().optional(),
  limit: z.union([z.number().int().positive(), z.string().transform((s) => (s ? Number(s) : undefined))]).optional(),
  nextPaginationKey: z.string().optional(),
});

export const setOrgStatusSchema = z.object({
  organizationId: z.string().min(1, 'organizationId is required'),
  status: z.enum(['ACTIVE', 'HOLD', 'DISABLED'], { message: 'status must be ACTIVE, HOLD, or DISABLED' }),
});
