// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Beauty on Wheels - Identity Service API",
    "version": "1"
  },
  "paths": {
    "/auth/register": {
      "post": {
        "summary": "Register a new user",
        "description": "",
        "tags": [
          "Registration"
        ],
        "operationId": "postregister.post./auth/register",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User created",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login",
        "description": "",
        "tags": [
          "Authentication"
        ],
        "operationId": "postlogin.post./auth/login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LoginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Login successful",
            "schema": {
              "$ref": "#/definitions/TokenResponse"
            }
          }
        }
      }
    },
    "/auth/refresh-token": {
      "post": {
        "summary": "Refresh access token",
        "description": "",
        "tags": [
          "Authentication"
        ],
        "operationId": "postrefreshtoken.post./auth/refresh-token",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RefreshTokenRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Token refreshed",
            "schema": {
              "$ref": "#/definitions/TokenResponse"
            }
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "Logout current session",
        "description": "",
        "tags": [
          "Authentication"
        ],
        "operationId": "postlogout.post./auth/logout",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "204": {
            "description": "Logged out"
          }
        }
      }
    },
    "/auth/change-password": {
      "post": {
        "summary": "Change password",
        "description": "",
        "tags": [
          "Authentication"
        ],
        "operationId": "postchangepassword.post./auth/change-password",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ChangePasswordRequest"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Password changed"
          }
        }
      }
    },
    "/otp/send": {
      "post": {
        "summary": "Send OTP",
        "description": "",
        "tags": [
          "OTP"
        ],
        "operationId": "postsend.post./otp/send",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SendOtpRequest"
            }
          }
        ],
        "responses": {
          "202": {
            "description": "OTP sent"
          }
        }
      }
    },
    "/otp/verify": {
      "post": {
        "summary": "Verify OTP",
        "description": "",
        "tags": [
          "OTP"
        ],
        "operationId": "postverify.post./otp/verify",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/VerifyOtpRequest"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "OTP verified"
          }
        }
      }
    },
    "/me": {
      "get": {
        "summary": "Current authenticated user",
        "description": "",
        "tags": [
          "Profile"
        ],
        "operationId": "getme.get./me",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Profile",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    },
    "/sessions": {
      "get": {
        "summary": "List active sessions",
        "description": "",
        "tags": [
          "Sessions"
        ],
        "operationId": "getsessions.get./sessions",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Sessions"
          }
        }
      },
      "delete": {
        "summary": "Logout from all devices",
        "description": "",
        "tags": [
          "Sessions"
        ],
        "operationId": "deletesessions.delete./sessions",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "204": {
            "description": "All sessions revoked"
          }
        }
      }
    },
    "/sessions/{sessionId}": {
      "delete": {
        "summary": "Revoke a session",
        "description": "",
        "tags": [
          "Sessions"
        ],
        "operationId": "deletesessionid.delete./sessions/{sessionId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sessionId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Session revoked"
          }
        }
      }
    },
    "/roles": {
      "get": {
        "summary": "List roles",
        "description": "",
        "tags": [
          "Roles"
        ],
        "operationId": "getroles.get./roles",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Roles list"
          }
        }
      }
    },
    "/permissions": {
      "get": {
        "summary": "List permissions",
        "description": "",
        "tags": [
          "Permissions"
        ],
        "operationId": "getpermissions.get./permissions",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Permissions list"
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "properties": {
        "code": {
          "title": "Error.code",
          "type": "string"
        },
        "message": {
          "title": "Error.message",
          "type": "string"
        },
        "traceId": {
          "title": "Error.traceId",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "Error",
      "description": "This file was automatically generated from the OpenAPI specification.\nDO NOT EDIT DIRECTLY.",
      "type": "object"
    },
    "User": {
      "properties": {
        "id": {
          "title": "User.id",
          "type": "string"
        },
        "email": {
          "title": "User.email",
          "type": "string"
        },
        "phone": {
          "title": "User.phone",
          "type": "string"
        },
        "status": {
          "enum": [
            "PENDING_VERIFICATION",
            "ACTIVE",
            "LOCKED",
            "DISABLED"
          ],
          "title": "User.status",
          "type": "string"
        },
        "roles": {
          "items": {
            "title": "User.roles.[]",
            "type": "string"
          },
          "title": "User.roles",
          "type": "array"
        }
      },
      "additionalProperties": false,
      "title": "User",
      "type": "object"
    },
    "RegisterRequest": {
      "properties": {
        "firstName": {
          "title": "RegisterRequest.firstName",
          "type": "string"
        },
        "lastName": {
          "title": "RegisterRequest.lastName",
          "type": "string"
        },
        "email": {
          "title": "RegisterRequest.email",
          "type": "string"
        },
        "phone": {
          "title": "RegisterRequest.phone",
          "type": "string"
        },
        "password": {
          "title": "RegisterRequest.password",
          "type": "string"
        }
      },
      "required": [
        "firstName",
        "lastName",
        "email",
        "password"
      ],
      "additionalProperties": false,
      "title": "RegisterRequest",
      "type": "object"
    },
    "LoginRequest": {
      "properties": {
        "username": {
          "title": "LoginRequest.username",
          "type": "string"
        },
        "password": {
          "title": "LoginRequest.password",
          "type": "string"
        }
      },
      "required": [
        "username",
        "password"
      ],
      "additionalProperties": false,
      "title": "LoginRequest",
      "type": "object"
    },
    "TokenResponse": {
      "properties": {
        "accessToken": {
          "title": "TokenResponse.accessToken",
          "type": "string"
        },
        "refreshToken": {
          "title": "TokenResponse.refreshToken",
          "type": "string"
        },
        "expiresIn": {
          "title": "TokenResponse.expiresIn",
          "type": "number"
        },
        "tokenType": {
          "title": "TokenResponse.tokenType",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "TokenResponse",
      "type": "object"
    },
    "RefreshTokenRequest": {
      "properties": {
        "refreshToken": {
          "title": "RefreshTokenRequest.refreshToken",
          "type": "string"
        }
      },
      "required": [
        "refreshToken"
      ],
      "additionalProperties": false,
      "title": "RefreshTokenRequest",
      "type": "object"
    },
    "VerifyOtpRequest": {
      "properties": {
        "destination": {
          "title": "VerifyOtpRequest.destination",
          "type": "string"
        },
        "otp": {
          "title": "VerifyOtpRequest.otp",
          "type": "string"
        }
      },
      "required": [
        "destination",
        "otp"
      ],
      "additionalProperties": false,
      "title": "VerifyOtpRequest",
      "type": "object"
    },
    "SendOtpRequest": {
      "properties": {
        "destination": {
          "title": "SendOtpRequest.destination",
          "type": "string"
        }
      },
      "required": [
        "destination"
      ],
      "additionalProperties": false,
      "title": "SendOtpRequest",
      "type": "object"
    },
    "ChangePasswordRequest": {
      "properties": {
        "oldPassword": {
          "title": "ChangePasswordRequest.oldPassword",
          "type": "string"
        },
        "newPassword": {
          "title": "ChangePasswordRequest.newPassword",
          "type": "string"
        }
      },
      "required": [
        "oldPassword",
        "newPassword"
      ],
      "additionalProperties": false,
      "title": "ChangePasswordRequest",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};