flowchart TD

A[Alert Service]
    --> B[Publish AlertCreated.v1]

B --> C[EventBridge]

C --> D[Realtime Queue SQS]

D --> E[Aggregation Lambda]

E --> F[Group by Scope]

F --> G{Grouping Key}

G --> H[ORG#ORG1#TEAM_ALERTS]

G --> I[USER#DOC123#MY_ALERTS]

G --> J[PATIENT#PAT001]

H --> K[Build Single Realtime Event]

I --> K

J --> K

K --> L[Socket Publisher]

L --> M[Web App]

L --> N[Mobile App]

M --> O[invalidateQueries]

N --> O