sequenceDiagram

participant User
participant AlertService
participant DB
participant EB as EventBridge
participant Consumer
participant RT as Realtime Middleware
participant Buffer
participant WS as WebSocket
participant FE as Frontend

User->>AlertService: Update Alert

AlertService->>DB: Save Alert Changes

DB-->>AlertService: Success

AlertService->>EB: Publish AlertUpdated.v1

EB->>Consumer: Deliver Event

Consumer->>Consumer: Execute Business Logic

EB->>RT: AlertCreated #1
RT->>Buffer: Store

EB->>RT: AlertCreated #2
RT->>Buffer: Store

EB->>RT: AlertCreated #3
RT->>Buffer: Store

EB->>RT: AlertCreated #4
RT->>Buffer: Store

Note over Buffer: wait 1-2 sec window

Buffer->>WS: TEAM_ALERTS_UPDATED

WS->>FE: TEAM_ALERTS_UPDATED

FE->>FE: invalidateQueries()

FE->>AlertService: GET /team-alerts
