flowchart LR

PlatformAdmin --> TemplateService
OrgAdmin --> TemplateService

TemplateService --> MetadataRegistry
TemplateService --> PackageService

PackageService --> CarePlanRuntime

CarePlanRuntime --> TaskRuntime
CarePlanRuntime --> AlertRuntime
CarePlanRuntime --> SymptomRuntime