// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Metadata Registry Service API",
    "version": "1.0.0",
    "description": "Metadata types, values, applicability (module, category, condition, country), JSON-schema validation on valueAttributes, DynamoDB single-table, EventBridge events"
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "Health check",
        "description": "No authentication. Standard ApiResponse envelope; data has status and service.",
        "tags": [
          "Health"
        ],
        "operationId": "health.get./health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/HealthPayload"
            }
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/metadata-types": {
      "get": {
        "summary": "List metadata types",
        "description": "Returns every metadata type. Arrays are wrapped as data.items in the success envelope.",
        "tags": [
          "MetadataTypes"
        ],
        "operationId": "listMetadataTypes.get.metadata-types",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "data.items is MetadataType[]",
            "schema": {
              "$ref": "#/definitions/MetadataTypeListPayload"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      },
      "post": {
        "summary": "Create metadata type",
        "description": "Creates type row; emits METADATA_TYPE_CREATED. metadataTypeCode is immutable. createdBy defaults from authorizer.",
        "tags": [
          "MetadataTypes"
        ],
        "operationId": "createMetadataType.post.metadata-types",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateMetadataTypeRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Created MetadataType in data",
            "schema": {
              "$ref": "#/definitions/MetadataType"
            }
          },
          "400": {
            "description": "Validation error (Zod / JSON)"
          },
          "401": {
            "description": "Unauthorized"
          },
          "409": {
            "description": "Type code already exists"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/metadata-types/{metadataTypeCode}": {
      "get": {
        "summary": "Get metadata type by code",
        "description": "Path param metadataTypeCode is the immutable key (e.g. SPECIALTY).",
        "tags": [
          "MetadataTypes"
        ],
        "operationId": "getMetadataType.get.metadata-types/{metadataTypeCode}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "metadataTypeCode",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "MetadataType in data",
            "schema": {
              "$ref": "#/definitions/MetadataType"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Type not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      },
      "put": {
        "summary": "Update metadata type",
        "description": "Partial update. Schema change bumps version; emits METADATA_SCHEMA_UPDATED or METADATA_TYPE_UPDATED.",
        "tags": [
          "MetadataTypes"
        ],
        "operationId": "updateMetadataType.put.metadata-types/{metadataTypeCode}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateMetadataTypeRequest"
            }
          },
          {
            "name": "metadataTypeCode",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated MetadataType",
            "schema": {
              "$ref": "#/definitions/MetadataType"
            }
          },
          "400": {
            "description": "Validation error"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Type not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/metadata-types/{metadataTypeCode}/inactivate": {
      "put": {
        "summary": "Inactivate metadata type",
        "description": "Sets status INACTIVE; version increments; emits METADATA_TYPE_UPDATED.",
        "tags": [
          "MetadataTypes"
        ],
        "operationId": "inactivateMetadataType.put.metadata-types/{metadataTypeCode}/inactivate",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "metadataTypeCode",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Type with status INACTIVE",
            "schema": {
              "$ref": "#/definitions/MetadataType"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Type not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/metadata-types/{metadataTypeCode}/values": {
      "post": {
        "summary": "Create metadata value",
        "description": "Parent type must be ACTIVE. Writes VALUE# and APPL# rows; emits METADATA_VALUE_CREATED and METADATA_RELATION_UPDATED.",
        "tags": [
          "MetadataValues"
        ],
        "operationId": "createMetadataValue.post.metadata-types/{metadataTypeCode}/values",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateMetadataValueRequest"
            }
          },
          {
            "name": "metadataTypeCode",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Created MetadataValue",
            "schema": {
              "$ref": "#/definitions/MetadataValue"
            }
          },
          "400": {
            "description": "Validation (Zod / attributeSchema)"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Parent type missing or inactive"
          },
          "409": {
            "description": "Value code already exists for type"
          },
          "500": {
            "description": "Server error"
          }
        }
      },
      "get": {
        "summary": "List metadata values by applicability context",
        "description": "Query params default to GLOBAL. Returns ACTIVE values matching module/category/condition/country rules.",
        "tags": [
          "MetadataValues"
        ],
        "operationId": "listMetadataValuesByContext.get.metadata-types/{metadataTypeCode}/values",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "metadataTypeCode",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "module",
            "type": "string",
            "description": "Default GLOBAL",
            "required": false
          },
          {
            "in": "query",
            "name": "category",
            "type": "string",
            "description": "Default GLOBAL",
            "required": false
          },
          {
            "in": "query",
            "name": "condition",
            "type": "string",
            "description": "Default GLOBAL",
            "required": false
          },
          {
            "in": "query",
            "name": "country",
            "type": "string",
            "description": "Default GLOBAL",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "data.items — filtered MetadataValue[]",
            "schema": {
              "$ref": "#/definitions/MetadataValueListPayload"
            }
          },
          "400": {
            "description": "Invalid query"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/metadata-types/{metadataTypeCode}/values/{metadataValueCode}": {
      "get": {
        "summary": "Get metadata value",
        "description": "Path codes are immutable.",
        "tags": [
          "MetadataValues"
        ],
        "operationId": "getMetadataValue.get.metadata-types/{metadataTypeCode}/values/{metadataValueCode}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "metadataTypeCode",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "metadataValueCode",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "MetadataValue in data",
            "schema": {
              "$ref": "#/definitions/MetadataValue"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      },
      "put": {
        "summary": "Update metadata value",
        "description": "Codes immutable. Applicability or attributes may bump version; emits METADATA_VALUE_UPDATED / METADATA_RELATION_UPDATED.",
        "tags": [
          "MetadataValues"
        ],
        "operationId": "updateMetadataValue.put.metadata-types/{metadataTypeCode}/values/{metadataValueCode}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateMetadataValueRequest"
            }
          },
          {
            "name": "metadataTypeCode",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "metadataValueCode",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated MetadataValue",
            "schema": {
              "$ref": "#/definitions/MetadataValue"
            }
          },
          "400": {
            "description": "Validation error"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/metadata-types/{metadataTypeCode}/values/{metadataValueCode}/inactivate": {
      "put": {
        "summary": "Inactivate metadata value",
        "description": "Emits METADATA_VALUE_INACTIVATED.",
        "tags": [
          "MetadataValues"
        ],
        "operationId": "inactivateMetadataValue.put.metadata-types/{metadataTypeCode}/values/{metadataValueCode}/inactivate",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "metadataTypeCode",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "metadataValueCode",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Value with status INACTIVE",
            "schema": {
              "$ref": "#/definitions/MetadataValue"
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/metadata-types/validate-value": {
      "post": {
        "summary": "Validate metadata value for context",
        "description": "Checks type/value ACTIVE, attributeSchema, and APPL# row for prioritized context.",
        "tags": [
          "Validation"
        ],
        "operationId": "validateMetadataValue.post.metadata-types/validate-value",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ValidateMetadataValueRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "{ valid, reason? } in data",
            "schema": {
              "$ref": "#/definitions/ValidateMetadataValuePayload"
            }
          },
          "400": {
            "description": "Invalid body"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },
  "definitions": {
    "HealthPayload": {
      "properties": {
        "status": {
          "title": "HealthPayload.status",
          "description": "Always `ok` when the Lambda succeeds",
          "type": "string"
        },
        "service": {
          "title": "HealthPayload.service",
          "type": "string"
        }
      },
      "required": [
        "status",
        "service"
      ],
      "additionalProperties": false,
      "title": "HealthPayload",
      "description": "Types for serverless-auto-swagger (bodyType / responseData).\nMirrors libs/metadata validators and domain types.",
      "type": "object"
    },
    "ValueDataType": {
      "enum": [
        "Enum",
        "Numeric",
        "Boolean",
        "Text"
      ],
      "title": "ValueDataType",
      "type": "string"
    },
    "RegistryStatus": {
      "enum": [
        "ACTIVE",
        "INACTIVE"
      ],
      "title": "RegistryStatus",
      "type": "string"
    },
    "CreateMetadataTypeRequest": {
      "properties": {
        "metadataTypeCode": {
          "title": "CreateMetadataTypeRequest.metadataTypeCode",
          "description": "Immutable logical key; PK METADATA_TYPE#{code}",
          "type": "string"
        },
        "displayName": {
          "title": "CreateMetadataTypeRequest.displayName",
          "type": "string"
        },
        "description": {
          "title": "CreateMetadataTypeRequest.description",
          "type": "string"
        },
        "valueDataType": {
          "$ref": "#/definitions/ValueDataType",
          "title": "CreateMetadataTypeRequest.valueDataType"
        },
        "multiSelectAllowed": {
          "title": "CreateMetadataTypeRequest.multiSelectAllowed",
          "type": "boolean"
        },
        "applicableModules": {
          "items": {
            "title": "CreateMetadataTypeRequest.applicableModules.[]",
            "type": "string"
          },
          "title": "CreateMetadataTypeRequest.applicableModules",
          "type": "array"
        },
        "attributeSchema": {
          "title": "CreateMetadataTypeRequest.attributeSchema",
          "description": "JSON Schema for valueAttributes on values of this type"
        },
        "createdBy": {
          "title": "CreateMetadataTypeRequest.createdBy",
          "description": "Optional; defaults from authorizer",
          "type": "string"
        }
      },
      "required": [
        "metadataTypeCode",
        "displayName",
        "valueDataType",
        "multiSelectAllowed",
        "applicableModules"
      ],
      "additionalProperties": false,
      "title": "CreateMetadataTypeRequest",
      "description": "POST /metadata-types",
      "type": "object"
    },
    "UpdateMetadataTypeRequest": {
      "properties": {
        "displayName": {
          "title": "UpdateMetadataTypeRequest.displayName",
          "type": "string"
        },
        "description": {
          "title": "UpdateMetadataTypeRequest.description",
          "type": "string"
        },
        "valueDataType": {
          "$ref": "#/definitions/ValueDataType",
          "title": "UpdateMetadataTypeRequest.valueDataType"
        },
        "multiSelectAllowed": {
          "title": "UpdateMetadataTypeRequest.multiSelectAllowed",
          "type": "boolean"
        },
        "applicableModules": {
          "items": {
            "title": "UpdateMetadataTypeRequest.applicableModules.[]",
            "type": "string"
          },
          "title": "UpdateMetadataTypeRequest.applicableModules",
          "type": "array"
        },
        "attributeSchema": {
          "title": "UpdateMetadataTypeRequest.attributeSchema"
        },
        "status": {
          "$ref": "#/definitions/RegistryStatus",
          "title": "UpdateMetadataTypeRequest.status"
        },
        "updatedBy": {
          "title": "UpdateMetadataTypeRequest.updatedBy",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "UpdateMetadataTypeRequest",
      "description": "PUT /metadata-types/{metadataTypeCode}",
      "type": "object"
    },
    "CreateMetadataValueRequest": {
      "properties": {
        "metadataValueCode": {
          "title": "CreateMetadataValueRequest.metadataValueCode",
          "type": "string"
        },
        "label": {
          "title": "CreateMetadataValueRequest.label",
          "type": "string"
        },
        "description": {
          "title": "CreateMetadataValueRequest.description",
          "type": "string"
        },
        "isGlobal": {
          "title": "CreateMetadataValueRequest.isGlobal",
          "description": "When true, writes a single GLOBAL applicability tuple",
          "type": "boolean"
        },
        "applicableModules": {
          "items": {
            "title": "CreateMetadataValueRequest.applicableModules.[]",
            "type": "string"
          },
          "title": "CreateMetadataValueRequest.applicableModules",
          "type": "array"
        },
        "applicableCategories": {
          "items": {
            "title": "CreateMetadataValueRequest.applicableCategories.[]",
            "type": "string"
          },
          "title": "CreateMetadataValueRequest.applicableCategories",
          "type": "array"
        },
        "applicableConditions": {
          "items": {
            "title": "CreateMetadataValueRequest.applicableConditions.[]",
            "type": "string"
          },
          "title": "CreateMetadataValueRequest.applicableConditions",
          "type": "array"
        },
        "applicableCountries": {
          "items": {
            "title": "CreateMetadataValueRequest.applicableCountries.[]",
            "type": "string"
          },
          "title": "CreateMetadataValueRequest.applicableCountries",
          "type": "array"
        },
        "valueAttributes": {
          "title": "CreateMetadataValueRequest.valueAttributes"
        },
        "createdBy": {
          "title": "CreateMetadataValueRequest.createdBy",
          "type": "string"
        }
      },
      "required": [
        "metadataValueCode",
        "label",
        "isGlobal",
        "applicableModules",
        "applicableCategories",
        "applicableConditions",
        "applicableCountries",
        "valueAttributes"
      ],
      "additionalProperties": false,
      "title": "CreateMetadataValueRequest",
      "description": "POST /metadata-types/{metadataTypeCode}/values",
      "type": "object"
    },
    "UpdateMetadataValueRequest": {
      "properties": {
        "label": {
          "title": "UpdateMetadataValueRequest.label",
          "type": "string"
        },
        "description": {
          "title": "UpdateMetadataValueRequest.description",
          "type": "string"
        },
        "isGlobal": {
          "title": "UpdateMetadataValueRequest.isGlobal",
          "type": "boolean"
        },
        "applicableModules": {
          "items": {
            "title": "UpdateMetadataValueRequest.applicableModules.[]",
            "type": "string"
          },
          "title": "UpdateMetadataValueRequest.applicableModules",
          "type": "array"
        },
        "applicableCategories": {
          "items": {
            "title": "UpdateMetadataValueRequest.applicableCategories.[]",
            "type": "string"
          },
          "title": "UpdateMetadataValueRequest.applicableCategories",
          "type": "array"
        },
        "applicableConditions": {
          "items": {
            "title": "UpdateMetadataValueRequest.applicableConditions.[]",
            "type": "string"
          },
          "title": "UpdateMetadataValueRequest.applicableConditions",
          "type": "array"
        },
        "applicableCountries": {
          "items": {
            "title": "UpdateMetadataValueRequest.applicableCountries.[]",
            "type": "string"
          },
          "title": "UpdateMetadataValueRequest.applicableCountries",
          "type": "array"
        },
        "valueAttributes": {
          "title": "UpdateMetadataValueRequest.valueAttributes"
        },
        "status": {
          "$ref": "#/definitions/RegistryStatus",
          "title": "UpdateMetadataValueRequest.status"
        },
        "updatedBy": {
          "title": "UpdateMetadataValueRequest.updatedBy",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "UpdateMetadataValueRequest",
      "description": "PUT /metadata-types/{metadataTypeCode}/values/{metadataValueCode}",
      "type": "object"
    },
    "ValidateMetadataValueRequest": {
      "properties": {
        "metadataTypeCode": {
          "title": "ValidateMetadataValueRequest.metadataTypeCode",
          "type": "string"
        },
        "metadataValueCode": {
          "title": "ValidateMetadataValueRequest.metadataValueCode",
          "type": "string"
        },
        "context": {
          "$ref": "#/definitions/ApplicabilityContextBody",
          "title": "ValidateMetadataValueRequest.context"
        }
      },
      "required": [
        "metadataTypeCode",
        "metadataValueCode",
        "context"
      ],
      "additionalProperties": false,
      "title": "ValidateMetadataValueRequest",
      "description": "POST /metadata-types/validate-value",
      "type": "object"
    },
    "ApplicabilityContextBody": {
      "properties": {
        "module": {
          "title": "ApplicabilityContextBody.module",
          "type": "string"
        },
        "category": {
          "title": "ApplicabilityContextBody.category",
          "type": "string"
        },
        "condition": {
          "title": "ApplicabilityContextBody.condition",
          "type": "string"
        },
        "country": {
          "title": "ApplicabilityContextBody.country",
          "type": "string"
        }
      },
      "required": [
        "module",
        "category",
        "condition",
        "country"
      ],
      "additionalProperties": false,
      "title": "ApplicabilityContextBody",
      "type": "object"
    },
    "MetadataType": {
      "properties": {
        "metadataTypeCode": {
          "title": "MetadataType.metadataTypeCode",
          "type": "string"
        },
        "displayName": {
          "title": "MetadataType.displayName",
          "type": "string"
        },
        "description": {
          "title": "MetadataType.description",
          "type": "string"
        },
        "valueDataType": {
          "$ref": "#/definitions/ValueDataType",
          "title": "MetadataType.valueDataType"
        },
        "multiSelectAllowed": {
          "title": "MetadataType.multiSelectAllowed",
          "type": "boolean"
        },
        "applicableModules": {
          "items": {
            "title": "MetadataType.applicableModules.[]",
            "type": "string"
          },
          "title": "MetadataType.applicableModules",
          "type": "array"
        },
        "attributeSchema": {
          "title": "MetadataType.attributeSchema"
        },
        "status": {
          "$ref": "#/definitions/RegistryStatus",
          "title": "MetadataType.status"
        },
        "version": {
          "title": "MetadataType.version",
          "type": "number"
        },
        "createdAt": {
          "title": "MetadataType.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "MetadataType.updatedAt",
          "type": "string"
        },
        "createdBy": {
          "title": "MetadataType.createdBy",
          "type": "string"
        },
        "updatedBy": {
          "title": "MetadataType.updatedBy",
          "type": "string"
        }
      },
      "required": [
        "metadataTypeCode",
        "displayName",
        "valueDataType",
        "multiSelectAllowed",
        "applicableModules",
        "status",
        "version",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "MetadataType",
      "description": "Stored metadata type entity",
      "type": "object"
    },
    "MetadataValue": {
      "properties": {
        "metadataTypeCode": {
          "title": "MetadataValue.metadataTypeCode",
          "type": "string"
        },
        "metadataValueCode": {
          "title": "MetadataValue.metadataValueCode",
          "type": "string"
        },
        "label": {
          "title": "MetadataValue.label",
          "type": "string"
        },
        "description": {
          "title": "MetadataValue.description",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/RegistryStatus",
          "title": "MetadataValue.status"
        },
        "isGlobal": {
          "title": "MetadataValue.isGlobal",
          "type": "boolean"
        },
        "applicableModules": {
          "items": {
            "title": "MetadataValue.applicableModules.[]",
            "type": "string"
          },
          "title": "MetadataValue.applicableModules",
          "type": "array"
        },
        "applicableCategories": {
          "items": {
            "title": "MetadataValue.applicableCategories.[]",
            "type": "string"
          },
          "title": "MetadataValue.applicableCategories",
          "type": "array"
        },
        "applicableConditions": {
          "items": {
            "title": "MetadataValue.applicableConditions.[]",
            "type": "string"
          },
          "title": "MetadataValue.applicableConditions",
          "type": "array"
        },
        "applicableCountries": {
          "items": {
            "title": "MetadataValue.applicableCountries.[]",
            "type": "string"
          },
          "title": "MetadataValue.applicableCountries",
          "type": "array"
        },
        "valueAttributes": {
          "title": "MetadataValue.valueAttributes"
        },
        "version": {
          "title": "MetadataValue.version",
          "type": "number"
        },
        "createdAt": {
          "title": "MetadataValue.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "MetadataValue.updatedAt",
          "type": "string"
        },
        "createdBy": {
          "title": "MetadataValue.createdBy",
          "type": "string"
        },
        "updatedBy": {
          "title": "MetadataValue.updatedBy",
          "type": "string"
        }
      },
      "required": [
        "metadataTypeCode",
        "metadataValueCode",
        "label",
        "status",
        "isGlobal",
        "applicableModules",
        "applicableCategories",
        "applicableConditions",
        "applicableCountries",
        "valueAttributes",
        "version",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "MetadataValue",
      "description": "Stored metadata value entity",
      "type": "object"
    },
    "MetadataTypeListPayload": {
      "properties": {
        "items": {
          "items": {
            "$ref": "#/definitions/MetadataType",
            "title": "MetadataTypeListPayload.items.[]"
          },
          "title": "MetadataTypeListPayload.items",
          "type": "array"
        }
      },
      "required": [
        "items"
      ],
      "additionalProperties": false,
      "title": "MetadataTypeListPayload",
      "description": "GET list endpoints — ApiResponse normalizes arrays to `{ items }` in `data`",
      "type": "object"
    },
    "MetadataValueListPayload": {
      "properties": {
        "items": {
          "items": {
            "$ref": "#/definitions/MetadataValue",
            "title": "MetadataValueListPayload.items.[]"
          },
          "title": "MetadataValueListPayload.items",
          "type": "array"
        }
      },
      "required": [
        "items"
      ],
      "additionalProperties": false,
      "title": "MetadataValueListPayload",
      "type": "object"
    },
    "ValidateMetadataValuePayload": {
      "properties": {
        "valid": {
          "title": "ValidateMetadataValuePayload.valid",
          "type": "boolean"
        },
        "reason": {
          "title": "ValidateMetadataValuePayload.reason",
          "description": "Present when valid is false, e.g. APPLICABILITY_MISMATCH",
          "type": "string"
        }
      },
      "required": [
        "valid"
      ],
      "additionalProperties": false,
      "title": "ValidateMetadataValuePayload",
      "description": "validateMetadataValue handler return",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};