Outputs:
  TemplateConfigBucketName:
    Description: S3 bucket for template UI configuration JSON (existing stage bucket)
    Value: ${self:custom.bundle.templateConfigBucketName}
    Export:
      Name: ${self:provider.stage}-${self:service}-TemplateConfigBucketName
  TemplateEventBusName:
    Description: Name of the Template Service Event Bus
    Value:
      Ref: TemplateEventBus
    Export:
      Name: ${self:provider.stage}-${self:service}-EventBusName
  TemplateEventBusArn:
    Description: ARN of the Template Service Event Bus
    Value:
      Fn::GetAtt:
        - TemplateEventBus
        - Arn
    Export:
      Name: ${self:provider.stage}-${self:service}-EventBusArn
