/**
 * Error codes returned in API response body.
 * Single source of truth for backward compatibility with API consumers.
 */
export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DELETE_FAILED: 'DELETE_FAILED',
  RECOMMENDATION_NOT_FOUND: 'RECOMMENDATION_NOT_FOUND',
  RECOMMENDATION_REMOVE_FAILED: 'RECOMMENDATION_REMOVE_FAILED',
  CANNOT_REMOVE_PAIRED_DEVICE: 'CANNOT_REMOVE_PAIRED_DEVICE',
  SEARCH_FAILED: 'SEARCH_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
