// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Beauty on Wheels - Booking Service API",
    "version": "1"
  },
  "paths": {
    "/bookings": {
      "get": {
        "summary": "List bookings",
        "description": "List all bookings, or filter by customerId or vendorId query param",
        "tags": [
          "Bookings"
        ],
        "operationId": "getbookings.get./bookings",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "customerId",
            "type": "string",
            "description": "Filter bookings by customer ID",
            "required": false
          },
          {
            "in": "query",
            "name": "vendorId",
            "type": "string",
            "description": "Filter bookings by vendor ID",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "Booking list"
          }
        }
      },
      "post": {
        "summary": "Create booking",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "postbookings.post./bookings",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Booking created"
          }
        }
      }
    },
    "/bookings/{bookingId}": {
      "get": {
        "summary": "Get booking",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "getbookingid.get./bookings/{bookingId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "bookingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Booking",
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          }
        }
      },
      "put": {
        "summary": "Update booking",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "putbookingid.put./bookings/{bookingId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Booking"
            }
          },
          {
            "name": "bookingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Updated"
          }
        }
      },
      "delete": {
        "summary": "Cancel booking",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "deletebookingid.delete./bookings/{bookingId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "bookingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Cancelled"
          }
        }
      }
    },
    "/bookings/{bookingId}/confirm": {
      "post": {
        "summary": "Confirm booking",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "postconfirm.post./bookings/{bookingId}/confirm",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "bookingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Confirmed"
          }
        }
      }
    },
    "/bookings/{bookingId}/check-in": {
      "post": {
        "summary": "Customer check-in",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "postcheckin.post./bookings/{bookingId}/check-in",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "bookingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Checked in"
          }
        }
      }
    },
    "/bookings/{bookingId}/start": {
      "post": {
        "summary": "Start service",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "poststart.post./bookings/{bookingId}/start",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "bookingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "In progress"
          }
        }
      }
    },
    "/bookings/{bookingId}/complete": {
      "post": {
        "summary": "Complete booking",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "postcomplete.post./bookings/{bookingId}/complete",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "bookingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Completed"
          }
        }
      }
    },
    "/bookings/{bookingId}/cancel": {
      "post": {
        "summary": "Cancel booking",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "postcancel.post./bookings/{bookingId}/cancel",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "bookingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Cancelled"
          }
        }
      }
    },
    "/customers/{customerId}/bookings": {
      "get": {
        "summary": "Customer booking history",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "getcustomerbookings.get./customers/{customerId}/bookings",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "customerId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "History"
          }
        }
      }
    },
    "/vendors/{vendorId}/bookings": {
      "get": {
        "summary": "Vendor bookings",
        "description": "",
        "tags": [
          "Bookings"
        ],
        "operationId": "getvendorbookings.get./vendors/{vendorId}/bookings",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor bookings"
          }
        }
      }
    }
  },
  "definitions": {
    "Booking": {
      "properties": {
        "id": {
          "title": "Booking.id",
          "type": "string"
        },
        "customerId": {
          "title": "Booking.customerId",
          "type": "string"
        },
        "vendorId": {
          "title": "Booking.vendorId",
          "type": "string"
        },
        "vehicleId": {
          "title": "Booking.vehicleId",
          "type": "string"
        },
        "serviceIds": {
          "items": {
            "title": "Booking.serviceIds.[]",
            "type": "string"
          },
          "title": "Booking.serviceIds",
          "type": "array"
        },
        "bookingDate": {
          "title": "Booking.bookingDate",
          "type": "string"
        },
        "slotId": {
          "title": "Booking.slotId",
          "type": "string"
        },
        "totalAmount": {
          "title": "Booking.totalAmount",
          "type": "number"
        },
        "paymentStatus": {
          "enum": [
            "PENDING",
            "PAID",
            "REFUNDED"
          ],
          "title": "Booking.paymentStatus",
          "type": "string"
        },
        "bookingStatus": {
          "enum": [
            "CREATED",
            "PENDING",
            "CONFIRMED",
            "CHECKED_IN",
            "IN_PROGRESS",
            "COMPLETED",
            "CANCELLED"
          ],
          "title": "Booking.bookingStatus",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "Booking",
      "description": "This file was automatically generated from the OpenAPI specification.\nDO NOT EDIT DIRECTLY.",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};