// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Template Service API",
    "version": "1.0.0",
    "description": "Template library, metadata registry, execution, and care-plan draft APIs"
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "health",
        "description": "",
        "operationId": "health.get./health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/metadata/applicable": {
      "get": {
        "summary": "listApplicableMetadata",
        "description": "",
        "operationId": "listApplicableMetadata.get.metadata/applicable",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/metadata/{type}/{name}/versions": {
      "get": {
        "summary": "listMetadataVersions",
        "description": "",
        "operationId": "listMetadataVersions.get.metadata/{type}/{name}/versions",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/metadata/{type}/{name}/{version}": {
      "put": {
        "summary": "upsertMetadataDefinition",
        "description": "",
        "operationId": "upsertMetadataDefinition.put.metadata/{type}/{name}/{version}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "deleteMetadataDefinition",
        "description": "",
        "operationId": "deleteMetadataDefinition.delete.metadata/{type}/{name}/{version}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "version",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/metadata/{type}": {
      "get": {
        "summary": "listMetadataByType",
        "description": "",
        "operationId": "listMetadataByType.get.metadata/{type}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "createMetadataDefinition",
        "description": "",
        "operationId": "createMetadataDefinition.post.metadata/{type}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/metadata/{type}/{name}": {
      "get": {
        "summary": "getMetadataDefinition",
        "description": "",
        "operationId": "getMetadataDefinition.get.metadata/{type}/{name}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "type",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "name",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/templates": {
      "post": {
        "summary": "createTemplate",
        "description": "",
        "operationId": "createTemplate.post.templates",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/templates/{id}": {
      "get": {
        "summary": "getTemplate",
        "description": "",
        "operationId": "getTemplate.get.templates/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "updateTemplate",
        "description": "",
        "operationId": "updateTemplate.put.templates/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/templates/{id}/publish": {
      "post": {
        "summary": "publishTemplate",
        "description": "",
        "operationId": "publishTemplate.post.templates/{id}/publish",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/templates/{id}/execute": {
      "post": {
        "summary": "executeTemplate",
        "description": "",
        "operationId": "executeTemplate.post.templates/{id}/execute",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/care-plans/draft": {
      "post": {
        "summary": "createCarePlanDraft",
        "description": "",
        "operationId": "createCarePlanDraft.post.care-plans/draft",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};