// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Beauty on Wheels - Vendor Service API",
    "version": "1"
  },
  "paths": {
    "/vendors": {
      "post": {
        "summary": "Create vendor",
        "description": "Creates a new vendor profile.\n\nThe authenticated identity should be linked to the vendor through ownerUserId.\nVendor creation does not automatically activate the vendor.\n",
        "tags": [
          "Vendors"
        ],
        "operationId": "createvendor.post./vendors",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateVendorRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Vendor created successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      },
      "get": {
        "summary": "List vendors",
        "description": "Lists vendors using optional filters.\nIntended primarily for admin and operational use.\n",
        "tags": [
          "Vendors"
        ],
        "operationId": "listvendors.get./vendors",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Vendors retrieved successfully",
            "schema": {
              "$ref": "#/definitions/VendorListResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}": {
      "get": {
        "summary": "Get vendor",
        "description": "",
        "tags": [
          "Vendors"
        ],
        "operationId": "getvendor.get./vendors/{vendorId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor retrieved successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      },
      "patch": {
        "summary": "Update vendor",
        "description": "",
        "tags": [
          "Vendors"
        ],
        "operationId": "updatevendor.patch./vendors/{vendorId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateVendorRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor updated successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/status": {
      "patch": {
        "summary": "Update vendor lifecycle status",
        "description": "Updates the administrative lifecycle status of a vendor.\n\nTypical lifecycle:\n  PENDING_VERIFICATION\n  -> ACTIVE\n  -> SUSPENDED\n  -> ACTIVE\n  -> INACTIVE\n",
        "tags": [
          "Vendors"
        ],
        "operationId": "updatevendorstatus.patch./vendors/{vendorId}/status",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateVendorStatusRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor status updated successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "403": {
            "description": "403 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/operational-status": {
      "patch": {
        "summary": "Update vendor operational status",
        "description": "Controls whether a vendor is currently accepting work.\n\nThis is different from the administrative vendor lifecycle status.\n",
        "tags": [
          "Vendors"
        ],
        "operationId": "updatevendoroperationalstatus.patch./vendors/{vendorId}/operational-status",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateOperationalStatusRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Operational status updated successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/service-areas": {
      "get": {
        "summary": "List vendor service areas",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "listvendorserviceareas.get./vendors/{vendorId}/service-areas",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Service areas retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      },
      "post": {
        "summary": "Add vendor service area",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "addvendorservicearea.post./vendors/{vendorId}/service-areas",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateServiceAreaRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Service area created successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/service-areas/{serviceAreaId}": {
      "get": {
        "summary": "Get vendor service area",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "getvendorservicearea.get./vendors/{vendorId}/service-areas/{serviceAreaId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "serviceAreaId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Service area retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "patch": {
        "summary": "Update vendor service area",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "updatevendorservicearea.patch./vendors/{vendorId}/service-areas/{serviceAreaId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateServiceAreaRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "serviceAreaId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Service area updated successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "delete": {
        "summary": "Remove vendor service area",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "deletevendorservicearea.delete./vendors/{vendorId}/service-areas/{serviceAreaId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "serviceAreaId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Service area removed successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/operating-hours": {
      "get": {
        "summary": "Get vendor operating hours",
        "description": "",
        "tags": [
          "Operating Hours"
        ],
        "operationId": "getvendoroperatinghours.get./vendors/{vendorId}/operating-hours",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Operating hours retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Replace vendor operating hours",
        "description": "Replaces the vendor's standard weekly operating schedule.\n\nAvailability Service may use this schedule as an input when\ngenerating or validating bookable slots.\n",
        "tags": [
          "Operating Hours"
        ],
        "operationId": "updatevendoroperatinghours.put./vendors/{vendorId}/operating-hours",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Operating hours updated successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/staff": {
      "get": {
        "summary": "List vendor staff",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "listvendorstaff.get./vendors/{vendorId}/staff",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Staff retrieved successfully",
            "schema": {
              "$ref": "#/definitions/StaffListResponse"
            }
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "post": {
        "summary": "Add vendor staff member",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "createvendorstaff.post./vendors/{vendorId}/staff",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateStaffRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Staff member created successfully",
            "schema": {
              "$ref": "#/definitions/StaffResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/staff/{staffId}": {
      "get": {
        "summary": "Get vendor staff member",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "getvendorstaff.get./vendors/{vendorId}/staff/{staffId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "staffId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Staff member retrieved successfully",
            "schema": {
              "$ref": "#/definitions/StaffResponse"
            }
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "patch": {
        "summary": "Update vendor staff member",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "updatevendorstaff.patch./vendors/{vendorId}/staff/{staffId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateStaffRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "staffId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Staff member updated successfully",
            "schema": {
              "$ref": "#/definitions/StaffResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "delete": {
        "summary": "Deactivate vendor staff member",
        "description": "Deactivates the staff member.\nHistorical booking/job references should remain intact.\n",
        "tags": [
          "Staff"
        ],
        "operationId": "deactivatevendorstaff.delete./vendors/{vendorId}/staff/{staffId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "staffId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Staff member deactivated successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/capabilities": {
      "get": {
        "summary": "Get vendor capabilities",
        "description": "",
        "tags": [
          "Capabilities"
        ],
        "operationId": "getvendorcapabilities.get./vendors/{vendorId}/capabilities",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor capabilities retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Replace vendor capabilities",
        "description": "Updates the services, packages and vehicle types that the vendor\nis capable of supporting.\n\nserviceIds and packageIds are references to entities owned by the\nService Catalog Service.\n\nThis endpoint does not define pricing or availability.\n",
        "tags": [
          "Capabilities"
        ],
        "operationId": "updatevendorcapabilities.put./vendors/{vendorId}/capabilities",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateVendorCapabilitiesRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor capabilities updated successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          }
        }
      }
    }
  },
  "definitions": {
    "VendorStatus": {
      "enum": [
        "PENDING_VERIFICATION",
        "ACTIVE",
        "SUSPENDED",
        "INACTIVE",
        "REJECTED"
      ],
      "title": "VendorStatus",
      "description": "This file was automatically generated from the OpenAPI specification.\nDO NOT EDIT DIRECTLY.",
      "type": "string"
    },
    "OperationalStatus": {
      "enum": [
        "ONLINE",
        "OFFLINE",
        "BUSY",
        "TEMPORARILY_UNAVAILABLE"
      ],
      "title": "OperationalStatus",
      "type": "string"
    },
    "VendorType": {
      "enum": [
        "INDIVIDUAL",
        "BUSINESS"
      ],
      "title": "VendorType",
      "type": "string"
    },
    "VehicleType": {
      "enum": [
        "HATCHBACK",
        "SEDAN",
        "SUV",
        "MUV",
        "LUXURY",
        "OTHER"
      ],
      "title": "VehicleType",
      "type": "string"
    },
    "StaffStatus": {
      "enum": [
        "ACTIVE",
        "INACTIVE"
      ],
      "title": "StaffStatus",
      "type": "string"
    },
    "DayOfWeek": {
      "enum": [
        "MONDAY",
        "TUESDAY",
        "WEDNESDAY",
        "THURSDAY",
        "FRIDAY",
        "SATURDAY",
        "SUNDAY"
      ],
      "title": "DayOfWeek",
      "type": "string"
    },
    "Address": {
      "properties": {
        "addressLine1": {
          "title": "Address.addressLine1",
          "type": "string"
        },
        "addressLine2": {
          "title": "Address.addressLine2",
          "type": "string"
        },
        "landmark": {
          "title": "Address.landmark",
          "type": "string"
        },
        "city": {
          "title": "Address.city",
          "type": "string"
        },
        "state": {
          "title": "Address.state",
          "type": "string"
        },
        "country": {
          "title": "Address.country",
          "type": "string"
        },
        "postalCode": {
          "title": "Address.postalCode",
          "type": "string"
        }
      },
      "required": [
        "addressLine1",
        "city",
        "state",
        "country",
        "postalCode"
      ],
      "additionalProperties": false,
      "title": "Address",
      "type": "object"
    },
    "GeoLocation": {
      "properties": {
        "latitude": {
          "title": "GeoLocation.latitude",
          "type": "number"
        },
        "longitude": {
          "title": "GeoLocation.longitude",
          "type": "number"
        }
      },
      "required": [
        "latitude",
        "longitude"
      ],
      "additionalProperties": false,
      "title": "GeoLocation",
      "type": "object"
    },
    "CreateVendorRequest": {
      "properties": {
        "ownerUserId": {
          "title": "CreateVendorRequest.ownerUserId",
          "type": "string"
        },
        "vendorType": {
          "$ref": "#/definitions/VendorType",
          "title": "CreateVendorRequest.vendorType"
        },
        "businessName": {
          "title": "CreateVendorRequest.businessName",
          "type": "string"
        },
        "contactName": {
          "title": "CreateVendorRequest.contactName",
          "type": "string"
        },
        "phoneNumber": {
          "title": "CreateVendorRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "CreateVendorRequest.email",
          "type": "string"
        },
        "description": {
          "title": "CreateVendorRequest.description",
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address",
          "title": "CreateVendorRequest.address"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "CreateVendorRequest.geoLocation"
        }
      },
      "required": [
        "ownerUserId",
        "vendorType",
        "businessName",
        "contactName",
        "phoneNumber",
        "address"
      ],
      "additionalProperties": false,
      "title": "CreateVendorRequest",
      "type": "object"
    },
    "UpdateVendorRequest": {
      "properties": {
        "businessName": {
          "title": "UpdateVendorRequest.businessName",
          "type": "string"
        },
        "contactName": {
          "title": "UpdateVendorRequest.contactName",
          "type": "string"
        },
        "phoneNumber": {
          "title": "UpdateVendorRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "UpdateVendorRequest.email",
          "type": "string"
        },
        "description": {
          "title": "UpdateVendorRequest.description",
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address",
          "title": "UpdateVendorRequest.address"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "UpdateVendorRequest.geoLocation"
        },
        "profileImageUrl": {
          "title": "UpdateVendorRequest.profileImageUrl",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "UpdateVendorRequest",
      "type": "object"
    },
    "UpdateVendorStatusRequest": {
      "properties": {
        "status": {
          "$ref": "#/definitions/VendorStatus",
          "title": "UpdateVendorStatusRequest.status"
        },
        "reason": {
          "title": "UpdateVendorStatusRequest.reason",
          "type": "string"
        }
      },
      "required": [
        "status"
      ],
      "additionalProperties": false,
      "title": "UpdateVendorStatusRequest",
      "type": "object"
    },
    "UpdateOperationalStatusRequest": {
      "properties": {
        "operationalStatus": {
          "$ref": "#/definitions/OperationalStatus",
          "title": "UpdateOperationalStatusRequest.operationalStatus"
        }
      },
      "required": [
        "operationalStatus"
      ],
      "additionalProperties": false,
      "title": "UpdateOperationalStatusRequest",
      "type": "object"
    },
    "Vendor": {
      "properties": {
        "vendorId": {
          "title": "Vendor.vendorId",
          "type": "string"
        },
        "ownerUserId": {
          "title": "Vendor.ownerUserId",
          "type": "string"
        },
        "vendorType": {
          "$ref": "#/definitions/VendorType",
          "title": "Vendor.vendorType"
        },
        "businessName": {
          "title": "Vendor.businessName",
          "type": "string"
        },
        "contactName": {
          "title": "Vendor.contactName",
          "type": "string"
        },
        "phoneNumber": {
          "title": "Vendor.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "Vendor.email",
          "type": "string"
        },
        "description": {
          "title": "Vendor.description",
          "type": "string"
        },
        "profileImageUrl": {
          "title": "Vendor.profileImageUrl",
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address",
          "title": "Vendor.address"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "Vendor.geoLocation"
        },
        "status": {
          "$ref": "#/definitions/VendorStatus",
          "title": "Vendor.status"
        },
        "operationalStatus": {
          "$ref": "#/definitions/OperationalStatus",
          "title": "Vendor.operationalStatus"
        },
        "createdAt": {
          "title": "Vendor.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "Vendor.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "vendorId",
        "ownerUserId",
        "vendorType",
        "businessName",
        "status",
        "operationalStatus",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "Vendor",
      "type": "object"
    },
    "VendorResponse": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Vendor",
          "title": "VendorResponse.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "VendorResponse",
      "type": "object"
    },
    "VendorListResponse": {
      "properties": {
        "data": {
          "items": {
            "$ref": "#/definitions/Vendor",
            "title": "VendorListResponse.data.[]"
          },
          "title": "VendorListResponse.data",
          "type": "array"
        },
        "pagination": {
          "$ref": "#/definitions/Pagination",
          "title": "VendorListResponse.pagination"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "VendorListResponse",
      "type": "object"
    },
    "CreateServiceAreaRequest": {
      "properties": {
        "name": {
          "title": "CreateServiceAreaRequest.name",
          "type": "string"
        },
        "city": {
          "title": "CreateServiceAreaRequest.city",
          "type": "string"
        },
        "state": {
          "title": "CreateServiceAreaRequest.state",
          "type": "string"
        },
        "postalCodes": {
          "items": {
            "title": "CreateServiceAreaRequest.postalCodes.[]",
            "type": "string"
          },
          "title": "CreateServiceAreaRequest.postalCodes",
          "type": "array"
        },
        "center": {
          "$ref": "#/definitions/GeoLocation",
          "title": "CreateServiceAreaRequest.center"
        },
        "radiusKm": {
          "title": "CreateServiceAreaRequest.radiusKm",
          "type": "number"
        },
        "active": {
          "title": "CreateServiceAreaRequest.active",
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "city"
      ],
      "additionalProperties": false,
      "title": "CreateServiceAreaRequest",
      "type": "object"
    },
    "UpdateServiceAreaRequest": {
      "properties": {
        "name": {
          "title": "UpdateServiceAreaRequest.name",
          "type": "string"
        },
        "city": {
          "title": "UpdateServiceAreaRequest.city",
          "type": "string"
        },
        "state": {
          "title": "UpdateServiceAreaRequest.state",
          "type": "string"
        },
        "postalCodes": {
          "items": {
            "title": "UpdateServiceAreaRequest.postalCodes.[]",
            "type": "string"
          },
          "title": "UpdateServiceAreaRequest.postalCodes",
          "type": "array"
        },
        "center": {
          "$ref": "#/definitions/GeoLocation",
          "title": "UpdateServiceAreaRequest.center"
        },
        "radiusKm": {
          "title": "UpdateServiceAreaRequest.radiusKm",
          "type": "number"
        },
        "active": {
          "title": "UpdateServiceAreaRequest.active",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "title": "UpdateServiceAreaRequest",
      "type": "object"
    },
    "ServiceArea": {
      "allOf": [
        {
          "$ref": "#/definitions/CreateServiceAreaRequest"
        },
        {
          "properties": {
            "serviceAreaId": {
              "title": "serviceAreaId",
              "type": "string"
            },
            "vendorId": {
              "title": "vendorId",
              "type": "string"
            },
            "createdAt": {
              "title": "createdAt",
              "type": "string"
            },
            "updatedAt": {
              "title": "updatedAt",
              "type": "string"
            }
          },
          "required": [
            "serviceAreaId",
            "vendorId",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false,
          "type": "object"
        }
      ],
      "title": "ServiceArea"
    },
    "OperatingHoursRequest": {
      "properties": {
        "dayOfWeek": {
          "$ref": "#/definitions/DayOfWeek",
          "title": "OperatingHoursRequest.dayOfWeek"
        },
        "closed": {
          "title": "OperatingHoursRequest.closed",
          "type": "boolean"
        },
        "openTime": {
          "title": "OperatingHoursRequest.openTime",
          "type": "string"
        },
        "closeTime": {
          "title": "OperatingHoursRequest.closeTime",
          "type": "string"
        }
      },
      "required": [
        "dayOfWeek",
        "closed"
      ],
      "additionalProperties": false,
      "title": "OperatingHoursRequest",
      "type": "object"
    },
    "OperatingHours": {
      "allOf": [
        {
          "$ref": "#/definitions/OperatingHoursRequest"
        },
        {
          "properties": {
            "vendorId": {
              "title": "vendorId",
              "type": "string"
            }
          },
          "additionalProperties": false,
          "type": "object"
        }
      ],
      "title": "OperatingHours"
    },
    "CreateStaffRequest": {
      "properties": {
        "userId": {
          "title": "CreateStaffRequest.userId",
          "type": "string"
        },
        "name": {
          "title": "CreateStaffRequest.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "CreateStaffRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "CreateStaffRequest.email",
          "type": "string"
        },
        "role": {
          "title": "CreateStaffRequest.role",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/StaffStatus",
          "title": "CreateStaffRequest.status"
        }
      },
      "required": [
        "name",
        "phoneNumber"
      ],
      "additionalProperties": false,
      "title": "CreateStaffRequest",
      "type": "object"
    },
    "UpdateStaffRequest": {
      "properties": {
        "name": {
          "title": "UpdateStaffRequest.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "UpdateStaffRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "UpdateStaffRequest.email",
          "type": "string"
        },
        "role": {
          "title": "UpdateStaffRequest.role",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/StaffStatus",
          "title": "UpdateStaffRequest.status"
        }
      },
      "additionalProperties": false,
      "title": "UpdateStaffRequest",
      "type": "object"
    },
    "Staff": {
      "properties": {
        "staffId": {
          "title": "Staff.staffId",
          "type": "string"
        },
        "vendorId": {
          "title": "Staff.vendorId",
          "type": "string"
        },
        "userId": {
          "title": "Staff.userId",
          "type": "string"
        },
        "name": {
          "title": "Staff.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "Staff.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "Staff.email",
          "type": "string"
        },
        "role": {
          "title": "Staff.role",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/StaffStatus",
          "title": "Staff.status"
        },
        "createdAt": {
          "title": "Staff.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "Staff.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "staffId",
        "vendorId",
        "name",
        "status",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "Staff",
      "type": "object"
    },
    "StaffResponse": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Staff",
          "title": "StaffResponse.data"
        }
      },
      "additionalProperties": false,
      "title": "StaffResponse",
      "type": "object"
    },
    "StaffListResponse": {
      "properties": {
        "data": {
          "items": {
            "$ref": "#/definitions/Staff",
            "title": "StaffListResponse.data.[]"
          },
          "title": "StaffListResponse.data",
          "type": "array"
        },
        "pagination": {
          "$ref": "#/definitions/Pagination",
          "title": "StaffListResponse.pagination"
        }
      },
      "additionalProperties": false,
      "title": "StaffListResponse",
      "type": "object"
    },
    "VendorCapabilities": {
      "properties": {
        "vendorId": {
          "title": "VendorCapabilities.vendorId",
          "type": "string"
        },
        "vehicleTypes": {
          "items": {
            "$ref": "#/definitions/VehicleType",
            "title": "VendorCapabilities.vehicleTypes.[]"
          },
          "title": "VendorCapabilities.vehicleTypes",
          "type": "array"
        },
        "serviceIds": {
          "items": {
            "title": "VendorCapabilities.serviceIds.[]",
            "type": "string"
          },
          "title": "VendorCapabilities.serviceIds",
          "type": "array"
        },
        "packageIds": {
          "items": {
            "title": "VendorCapabilities.packageIds.[]",
            "type": "string"
          },
          "title": "VendorCapabilities.packageIds",
          "type": "array"
        },
        "updatedAt": {
          "title": "VendorCapabilities.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "vendorId",
        "vehicleTypes",
        "serviceIds",
        "packageIds"
      ],
      "additionalProperties": false,
      "title": "VendorCapabilities",
      "type": "object"
    },
    "UpdateVendorCapabilitiesRequest": {
      "properties": {
        "vehicleTypes": {
          "items": {
            "$ref": "#/definitions/VehicleType",
            "title": "UpdateVendorCapabilitiesRequest.vehicleTypes.[]"
          },
          "title": "UpdateVendorCapabilitiesRequest.vehicleTypes",
          "type": "array"
        },
        "serviceIds": {
          "items": {
            "title": "UpdateVendorCapabilitiesRequest.serviceIds.[]",
            "type": "string"
          },
          "title": "UpdateVendorCapabilitiesRequest.serviceIds",
          "type": "array"
        },
        "packageIds": {
          "items": {
            "title": "UpdateVendorCapabilitiesRequest.packageIds.[]",
            "type": "string"
          },
          "title": "UpdateVendorCapabilitiesRequest.packageIds",
          "type": "array"
        }
      },
      "required": [
        "vehicleTypes",
        "serviceIds",
        "packageIds"
      ],
      "additionalProperties": false,
      "title": "UpdateVendorCapabilitiesRequest",
      "type": "object"
    },
    "Pagination": {
      "properties": {
        "nextCursor": {
          "title": "Pagination.nextCursor",
          "nullable": true,
          "type": "string"
        },
        "hasMore": {
          "title": "Pagination.hasMore",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "title": "Pagination",
      "type": "object"
    },
    "Error": {
      "properties": {
        "code": {
          "title": "Error.code",
          "type": "string"
        },
        "message": {
          "title": "Error.message",
          "type": "string"
        },
        "correlationId": {
          "title": "Error.correlationId",
          "type": "string"
        },
        "details": {
          "items": {
            "additionalProperties": {},
            "title": "Error.details.[]",
            "type": "object"
          },
          "title": "Error.details",
          "type": "array"
        }
      },
      "required": [
        "code",
        "message"
      ],
      "additionalProperties": false,
      "title": "Error",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};