// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Beauty on Wheels - Vendor Service API",
    "version": "1"
  },
  "paths": {
    "/vendors": {
      "post": {
        "summary": "Create vendor",
        "description": "Creates a new Vendor profile with a unique vendorId and the submitted business information. Each POST mints a new vendorId. Progressive section data is saved via PUT /vendors/{vendorId}/onboarding.",
        "tags": [
          "Vendors"
        ],
        "operationId": "createvendor.post./vendors",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateVendorRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Vendor created successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      },
      "get": {
        "summary": "List vendors",
        "description": "Lists vendors using optional filters.\nIntended primarily for admin and operational use.\n",
        "tags": [
          "Vendors"
        ],
        "operationId": "listvendors.get./vendors",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Vendors retrieved successfully",
            "schema": {
              "$ref": "#/definitions/VendorListResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/onboarding": {
      "get": {
        "summary": "Get vendor onboarding state",
        "description": "Returns backend-authoritative onboarding progress and persisted section data so the frontend can resume.",
        "tags": [
          "Onboarding"
        ],
        "operationId": "getvendoronboarding.get./vendors/{vendorId}/onboarding",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Onboarding state retrieved",
            "schema": {
              "$ref": "#/definitions/OnboardingResponse"
            }
          },
          "401": {
            "description": "401 response"
          },
          "403": {
            "description": "403 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Save an onboarding section",
        "description": "Progressively creates or updates one onboarding section. `section` identifies the domain portion. Repeated PUTs or PATCHes for the same section update in place. The `data` payload is validated against the selected section schema. Vendors may be onboarded by the vendor owner or by platform admin staff.",
        "tags": [
          "Onboarding"
        ],
        "operationId": "updatevendoronboarding.put./vendors/{vendorId}/onboarding",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateOnboardingRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Onboarding section saved",
            "schema": {
              "$ref": "#/definitions/OnboardingResponse"
            }
          },
          "400": {
            "description": "Invalid section or section payload"
          },
          "401": {
            "description": "401 response"
          },
          "403": {
            "description": "403 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "patch": {
        "summary": "Save an onboarding section",
        "description": "Progressively creates or updates one onboarding section. Same contract as PUT /vendors/{vendorId}/onboarding.",
        "tags": [
          "Onboarding"
        ],
        "operationId": "updatevendoronboarding.patch./vendors/{vendorId}/onboarding",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateOnboardingRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Onboarding section saved",
            "schema": {
              "$ref": "#/definitions/OnboardingResponse"
            }
          },
          "400": {
            "description": "Invalid section or section payload"
          },
          "401": {
            "description": "401 response"
          },
          "403": {
            "description": "403 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}": {
      "get": {
        "summary": "Get vendor",
        "description": "Returns the vendor profile and primary address. Bank details are omitted.",
        "tags": [
          "Vendors"
        ],
        "operationId": "getvendor.get./vendors/{vendorId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor retrieved successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "401": {
            "description": "401 response"
          },
          "403": {
            "description": "403 response"
          },
          "404": {
            "description": "404 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      },
      "patch": {
        "summary": "Update vendor",
        "description": "Updates vendor profile fields. Address, owner, bank, branches and documents are not updated here — use onboarding or dedicated resource APIs.",
        "tags": [
          "Vendors"
        ],
        "operationId": "updatevendor.patch./vendors/{vendorId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateVendorRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor updated successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/status": {
      "patch": {
        "summary": "Update vendor lifecycle status",
        "description": "Updates the administrative lifecycle status of a vendor.\n\nTypical lifecycle:\n  PENDING_VERIFICATION\n  -> ACTIVE\n  -> SUSPENDED\n  -> ACTIVE\n  -> INACTIVE\n",
        "tags": [
          "Vendors"
        ],
        "operationId": "updatevendorstatus.patch./vendors/{vendorId}/status",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateVendorStatusRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor status updated successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "403": {
            "description": "403 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/operational-status": {
      "patch": {
        "summary": "Update vendor operational status",
        "description": "Controls whether a vendor is currently accepting work.\n\nThis is different from the administrative vendor lifecycle status.\n",
        "tags": [
          "Vendors"
        ],
        "operationId": "updatevendoroperationalstatus.patch./vendors/{vendorId}/operational-status",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateOperationalStatusRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Operational status updated successfully",
            "schema": {
              "$ref": "#/definitions/VendorResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/service-areas": {
      "get": {
        "summary": "List vendor service areas",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "listvendorserviceareas.get./vendors/{vendorId}/service-areas",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Service areas retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      },
      "post": {
        "summary": "Add vendor service area",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "addvendorservicearea.post./vendors/{vendorId}/service-areas",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateServiceAreaRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Service area created successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          },
          "500": {
            "description": "500 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/service-areas/{serviceAreaId}": {
      "get": {
        "summary": "Get vendor service area",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "getvendorservicearea.get./vendors/{vendorId}/service-areas/{serviceAreaId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "serviceAreaId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Service area retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "patch": {
        "summary": "Update vendor service area",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "updatevendorservicearea.patch./vendors/{vendorId}/service-areas/{serviceAreaId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateServiceAreaRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "serviceAreaId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Service area updated successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "delete": {
        "summary": "Remove vendor service area",
        "description": "",
        "tags": [
          "Service Areas"
        ],
        "operationId": "deletevendorservicearea.delete./vendors/{vendorId}/service-areas/{serviceAreaId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "serviceAreaId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Service area removed successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/operating-hours": {
      "get": {
        "summary": "Get vendor operating hours",
        "description": "",
        "tags": [
          "Operating Hours"
        ],
        "operationId": "getvendoroperatinghours.get./vendors/{vendorId}/operating-hours",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Operating hours retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Replace vendor operating hours",
        "description": "Replaces the vendor's standard weekly operating schedule.\n\nAvailability Service may use this schedule as an input when\ngenerating or validating bookable slots.\n",
        "tags": [
          "Operating Hours"
        ],
        "operationId": "updatevendoroperatinghours.put./vendors/{vendorId}/operating-hours",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateVendorOperatingHoursRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Operating hours updated successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/staff": {
      "get": {
        "summary": "List vendor staff",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "listvendorstaff.get./vendors/{vendorId}/staff",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Staff retrieved successfully",
            "schema": {
              "$ref": "#/definitions/StaffListResponse"
            }
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "post": {
        "summary": "Add vendor staff member",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "createvendorstaff.post./vendors/{vendorId}/staff",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateStaffRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Staff member created successfully",
            "schema": {
              "$ref": "#/definitions/StaffResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/staff/{staffId}": {
      "get": {
        "summary": "Get vendor staff member",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "getvendorstaff.get./vendors/{vendorId}/staff/{staffId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "staffId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Staff member retrieved successfully",
            "schema": {
              "$ref": "#/definitions/StaffResponse"
            }
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "patch": {
        "summary": "Update vendor staff member",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "updatevendorstaff.patch./vendors/{vendorId}/staff/{staffId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateStaffRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "staffId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Staff member updated successfully",
            "schema": {
              "$ref": "#/definitions/StaffResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Replace vendor staff member",
        "description": "",
        "tags": [
          "Staff"
        ],
        "operationId": "updatevendorstaff.put./vendors/{vendorId}/staff/{staffId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateStaffRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "staffId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Staff member updated successfully",
            "schema": {
              "$ref": "#/definitions/StaffResponse"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "delete": {
        "summary": "Deactivate vendor staff member",
        "description": "Deactivates the staff member.\nHistorical booking/job references should remain intact.\n",
        "tags": [
          "Staff"
        ],
        "operationId": "deactivatevendorstaff.delete./vendors/{vendorId}/staff/{staffId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "staffId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Staff member deactivated successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/capabilities": {
      "get": {
        "summary": "List available capabilities",
        "description": "Returns capability master data. Vendor assignments store IDs only; service and package definitions remain in Service Catalog.",
        "tags": [
          "Capabilities"
        ],
        "operationId": "listavailablecapabilities.get./capabilities",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "Available capabilities retrieved",
            "schema": {
              "$ref": "#/definitions/AvailableCapabilities"
            }
          },
          "401": {
            "description": "401 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/capabilities": {
      "get": {
        "summary": "Get vendor capabilities",
        "description": "",
        "tags": [
          "Capabilities"
        ],
        "operationId": "getvendorcapabilities.get./vendors/{vendorId}/capabilities",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor capabilities retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Replace vendor capabilities",
        "description": "Updates the services, packages and vehicle types that the vendor\nis capable of supporting.\n\nserviceIds and packageIds are references to entities owned by the\nService Catalog Service.\n\nThis endpoint does not define pricing or availability.\n",
        "tags": [
          "Capabilities"
        ],
        "operationId": "updatevendorcapabilities.put./vendors/{vendorId}/capabilities",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateVendorCapabilitiesRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Vendor capabilities updated successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          },
          "409": {
            "description": "409 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/branches": {
      "get": {
        "summary": "List vendor branches",
        "description": "",
        "tags": [
          "Branches"
        ],
        "operationId": "listvendorbranches.get./vendors/{vendorId}/branches",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Branches retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "403": {
            "description": "403 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "post": {
        "summary": "Create vendor branch",
        "description": "",
        "tags": [
          "Branches"
        ],
        "operationId": "createvendorbranch.post./vendors/{vendorId}/branches",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateBranchRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Branch created successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/branches/{branchId}": {
      "get": {
        "summary": "Get vendor branch",
        "description": "",
        "tags": [
          "Branches"
        ],
        "operationId": "getvendorbranch.get./vendors/{vendorId}/branches/{branchId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "branchId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Branch retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Update vendor branch",
        "description": "",
        "tags": [
          "Branches"
        ],
        "operationId": "updatevendorbranch.put./vendors/{vendorId}/branches/{branchId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateBranchRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "branchId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Branch updated successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "delete": {
        "summary": "Delete vendor branch",
        "description": "",
        "tags": [
          "Branches"
        ],
        "operationId": "deletevendorbranch.delete./vendors/{vendorId}/branches/{branchId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "branchId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Branch deleted successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/documents": {
      "get": {
        "summary": "List vendor documents",
        "description": "",
        "tags": [
          "Documents"
        ],
        "operationId": "listvendordocuments.get./vendors/{vendorId}/documents",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Documents retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "post": {
        "summary": "Create vendor document metadata and upload URL",
        "description": "",
        "tags": [
          "Documents"
        ],
        "operationId": "createvendordocument.post./vendors/{vendorId}/documents",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateDocumentRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "201": {
            "description": "Document created successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "409": {
            "description": "409 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/documents/{documentId}": {
      "get": {
        "summary": "Get vendor document",
        "description": "",
        "tags": [
          "Documents"
        ],
        "operationId": "getvendordocument.get./vendors/{vendorId}/documents/{documentId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "documentId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Document retrieved successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Replace vendor document",
        "description": "",
        "tags": [
          "Documents"
        ],
        "operationId": "updatevendordocument.put./vendors/{vendorId}/documents/{documentId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateDocumentRequest"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "documentId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Document updated successfully"
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "delete": {
        "summary": "Delete vendor document",
        "description": "",
        "tags": [
          "Documents"
        ],
        "operationId": "deletevendordocument.delete./vendors/{vendorId}/documents/{documentId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "documentId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Document deleted successfully"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    },
    "/vendors/{vendorId}/bank-details": {
      "get": {
        "summary": "Get vendor bank details",
        "description": "Returns masked banking information. Full account numbers are never returned.",
        "tags": [
          "Bank Details"
        ],
        "operationId": "getvendorbankdetails.get./vendors/{vendorId}/bank-details",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Bank details retrieved successfully",
            "schema": {
              "$ref": "#/definitions/BankDetails"
            }
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      },
      "put": {
        "summary": "Create or update vendor bank details",
        "description": "",
        "tags": [
          "Bank Details"
        ],
        "operationId": "updatevendorbankdetails.put./vendors/{vendorId}/bank-details",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BankDetailsData"
            }
          },
          {
            "name": "vendorId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Bank details saved successfully",
            "schema": {
              "$ref": "#/definitions/BankDetails"
            }
          },
          "400": {
            "description": "400 response"
          },
          "401": {
            "description": "401 response"
          },
          "404": {
            "description": "404 response"
          }
        }
      }
    }
  },
  "definitions": {
    "VendorStatus": {
      "enum": [
        "PENDING_VERIFICATION",
        "ACTIVE",
        "SUSPENDED",
        "INACTIVE",
        "REJECTED"
      ],
      "title": "VendorStatus",
      "description": "This file was automatically generated from the OpenAPI specification.\nDO NOT EDIT DIRECTLY.",
      "type": "string"
    },
    "OperationalStatus": {
      "enum": [
        "ONLINE",
        "OFFLINE",
        "BUSY",
        "TEMPORARILY_UNAVAILABLE"
      ],
      "title": "OperationalStatus",
      "type": "string"
    },
    "VendorType": {
      "enum": [
        "INDIVIDUAL",
        "BUSINESS"
      ],
      "title": "VendorType",
      "type": "string"
    },
    "VehicleType": {
      "enum": [
        "HATCHBACK",
        "SEDAN",
        "SUV",
        "MUV",
        "LUXURY",
        "OTHER"
      ],
      "title": "VehicleType",
      "type": "string"
    },
    "StaffStatus": {
      "enum": [
        "ACTIVE",
        "INACTIVE"
      ],
      "title": "StaffStatus",
      "type": "string"
    },
    "DayOfWeek": {
      "enum": [
        "MONDAY",
        "TUESDAY",
        "WEDNESDAY",
        "THURSDAY",
        "FRIDAY",
        "SATURDAY",
        "SUNDAY"
      ],
      "title": "DayOfWeek",
      "type": "string"
    },
    "OnboardingSection": {
      "enum": [
        "BUSINESS_INFO",
        "OWNER_DETAILS",
        "ADDRESS",
        "BRANCH",
        "DOCUMENTS",
        "BANK_DETAILS"
      ],
      "title": "OnboardingSection",
      "type": "string"
    },
    "OnboardingStatus": {
      "enum": [
        "DRAFT",
        "IN_PROGRESS",
        "COMPLETED",
        "PENDING_REVIEW"
      ],
      "title": "OnboardingStatus",
      "type": "string"
    },
    "DocumentType": {
      "enum": [
        "GST_REGISTRATION",
        "BUSINESS_REGISTRATION",
        "COMMERCIAL_INSURANCE"
      ],
      "title": "DocumentType",
      "type": "string"
    },
    "DocumentStatus": {
      "enum": [
        "PENDING_UPLOAD",
        "UPLOADED"
      ],
      "title": "DocumentStatus",
      "type": "string"
    },
    "BankAccountType": {
      "enum": [
        "SAVINGS",
        "CURRENT"
      ],
      "title": "BankAccountType",
      "type": "string"
    },
    "CapabilityCategory": {
      "title": "CapabilityCategory",
      "enum": [
        "vehicleType"
      ],
      "type": "string"
    },
    "Address": {
      "properties": {
        "addressLine1": {
          "title": "Address.addressLine1",
          "type": "string"
        },
        "addressLine2": {
          "title": "Address.addressLine2",
          "type": "string"
        },
        "landmark": {
          "title": "Address.landmark",
          "type": "string"
        },
        "city": {
          "title": "Address.city",
          "type": "string"
        },
        "state": {
          "title": "Address.state",
          "type": "string"
        },
        "country": {
          "title": "Address.country",
          "type": "string"
        },
        "postalCode": {
          "title": "Address.postalCode",
          "type": "string"
        }
      },
      "required": [
        "addressLine1",
        "city",
        "state",
        "country",
        "postalCode"
      ],
      "additionalProperties": false,
      "title": "Address",
      "type": "object"
    },
    "GeoLocation": {
      "properties": {
        "latitude": {
          "title": "GeoLocation.latitude",
          "type": "number"
        },
        "longitude": {
          "title": "GeoLocation.longitude",
          "type": "number"
        }
      },
      "required": [
        "latitude",
        "longitude"
      ],
      "additionalProperties": false,
      "title": "GeoLocation",
      "type": "object"
    },
    "CreateVendorRequest": {
      "properties": {
        "businessName": {
          "title": "CreateVendorRequest.businessName",
          "type": "string"
        },
        "contactName": {
          "title": "CreateVendorRequest.contactName",
          "type": "string"
        },
        "phoneNumber": {
          "title": "CreateVendorRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "CreateVendorRequest.email",
          "type": "string"
        },
        "description": {
          "title": "CreateVendorRequest.description",
          "type": "string"
        },
        "gstNumber": {
          "title": "CreateVendorRequest.gstNumber",
          "type": "string"
        },
        "panNumber": {
          "title": "CreateVendorRequest.panNumber",
          "type": "string"
        },
        "profileImageUrl": {
          "title": "CreateVendorRequest.profileImageUrl",
          "type": "string"
        },
        "vendorType": {
          "$ref": "#/definitions/VendorType",
          "title": "CreateVendorRequest.vendorType"
        },
        "ownerUserId": {
          "title": "CreateVendorRequest.ownerUserId",
          "type": "string"
        }
      },
      "required": [
        "businessName",
        "contactName"
      ],
      "additionalProperties": false,
      "title": "CreateVendorRequest",
      "type": "object"
    },
    "UpdateVendorRequest": {
      "properties": {
        "businessName": {
          "title": "UpdateVendorRequest.businessName",
          "type": "string"
        },
        "contactName": {
          "title": "UpdateVendorRequest.contactName",
          "type": "string"
        },
        "phoneNumber": {
          "title": "UpdateVendorRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "UpdateVendorRequest.email",
          "type": "string"
        },
        "description": {
          "title": "UpdateVendorRequest.description",
          "type": "string"
        },
        "profileImageUrl": {
          "title": "UpdateVendorRequest.profileImageUrl",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "UpdateVendorRequest",
      "type": "object"
    },
    "UpdateVendorStatusRequest": {
      "properties": {
        "status": {
          "$ref": "#/definitions/VendorStatus",
          "title": "UpdateVendorStatusRequest.status"
        },
        "reason": {
          "title": "UpdateVendorStatusRequest.reason",
          "type": "string"
        }
      },
      "required": [
        "status"
      ],
      "additionalProperties": false,
      "title": "UpdateVendorStatusRequest",
      "type": "object"
    },
    "UpdateOperationalStatusRequest": {
      "properties": {
        "operationalStatus": {
          "$ref": "#/definitions/OperationalStatus",
          "title": "UpdateOperationalStatusRequest.operationalStatus"
        }
      },
      "required": [
        "operationalStatus"
      ],
      "additionalProperties": false,
      "title": "UpdateOperationalStatusRequest",
      "type": "object"
    },
    "BusinessInfoData": {
      "properties": {
        "vendorType": {
          "$ref": "#/definitions/VendorType",
          "title": "BusinessInfoData.vendorType"
        },
        "businessName": {
          "title": "BusinessInfoData.businessName",
          "type": "string"
        },
        "contactName": {
          "title": "BusinessInfoData.contactName",
          "type": "string"
        },
        "phoneNumber": {
          "title": "BusinessInfoData.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "BusinessInfoData.email",
          "type": "string"
        },
        "description": {
          "title": "BusinessInfoData.description",
          "type": "string"
        },
        "gstNumber": {
          "title": "BusinessInfoData.gstNumber",
          "type": "string"
        },
        "panNumber": {
          "title": "BusinessInfoData.panNumber",
          "type": "string"
        },
        "profileImageUrl": {
          "title": "BusinessInfoData.profileImageUrl",
          "type": "string"
        }
      },
      "required": [
        "vendorType",
        "businessName",
        "contactName",
        "phoneNumber"
      ],
      "additionalProperties": false,
      "title": "BusinessInfoData",
      "type": "object"
    },
    "OwnerDetailsData": {
      "properties": {
        "userId": {
          "title": "OwnerDetailsData.userId",
          "type": "string"
        },
        "fullName": {
          "title": "OwnerDetailsData.fullName",
          "type": "string"
        },
        "designation": {
          "title": "OwnerDetailsData.designation",
          "type": "string"
        },
        "phoneNumber": {
          "title": "OwnerDetailsData.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "OwnerDetailsData.email",
          "type": "string"
        }
      },
      "required": [
        "userId",
        "fullName"
      ],
      "additionalProperties": false,
      "title": "OwnerDetailsData",
      "type": "object"
    },
    "AddressData": {
      "properties": {
        "addressLine1": {
          "title": "AddressData.addressLine1",
          "type": "string"
        },
        "addressLine2": {
          "title": "AddressData.addressLine2",
          "type": "string"
        },
        "landmark": {
          "title": "AddressData.landmark",
          "type": "string"
        },
        "city": {
          "title": "AddressData.city",
          "type": "string"
        },
        "state": {
          "title": "AddressData.state",
          "type": "string"
        },
        "country": {
          "title": "AddressData.country",
          "type": "string"
        },
        "postalCode": {
          "title": "AddressData.postalCode",
          "type": "string"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "AddressData.geoLocation"
        }
      },
      "required": [
        "addressLine1",
        "city",
        "state",
        "country",
        "postalCode"
      ],
      "additionalProperties": false,
      "title": "AddressData",
      "type": "object"
    },
    "BranchData": {
      "properties": {
        "branchId": {
          "title": "BranchData.branchId",
          "type": "string"
        },
        "name": {
          "title": "BranchData.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "BranchData.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "BranchData.email",
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address",
          "title": "BranchData.address"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "BranchData.geoLocation"
        },
        "isPrimary": {
          "title": "BranchData.isPrimary",
          "type": "boolean"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "title": "BranchData",
      "type": "object"
    },
    "DocumentsData": {
      "properties": {
        "documentType": {
          "$ref": "#/definitions/DocumentType",
          "title": "DocumentsData.documentType"
        },
        "fileName": {
          "title": "DocumentsData.fileName",
          "type": "string"
        },
        "contentType": {
          "title": "DocumentsData.contentType",
          "type": "string"
        }
      },
      "required": [
        "documentType",
        "fileName",
        "contentType"
      ],
      "additionalProperties": false,
      "title": "DocumentsData",
      "type": "object"
    },
    "BankDetailsData": {
      "properties": {
        "accountHolderName": {
          "title": "BankDetailsData.accountHolderName",
          "type": "string"
        },
        "accountNumber": {
          "title": "BankDetailsData.accountNumber",
          "type": "string"
        },
        "ifscCode": {
          "title": "BankDetailsData.ifscCode",
          "type": "string"
        },
        "bankName": {
          "title": "BankDetailsData.bankName",
          "type": "string"
        },
        "branchName": {
          "title": "BankDetailsData.branchName",
          "type": "string"
        },
        "accountType": {
          "$ref": "#/definitions/BankAccountType",
          "title": "BankDetailsData.accountType"
        }
      },
      "required": [
        "accountHolderName",
        "accountNumber",
        "ifscCode",
        "bankName"
      ],
      "additionalProperties": false,
      "title": "BankDetailsData",
      "type": "object"
    },
    "UpdateOnboardingRequest": {
      "properties": {
        "section": {
          "$ref": "#/definitions/OnboardingSection",
          "title": "UpdateOnboardingRequest.section"
        },
        "data": {
          "anyOf": [
            {
              "$ref": "#/definitions/BusinessInfoData",
              "title": "UpdateOnboardingRequest.data"
            },
            {
              "$ref": "#/definitions/OwnerDetailsData",
              "title": "UpdateOnboardingRequest.data"
            },
            {
              "$ref": "#/definitions/AddressData",
              "title": "UpdateOnboardingRequest.data"
            },
            {
              "$ref": "#/definitions/BranchData",
              "title": "UpdateOnboardingRequest.data"
            },
            {
              "$ref": "#/definitions/DocumentsData",
              "title": "UpdateOnboardingRequest.data"
            },
            {
              "$ref": "#/definitions/BankDetailsData",
              "title": "UpdateOnboardingRequest.data"
            }
          ],
          "title": "UpdateOnboardingRequest.data"
        }
      },
      "required": [
        "section",
        "data"
      ],
      "additionalProperties": false,
      "title": "UpdateOnboardingRequest",
      "type": "object"
    },
    "VendorOwner": {
      "properties": {
        "vendorId": {
          "title": "VendorOwner.vendorId",
          "type": "string"
        },
        "userId": {
          "title": "VendorOwner.userId",
          "type": "string"
        },
        "fullName": {
          "title": "VendorOwner.fullName",
          "type": "string"
        },
        "designation": {
          "title": "VendorOwner.designation",
          "type": "string"
        },
        "phoneNumber": {
          "title": "VendorOwner.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "VendorOwner.email",
          "type": "string"
        },
        "createdAt": {
          "title": "VendorOwner.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "VendorOwner.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "vendorId",
        "userId",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "VendorOwner",
      "type": "object"
    },
    "VendorAddress": {
      "properties": {
        "vendorId": {
          "title": "VendorAddress.vendorId",
          "type": "string"
        },
        "addressLine1": {
          "title": "VendorAddress.addressLine1",
          "type": "string"
        },
        "addressLine2": {
          "title": "VendorAddress.addressLine2",
          "type": "string"
        },
        "landmark": {
          "title": "VendorAddress.landmark",
          "type": "string"
        },
        "city": {
          "title": "VendorAddress.city",
          "type": "string"
        },
        "state": {
          "title": "VendorAddress.state",
          "type": "string"
        },
        "country": {
          "title": "VendorAddress.country",
          "type": "string"
        },
        "postalCode": {
          "title": "VendorAddress.postalCode",
          "type": "string"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "VendorAddress.geoLocation"
        },
        "createdAt": {
          "title": "VendorAddress.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "VendorAddress.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "vendorId",
        "addressLine1",
        "city",
        "state",
        "country",
        "postalCode",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "VendorAddress",
      "type": "object"
    },
    "BankDetails": {
      "properties": {
        "vendorId": {
          "title": "BankDetails.vendorId",
          "type": "string"
        },
        "accountHolderName": {
          "title": "BankDetails.accountHolderName",
          "type": "string"
        },
        "accountNumberLast4": {
          "title": "BankDetails.accountNumberLast4",
          "type": "string"
        },
        "accountNumberMasked": {
          "title": "BankDetails.accountNumberMasked",
          "type": "string"
        },
        "ifscCode": {
          "title": "BankDetails.ifscCode",
          "type": "string"
        },
        "bankName": {
          "title": "BankDetails.bankName",
          "type": "string"
        },
        "branchName": {
          "title": "BankDetails.branchName",
          "type": "string"
        },
        "accountType": {
          "$ref": "#/definitions/BankAccountType",
          "title": "BankDetails.accountType"
        },
        "createdAt": {
          "title": "BankDetails.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "BankDetails.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "vendorId",
        "accountHolderName",
        "accountNumberLast4",
        "accountNumberMasked",
        "ifscCode",
        "bankName",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "BankDetails",
      "type": "object"
    },
    "VendorBranch": {
      "properties": {
        "branchId": {
          "title": "VendorBranch.branchId",
          "type": "string"
        },
        "vendorId": {
          "title": "VendorBranch.vendorId",
          "type": "string"
        },
        "name": {
          "title": "VendorBranch.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "VendorBranch.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "VendorBranch.email",
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address",
          "title": "VendorBranch.address"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "VendorBranch.geoLocation"
        },
        "isPrimary": {
          "title": "VendorBranch.isPrimary",
          "type": "boolean"
        },
        "createdAt": {
          "title": "VendorBranch.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "VendorBranch.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "branchId",
        "vendorId",
        "name",
        "isPrimary",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "VendorBranch",
      "type": "object"
    },
    "CreateBranchRequest": {
      "properties": {
        "name": {
          "title": "CreateBranchRequest.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "CreateBranchRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "CreateBranchRequest.email",
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address",
          "title": "CreateBranchRequest.address"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "CreateBranchRequest.geoLocation"
        },
        "isPrimary": {
          "title": "CreateBranchRequest.isPrimary",
          "type": "boolean"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false,
      "title": "CreateBranchRequest",
      "type": "object"
    },
    "UpdateBranchRequest": {
      "properties": {
        "name": {
          "title": "UpdateBranchRequest.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "UpdateBranchRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "UpdateBranchRequest.email",
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address",
          "title": "UpdateBranchRequest.address"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "UpdateBranchRequest.geoLocation"
        },
        "isPrimary": {
          "title": "UpdateBranchRequest.isPrimary",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "title": "UpdateBranchRequest",
      "type": "object"
    },
    "VendorDocument": {
      "properties": {
        "documentId": {
          "title": "VendorDocument.documentId",
          "type": "string"
        },
        "vendorId": {
          "title": "VendorDocument.vendorId",
          "type": "string"
        },
        "documentType": {
          "$ref": "#/definitions/DocumentType",
          "title": "VendorDocument.documentType"
        },
        "fileName": {
          "title": "VendorDocument.fileName",
          "type": "string"
        },
        "contentType": {
          "title": "VendorDocument.contentType",
          "type": "string"
        },
        "objectKey": {
          "title": "VendorDocument.objectKey",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/DocumentStatus",
          "title": "VendorDocument.status"
        },
        "uploadUrl": {
          "title": "VendorDocument.uploadUrl",
          "type": "string"
        },
        "downloadUrl": {
          "title": "VendorDocument.downloadUrl",
          "type": "string"
        },
        "createdAt": {
          "title": "VendorDocument.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "VendorDocument.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "documentId",
        "vendorId",
        "documentType",
        "fileName",
        "contentType",
        "objectKey",
        "status",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "VendorDocument",
      "type": "object"
    },
    "CreateDocumentRequest": {
      "properties": {
        "documentType": {
          "$ref": "#/definitions/DocumentType",
          "title": "CreateDocumentRequest.documentType"
        },
        "fileName": {
          "title": "CreateDocumentRequest.fileName",
          "type": "string"
        },
        "contentType": {
          "title": "CreateDocumentRequest.contentType",
          "type": "string"
        }
      },
      "required": [
        "documentType",
        "fileName",
        "contentType"
      ],
      "additionalProperties": false,
      "title": "CreateDocumentRequest",
      "type": "object"
    },
    "UpdateDocumentRequest": {
      "properties": {
        "fileName": {
          "title": "UpdateDocumentRequest.fileName",
          "type": "string"
        },
        "contentType": {
          "title": "UpdateDocumentRequest.contentType",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "UpdateDocumentRequest",
      "type": "object"
    },
    "OnboardingState": {
      "properties": {
        "vendorId": {
          "title": "OnboardingState.vendorId",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/OnboardingStatus",
          "title": "OnboardingState.status"
        },
        "currentSection": {
          "$ref": "#/definitions/OnboardingSection",
          "title": "OnboardingState.currentSection"
        },
        "completedSections": {
          "items": {
            "$ref": "#/definitions/OnboardingSection",
            "title": "OnboardingState.completedSections.[]"
          },
          "title": "OnboardingState.completedSections",
          "type": "array"
        }
      },
      "required": [
        "vendorId",
        "status",
        "currentSection",
        "completedSections"
      ],
      "additionalProperties": false,
      "title": "OnboardingState",
      "type": "object"
    },
    "OnboardingResponse": {
      "properties": {
        "vendorId": {
          "title": "OnboardingResponse.vendorId",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/OnboardingStatus",
          "title": "OnboardingResponse.status"
        },
        "currentSection": {
          "$ref": "#/definitions/OnboardingSection",
          "title": "OnboardingResponse.currentSection"
        },
        "completedSections": {
          "items": {
            "$ref": "#/definitions/OnboardingSection",
            "title": "OnboardingResponse.completedSections.[]"
          },
          "title": "OnboardingResponse.completedSections",
          "type": "array"
        },
        "applicationId": {
          "title": "OnboardingResponse.applicationId",
          "type": "string"
        },
        "sections": {
          "properties": {
            "BUSINESS_INFO": {
              "$ref": "#/definitions/BusinessInfoData",
              "title": "OnboardingResponse.sections.BUSINESS_INFO"
            },
            "OWNER_DETAILS": {
              "$ref": "#/definitions/VendorOwner",
              "title": "OnboardingResponse.sections.OWNER_DETAILS"
            },
            "ADDRESS": {
              "$ref": "#/definitions/VendorAddress",
              "title": "OnboardingResponse.sections.ADDRESS"
            },
            "BRANCH": {
              "items": {
                "$ref": "#/definitions/VendorBranch",
                "title": "OnboardingResponse.sections.BRANCH.[]"
              },
              "title": "OnboardingResponse.sections.BRANCH",
              "type": "array"
            },
            "DOCUMENTS": {
              "items": {
                "$ref": "#/definitions/VendorDocument",
                "title": "OnboardingResponse.sections.DOCUMENTS.[]"
              },
              "title": "OnboardingResponse.sections.DOCUMENTS",
              "type": "array"
            },
            "BANK_DETAILS": {
              "$ref": "#/definitions/BankDetails",
              "title": "OnboardingResponse.sections.BANK_DETAILS"
            }
          },
          "additionalProperties": false,
          "title": "OnboardingResponse.sections",
          "type": "object"
        }
      },
      "required": [
        "vendorId",
        "status",
        "currentSection",
        "completedSections",
        "sections"
      ],
      "additionalProperties": false,
      "title": "OnboardingResponse",
      "type": "object"
    },
    "Vendor": {
      "properties": {
        "vendorId": {
          "title": "Vendor.vendorId",
          "type": "string"
        },
        "ownerUserId": {
          "title": "Vendor.ownerUserId",
          "type": "string"
        },
        "vendorType": {
          "$ref": "#/definitions/VendorType",
          "title": "Vendor.vendorType"
        },
        "businessName": {
          "title": "Vendor.businessName",
          "type": "string"
        },
        "contactName": {
          "title": "Vendor.contactName",
          "type": "string"
        },
        "phoneNumber": {
          "title": "Vendor.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "Vendor.email",
          "type": "string"
        },
        "description": {
          "title": "Vendor.description",
          "type": "string"
        },
        "profileImageUrl": {
          "title": "Vendor.profileImageUrl",
          "type": "string"
        },
        "gstNumber": {
          "title": "Vendor.gstNumber",
          "type": "string"
        },
        "panNumber": {
          "title": "Vendor.panNumber",
          "type": "string"
        },
        "address": {
          "$ref": "#/definitions/Address",
          "title": "Vendor.address"
        },
        "geoLocation": {
          "$ref": "#/definitions/GeoLocation",
          "title": "Vendor.geoLocation"
        },
        "status": {
          "$ref": "#/definitions/VendorStatus",
          "title": "Vendor.status"
        },
        "operationalStatus": {
          "$ref": "#/definitions/OperationalStatus",
          "title": "Vendor.operationalStatus"
        },
        "onboardingStatus": {
          "$ref": "#/definitions/OnboardingStatus",
          "title": "Vendor.onboardingStatus"
        },
        "currentSection": {
          "$ref": "#/definitions/OnboardingSection",
          "title": "Vendor.currentSection"
        },
        "completedSections": {
          "items": {
            "$ref": "#/definitions/OnboardingSection",
            "title": "Vendor.completedSections.[]"
          },
          "title": "Vendor.completedSections",
          "type": "array"
        },
        "applicationId": {
          "title": "Vendor.applicationId",
          "type": "string"
        },
        "createdAt": {
          "title": "Vendor.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "Vendor.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "vendorId",
        "ownerUserId",
        "status",
        "operationalStatus",
        "onboardingStatus",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "Vendor",
      "type": "object"
    },
    "VendorResponse": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Vendor",
          "title": "VendorResponse.data"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "VendorResponse",
      "type": "object"
    },
    "VendorListResponse": {
      "properties": {
        "data": {
          "items": {
            "$ref": "#/definitions/Vendor",
            "title": "VendorListResponse.data.[]"
          },
          "title": "VendorListResponse.data",
          "type": "array"
        },
        "pagination": {
          "$ref": "#/definitions/Pagination",
          "title": "VendorListResponse.pagination"
        }
      },
      "required": [
        "data"
      ],
      "additionalProperties": false,
      "title": "VendorListResponse",
      "type": "object"
    },
    "CreateServiceAreaRequest": {
      "properties": {
        "name": {
          "title": "CreateServiceAreaRequest.name",
          "type": "string"
        },
        "city": {
          "title": "CreateServiceAreaRequest.city",
          "type": "string"
        },
        "state": {
          "title": "CreateServiceAreaRequest.state",
          "type": "string"
        },
        "postalCodes": {
          "items": {
            "title": "CreateServiceAreaRequest.postalCodes.[]",
            "type": "string"
          },
          "title": "CreateServiceAreaRequest.postalCodes",
          "type": "array"
        },
        "center": {
          "$ref": "#/definitions/GeoLocation",
          "title": "CreateServiceAreaRequest.center"
        },
        "radiusKm": {
          "title": "CreateServiceAreaRequest.radiusKm",
          "type": "number"
        },
        "active": {
          "title": "CreateServiceAreaRequest.active",
          "type": "boolean"
        }
      },
      "required": [
        "name",
        "city"
      ],
      "additionalProperties": false,
      "title": "CreateServiceAreaRequest",
      "type": "object"
    },
    "UpdateServiceAreaRequest": {
      "properties": {
        "name": {
          "title": "UpdateServiceAreaRequest.name",
          "type": "string"
        },
        "city": {
          "title": "UpdateServiceAreaRequest.city",
          "type": "string"
        },
        "state": {
          "title": "UpdateServiceAreaRequest.state",
          "type": "string"
        },
        "postalCodes": {
          "items": {
            "title": "UpdateServiceAreaRequest.postalCodes.[]",
            "type": "string"
          },
          "title": "UpdateServiceAreaRequest.postalCodes",
          "type": "array"
        },
        "center": {
          "$ref": "#/definitions/GeoLocation",
          "title": "UpdateServiceAreaRequest.center"
        },
        "radiusKm": {
          "title": "UpdateServiceAreaRequest.radiusKm",
          "type": "number"
        },
        "active": {
          "title": "UpdateServiceAreaRequest.active",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "title": "UpdateServiceAreaRequest",
      "type": "object"
    },
    "ServiceArea": {
      "allOf": [
        {
          "$ref": "#/definitions/CreateServiceAreaRequest"
        },
        {
          "properties": {
            "serviceAreaId": {
              "title": "serviceAreaId",
              "type": "string"
            },
            "vendorId": {
              "title": "vendorId",
              "type": "string"
            },
            "createdAt": {
              "title": "createdAt",
              "type": "string"
            },
            "updatedAt": {
              "title": "updatedAt",
              "type": "string"
            }
          },
          "required": [
            "serviceAreaId",
            "vendorId",
            "createdAt",
            "updatedAt"
          ],
          "additionalProperties": false,
          "type": "object"
        }
      ],
      "title": "ServiceArea"
    },
    "OperatingHoursRequest": {
      "properties": {
        "dayOfWeek": {
          "$ref": "#/definitions/DayOfWeek",
          "title": "OperatingHoursRequest.dayOfWeek"
        },
        "closed": {
          "title": "OperatingHoursRequest.closed",
          "type": "boolean"
        },
        "openTime": {
          "title": "OperatingHoursRequest.openTime",
          "type": "string"
        },
        "closeTime": {
          "title": "OperatingHoursRequest.closeTime",
          "type": "string"
        }
      },
      "required": [
        "dayOfWeek",
        "closed"
      ],
      "additionalProperties": false,
      "title": "OperatingHoursRequest",
      "type": "object"
    },
    "OperatingHours": {
      "allOf": [
        {
          "$ref": "#/definitions/OperatingHoursRequest"
        },
        {
          "properties": {
            "vendorId": {
              "title": "vendorId",
              "type": "string"
            }
          },
          "additionalProperties": false,
          "type": "object"
        }
      ],
      "title": "OperatingHours"
    },
    "UpdateVendorOperatingHoursRequest": {
      "properties": {
        "operatingHours": {
          "items": {
            "$ref": "#/definitions/OperatingHoursRequest",
            "title": "UpdateVendorOperatingHoursRequest.operatingHours.[]"
          },
          "title": "UpdateVendorOperatingHoursRequest.operatingHours",
          "type": "array"
        }
      },
      "required": [
        "operatingHours"
      ],
      "additionalProperties": false,
      "title": "UpdateVendorOperatingHoursRequest",
      "type": "object"
    },
    "CreateStaffRequest": {
      "properties": {
        "userId": {
          "title": "CreateStaffRequest.userId",
          "type": "string"
        },
        "name": {
          "title": "CreateStaffRequest.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "CreateStaffRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "CreateStaffRequest.email",
          "type": "string"
        },
        "role": {
          "title": "CreateStaffRequest.role",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/StaffStatus",
          "title": "CreateStaffRequest.status"
        }
      },
      "required": [
        "name",
        "phoneNumber"
      ],
      "additionalProperties": false,
      "title": "CreateStaffRequest",
      "type": "object"
    },
    "UpdateStaffRequest": {
      "properties": {
        "name": {
          "title": "UpdateStaffRequest.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "UpdateStaffRequest.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "UpdateStaffRequest.email",
          "type": "string"
        },
        "role": {
          "title": "UpdateStaffRequest.role",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/StaffStatus",
          "title": "UpdateStaffRequest.status"
        }
      },
      "additionalProperties": false,
      "title": "UpdateStaffRequest",
      "type": "object"
    },
    "Staff": {
      "properties": {
        "staffId": {
          "title": "Staff.staffId",
          "type": "string"
        },
        "vendorId": {
          "title": "Staff.vendorId",
          "type": "string"
        },
        "userId": {
          "title": "Staff.userId",
          "type": "string"
        },
        "name": {
          "title": "Staff.name",
          "type": "string"
        },
        "phoneNumber": {
          "title": "Staff.phoneNumber",
          "type": "string"
        },
        "email": {
          "title": "Staff.email",
          "type": "string"
        },
        "role": {
          "title": "Staff.role",
          "type": "string"
        },
        "status": {
          "$ref": "#/definitions/StaffStatus",
          "title": "Staff.status"
        },
        "createdAt": {
          "title": "Staff.createdAt",
          "type": "string"
        },
        "updatedAt": {
          "title": "Staff.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "staffId",
        "vendorId",
        "name",
        "status",
        "createdAt",
        "updatedAt"
      ],
      "additionalProperties": false,
      "title": "Staff",
      "type": "object"
    },
    "StaffResponse": {
      "properties": {
        "data": {
          "$ref": "#/definitions/Staff",
          "title": "StaffResponse.data"
        }
      },
      "additionalProperties": false,
      "title": "StaffResponse",
      "type": "object"
    },
    "StaffListResponse": {
      "properties": {
        "data": {
          "items": {
            "$ref": "#/definitions/Staff",
            "title": "StaffListResponse.data.[]"
          },
          "title": "StaffListResponse.data",
          "type": "array"
        },
        "pagination": {
          "$ref": "#/definitions/Pagination",
          "title": "StaffListResponse.pagination"
        }
      },
      "additionalProperties": false,
      "title": "StaffListResponse",
      "type": "object"
    },
    "CapabilityDefinition": {
      "properties": {
        "capabilityId": {
          "title": "CapabilityDefinition.capabilityId",
          "type": "string"
        },
        "category": {
          "$ref": "#/definitions/CapabilityCategory",
          "title": "CapabilityDefinition.category"
        },
        "code": {
          "$ref": "#/definitions/VehicleType",
          "title": "CapabilityDefinition.code"
        },
        "name": {
          "title": "CapabilityDefinition.name",
          "type": "string"
        }
      },
      "required": [
        "capabilityId",
        "category",
        "code",
        "name"
      ],
      "additionalProperties": false,
      "title": "CapabilityDefinition",
      "type": "object"
    },
    "AvailableCapabilities": {
      "properties": {
        "vehicleTypes": {
          "items": {
            "$ref": "#/definitions/CapabilityDefinition",
            "title": "AvailableCapabilities.vehicleTypes.[]"
          },
          "title": "AvailableCapabilities.vehicleTypes",
          "type": "array"
        },
        "catalogSources": {
          "properties": {
            "services": {
              "title": "AvailableCapabilities.catalogSources.services",
              "type": "string"
            },
            "packages": {
              "title": "AvailableCapabilities.catalogSources.packages",
              "type": "string"
            }
          },
          "required": [
            "services",
            "packages"
          ],
          "additionalProperties": false,
          "title": "AvailableCapabilities.catalogSources",
          "type": "object"
        }
      },
      "required": [
        "vehicleTypes",
        "catalogSources"
      ],
      "additionalProperties": false,
      "title": "AvailableCapabilities",
      "type": "object"
    },
    "VendorCapabilities": {
      "properties": {
        "vendorId": {
          "title": "VendorCapabilities.vendorId",
          "type": "string"
        },
        "vehicleTypes": {
          "items": {
            "$ref": "#/definitions/VehicleType",
            "title": "VendorCapabilities.vehicleTypes.[]"
          },
          "title": "VendorCapabilities.vehicleTypes",
          "type": "array"
        },
        "serviceIds": {
          "items": {
            "title": "VendorCapabilities.serviceIds.[]",
            "type": "string"
          },
          "title": "VendorCapabilities.serviceIds",
          "type": "array"
        },
        "packageIds": {
          "items": {
            "title": "VendorCapabilities.packageIds.[]",
            "type": "string"
          },
          "title": "VendorCapabilities.packageIds",
          "type": "array"
        },
        "updatedAt": {
          "title": "VendorCapabilities.updatedAt",
          "type": "string"
        }
      },
      "required": [
        "vendorId",
        "vehicleTypes",
        "serviceIds",
        "packageIds"
      ],
      "additionalProperties": false,
      "title": "VendorCapabilities",
      "type": "object"
    },
    "UpdateVendorCapabilitiesRequest": {
      "properties": {
        "vehicleTypes": {
          "items": {
            "$ref": "#/definitions/VehicleType",
            "title": "UpdateVendorCapabilitiesRequest.vehicleTypes.[]"
          },
          "title": "UpdateVendorCapabilitiesRequest.vehicleTypes",
          "type": "array"
        },
        "serviceIds": {
          "items": {
            "title": "UpdateVendorCapabilitiesRequest.serviceIds.[]",
            "type": "string"
          },
          "title": "UpdateVendorCapabilitiesRequest.serviceIds",
          "type": "array"
        },
        "packageIds": {
          "items": {
            "title": "UpdateVendorCapabilitiesRequest.packageIds.[]",
            "type": "string"
          },
          "title": "UpdateVendorCapabilitiesRequest.packageIds",
          "type": "array"
        }
      },
      "required": [
        "vehicleTypes",
        "serviceIds",
        "packageIds"
      ],
      "additionalProperties": false,
      "title": "UpdateVendorCapabilitiesRequest",
      "type": "object"
    },
    "Pagination": {
      "properties": {
        "nextCursor": {
          "title": "Pagination.nextCursor",
          "nullable": true,
          "type": "string"
        },
        "hasMore": {
          "title": "Pagination.hasMore",
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "title": "Pagination",
      "type": "object"
    },
    "Error": {
      "properties": {
        "code": {
          "title": "Error.code",
          "type": "string"
        },
        "message": {
          "title": "Error.message",
          "type": "string"
        },
        "correlationId": {
          "title": "Error.correlationId",
          "type": "string"
        },
        "details": {
          "items": {
            "additionalProperties": {},
            "title": "Error.details.[]",
            "type": "object"
          },
          "title": "Error.details",
          "type": "array"
        }
      },
      "required": [
        "code",
        "message"
      ],
      "additionalProperties": false,
      "title": "Error",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};