// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Device Service API",
    "version": "1.0.0",
    "description": "RESTful API for managing devices, device-user mappings, organization devices, and recommendations"
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "health",
        "description": "",
        "operationId": "health.get./health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/register": {
      "post": {
        "summary": "deviceRegister",
        "description": "",
        "operationId": "deviceRegister.post.devices/register",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/error-notification": {
      "post": {
        "summary": "errorNotification",
        "description": "",
        "operationId": "errorNotification.post.devices/error-notification",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/{deviceId}": {
      "get": {
        "summary": "deviceGet",
        "description": "",
        "operationId": "deviceGet.get.devices/{deviceId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "deviceUpdate",
        "description": "",
        "operationId": "deviceUpdate.put.devices/{deviceId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "deviceDelete",
        "description": "",
        "operationId": "deviceDelete.delete.devices/{deviceId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/delete-multiple": {
      "post": {
        "summary": "deviceDeleteMultiple",
        "description": "",
        "operationId": "deviceDeleteMultiple.post.devices/delete-multiple",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/user/delete": {
      "post": {
        "summary": "deviceUserDelete",
        "description": "",
        "operationId": "deviceUserDelete.post.devices/user/delete",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/user/register": {
      "post": {
        "summary": "deviceUserRegister",
        "description": "",
        "operationId": "deviceUserRegister.post.devices/user/register",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/list": {
      "post": {
        "summary": "deviceList",
        "description": "",
        "operationId": "deviceList.post.devices/list",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/search": {
      "post": {
        "summary": "deviceSearch",
        "description": "",
        "operationId": "deviceSearch.post.devices/search",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/org/manage": {
      "post": {
        "summary": "orgDeviceManage",
        "description": "",
        "operationId": "orgDeviceManage.post.devices/org/manage",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/recommendations/add": {
      "post": {
        "summary": "deviceRecommendationAdd",
        "description": "",
        "operationId": "deviceRecommendationAdd.post.devices/recommendations/add",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/recommendations/remove": {
      "post": {
        "summary": "deviceRecommendationRemove",
        "description": "",
        "operationId": "deviceRecommendationRemove.post.devices/recommendations/remove",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/global/register": {
      "post": {
        "summary": "deviceGlobalRegister",
        "description": "",
        "operationId": "deviceGlobalRegister.post.devices/global/register",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/{deviceId}/users/{userId}": {
      "post": {
        "summary": "deviceUserAssign",
        "description": "",
        "operationId": "deviceUserAssign.post.devices/{deviceId}/users/{userId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "deviceUserRemove",
        "description": "",
        "operationId": "deviceUserRemove.delete.devices/{deviceId}/users/{userId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/{deviceId}/users": {
      "get": {
        "summary": "deviceUserList",
        "description": "",
        "operationId": "deviceUserList.get.devices/{deviceId}/users",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/organizations": {
      "post": {
        "summary": "deviceOrgAssign",
        "description": "",
        "operationId": "deviceOrgAssign.post.devices/organizations",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/remove/organizations": {
      "post": {
        "summary": "deviceOrgRemove",
        "description": "",
        "operationId": "deviceOrgRemove.post.devices/remove/organizations",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/{deviceId}/organizations": {
      "get": {
        "summary": "deviceOrgList",
        "description": "",
        "operationId": "deviceOrgList.get.devices/{deviceId}/organizations",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/org/{organizationId}": {
      "get": {
        "summary": "getOrganizationDevice",
        "description": "",
        "operationId": "getOrganizationDevice.get.devices/org/{organizationId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/{deviceId}/metadata": {
      "put": {
        "summary": "deviceMetadataUpdate",
        "description": "",
        "operationId": "deviceMetadataUpdate.put.devices/{deviceId}/metadata",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/reading-timestamp/{userId}/{configDeviceId}/update": {
      "put": {
        "summary": "deviceReadingTimestampUpdate",
        "description": "",
        "operationId": "deviceReadingTimestampUpdate.put.devices/reading-timestamp/{userId}/{configDeviceId}/update",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "configDeviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/devices/{deviceId}/files": {
      "post": {
        "summary": "deviceFileUpload",
        "description": "",
        "operationId": "deviceFileUpload.post.devices/{deviceId}/files",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "deviceId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https",
    "http"
  ]
};