// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Organization Service API",
    "version": "1.0.0",
    "description": "RESTful API for managing organizations, users, devices, metadata, and files"
  },
  "paths": {
    "/organization": {
      "post": {
        "summary": "createOrganization",
        "description": "",
        "operationId": "createOrganization.post.organization",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/health": {
      "get": {
        "summary": "health",
        "description": "",
        "operationId": "health.get./health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/{organizationId}": {
      "get": {
        "summary": "getOrganization",
        "description": "",
        "operationId": "getOrganization.get.organization/{organizationId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "updateOrganization",
        "description": "",
        "operationId": "updateOrganization.put.organization/{organizationId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "deleteOrganization",
        "description": "",
        "operationId": "deleteOrganization.delete.organization/{organizationId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/list": {
      "post": {
        "summary": "organizationList",
        "description": "",
        "operationId": "organizationList.post.organization/list",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/link-unlink": {
      "post": {
        "summary": "linkUnlinkOrganization",
        "description": "",
        "operationId": "linkUnlinkOrganization.post.organization/link-unlink",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/status": {
      "post": {
        "summary": "setOrgStatus",
        "description": "",
        "operationId": "setOrgStatus.post.organization/status",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/count": {
      "post": {
        "summary": "getOrganizationCount",
        "description": "",
        "operationId": "getOrganizationCount.post.organization/count",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/linked": {
      "post": {
        "summary": "getLinkedOrganizations",
        "description": "",
        "operationId": "getLinkedOrganizations.post.organization/linked",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/{organizationId}/metadata": {
      "put": {
        "summary": "updateOrganizationMetadata",
        "description": "",
        "operationId": "updateOrganizationMetadata.put.organization/{organizationId}/metadata",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/metadata": {
      "get": {
        "summary": "getOrganizationMetadata",
        "description": "",
        "operationId": "getOrganizationMetadata.get.organization/metadata",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/get-external-tenant": {
      "post": {
        "summary": "getExternalTenant",
        "description": "",
        "operationId": "getExternalTenant.post.organization/get-external-tenant",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/organization/{organizationId}/files": {
      "get": {
        "summary": "listOrganizationFiles",
        "description": "",
        "operationId": "listOrganizationFiles.get.organization/{organizationId}/files",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "organizationId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/stg",
  "schemes": [
    "https",
    "http"
  ],
  "openapi": "3.0.0",
  "components": {
    "schemas": {
      "CreateOrganizationRequest": {
        "type": "object",
        "description": "Creates an organization. Legacy nested payloads are accepted and normalized server-side.",
        "required": [
          "name"
        ],
        "properties": {
          "organizationId": {
            "type": "string",
            "description": "Optional organization ID; generated if omitted"
          },
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 255
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "phone": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "ACTIVE",
              "INACTIVE",
              "SUSPENDED"
            ],
            "default": "ACTIVE"
          },
          "organizationType": {
            "type": "string"
          },
          "website": {
            "type": "string"
          },
          "taxId": {
            "type": "string"
          },
          "registrationNumber": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "industry": {
            "type": "string"
          },
          "supportedVitals": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "size": {
            "type": "string",
            "enum": [
              "SMALL",
              "MEDIUM",
              "LARGE"
            ]
          }
        }
      },
      "Organization": {
        "type": "object",
        "required": [
          "pk",
          "sk",
          "organizationId",
          "name",
          "status",
          "createdDate",
          "modifiedDate",
          "itemType"
        ],
        "properties": {
          "pk": {
            "type": "string"
          },
          "sk": {
            "type": "string"
          },
          "organizationId": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "phone": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "ACTIVE",
              "INACTIVE",
              "SUSPENDED"
            ]
          },
          "organizationType": {
            "type": "string"
          },
          "createdDate": {
            "type": "number"
          },
          "modifiedDate": {
            "type": "number"
          },
          "deleted": {
            "type": "boolean"
          },
          "itemType": {
            "type": "string",
            "enum": [
              "ORG_DETAILS"
            ]
          },
          "website": {
            "type": "string"
          },
          "taxId": {
            "type": "string"
          },
          "registrationNumber": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "industry": {
            "type": "string"
          },
          "supportedVitals": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": true
            }
          },
          "size": {
            "type": "string",
            "enum": [
              "SMALL",
              "MEDIUM",
              "LARGE"
            ]
          }
        }
      },
      "CreateOrganizationResponse": {
        "allOf": [
          {
            "$ref": "#/components/schemas/SuccessResponse"
          },
          {
            "type": "object",
            "properties": {
              "data": {
                "$ref": "#/components/schemas/Organization"
              }
            }
          }
        ]
      },
      "SuccessResponse": {
        "type": "object",
        "properties": {
          "data": {
            "description": "Response data (can be object, array, or null)",
            "oneOf": [
              {
                "type": "object"
              },
              {
                "type": "array"
              },
              {
                "type": "null"
              }
            ]
          },
          "meta": {
            "type": "object",
            "description": "Additional metadata (optional)",
            "additionalProperties": true
          },
          "links": {
            "type": "object",
            "description": "Related resource links (optional)",
            "additionalProperties": {
              "type": "string"
            }
          },
          "requestId": {
            "type": "string",
            "description": "Request correlation ID",
            "example": "req-123"
          },
          "message": {
            "type": "string",
            "description": "Success message (optional)",
            "example": "Operation completed successfully"
          }
        }
      },
      "ProblemDetails": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string"
          },
          "status": {
            "type": "integer"
          },
          "detail": {
            "type": "string"
          },
          "instance": {
            "type": "string",
            "nullable": true
          },
          "code": {
            "type": "string"
          },
          "correlationId": {
            "type": "string"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "field": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
};