// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Domain API",
    "version": "1"
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "healthCheck",
        "description": "",
        "operationId": "healthCheck.get.health",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/order/create": {
      "post": {
        "summary": "createOrgOrder",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "createOrgOrder.post.order/create",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateOrgOrderRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/CreateOrgOrderResponse"
            }
          },
          "202": {
            "description": "Accepted (payment pending)",
            "schema": {
              "$ref": "#/definitions/CreateOrgOrderResponse"
            }
          }
        }
      }
    },
    "/order/review": {
      "post": {
        "summary": "getOrder",
        "description": "",
        "operationId": "getOrder.post.order/review",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/order/{orderId}": {
      "get": {
        "summary": "getOrderById",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "getOrderById.get.order/{orderId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "orderId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "orgId",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Order fetched"
          }
        }
      }
    },
    "/orders": {
      "get": {
        "summary": "listOrders",
        "description": "",
        "operationId": "listOrders.get.orders",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/order/{orderId}/payments": {
      "post": {
        "summary": "requestPayment",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "requestPayment.post.order/{orderId}/payments",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "orderId",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "0",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Payment order created",
            "schema": {
              "$ref": "#/definitions/CreateOrgOrderResponse"
            }
          }
        }
      }
    },
    "/internal/payments/events": {
      "post": {
        "summary": "paymentEvents",
        "description": "",
        "tags": [
          "Payments"
        ],
        "operationId": "paymentEvents.post.internal/payments/events",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PaymentEventWebhook"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/order/cancel": {
      "post": {
        "summary": "cancelOrder",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "cancelOrder.post.order/cancel",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CancelOrderRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order cancelled",
            "schema": {
              "$ref": "#/definitions/CancelOrderResponse"
            }
          }
        }
      }
    },
    "/order/refund": {
      "post": {
        "summary": "refundPayment",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "refundPayment.post.order/refund",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/RefundOrderRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Refund processed",
            "schema": {
              "$ref": "#/definitions/RefundOrderResponse"
            }
          }
        }
      }
    },
    "/pharmacy/order": {
      "post": {
        "summary": "createPharmacyOrder",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "createPharmacyOrder.post.pharmacy/order",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateOrgOrderRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/CreateOrgOrderResponse"
            }
          }
        }
      }
    },
    "/order/complete": {
      "post": {
        "summary": "markPaid",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "markPaid.post.order/complete",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/MarkPaidRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order marked as paid",
            "schema": {
              "$ref": "#/definitions/MarkPaidResponse"
            }
          }
        }
      }
    },
    "/order/invoice": {
      "post": {
        "summary": "generateInvoice",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "generateInvoice.post.order/invoice",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GenerateInvoiceRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Invoice generated",
            "schema": {
              "$ref": "#/definitions/GenerateInvoiceResponse"
            }
          }
        }
      }
    },
    "/order/payments/{paymentId}/status": {
      "get": {
        "summary": "getPaymentStatus",
        "description": "",
        "tags": [
          "Orders"
        ],
        "operationId": "getPaymentStatus.get.order/payments/{paymentId}/status",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "paymentId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Invoice status retrieved",
            "schema": {
              "$ref": "#/definitions/GenerateInvoiceResponse"
            }
          },
          "404": {
            "description": "Invoice not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "HealthCheckResponse": {
      "properties": {
        "status": {
          "title": "HealthCheckResponse.status",
          "type": "string"
        }
      },
      "required": [
        "status"
      ],
      "additionalProperties": false,
      "title": "HealthCheckResponse",
      "type": "object"
    },
    "orderMeta": {
      "properties": {
        "productId": {
          "title": "orderMeta.productId",
          "type": "string"
        },
        "productType": {
          "enum": [
            "package",
            "addon"
          ],
          "title": "orderMeta.productType",
          "type": "string"
        },
        "amount": {
          "title": "orderMeta.amount",
          "type": "number"
        }
      },
      "required": [
        "productType",
        "amount"
      ],
      "additionalProperties": false,
      "title": "orderMeta",
      "type": "object"
    },
    "CreateOrgOrderRequest": {
      "properties": {
        "orgId": {
          "title": "CreateOrgOrderRequest.orgId",
          "type": "string"
        },
        "userId": {
          "title": "CreateOrgOrderRequest.userId",
          "type": "string"
        },
        "idempotencyKey": {
          "title": "CreateOrgOrderRequest.idempotencyKey",
          "type": "string"
        },
        "meta": {
          "$ref": "#/definitions/orderMeta",
          "title": "CreateOrgOrderRequest.meta"
        },
        "platform": {
          "enum": [
            "web",
            "mobile"
          ],
          "title": "CreateOrgOrderRequest.platform",
          "type": "string"
        },
        "transactionType": {
          "enum": [
            "paymentgateway",
            "cash"
          ],
          "title": "CreateOrgOrderRequest.transactionType",
          "type": "string"
        }
      },
      "required": [
        "orgId",
        "userId",
        "meta",
        "platform",
        "transactionType"
      ],
      "additionalProperties": false,
      "title": "CreateOrgOrderRequest",
      "type": "object"
    },
    "PaymentProviderMeta": {
      "properties": {
        "orderId": {
          "title": "PaymentProviderMeta.orderId",
          "type": "string"
        },
        "orgId": {
          "title": "PaymentProviderMeta.orgId",
          "type": "string"
        },
        "customerId": {
          "title": "PaymentProviderMeta.customerId",
          "type": "string"
        },
        "amount": {
          "title": "PaymentProviderMeta.amount",
          "type": "number"
        },
        "currency": {
          "title": "PaymentProviderMeta.currency",
          "enum": [
            "INR"
          ],
          "type": "string"
        },
        "receipt": {
          "title": "PaymentProviderMeta.receipt",
          "type": "string"
        },
        "paymentProviderType": {
          "title": "PaymentProviderMeta.paymentProviderType",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "title": "PaymentProviderMeta",
      "type": "object"
    },
    "CreateOrgOrderResponse": {
      "properties": {
        "orderId": {
          "title": "CreateOrgOrderResponse.orderId",
          "type": "string"
        },
        "status": {
          "enum": [
            "created",
            "failed"
          ],
          "title": "CreateOrgOrderResponse.status",
          "type": "string"
        },
        "amount": {
          "title": "CreateOrgOrderResponse.amount",
          "type": "number"
        },
        "currency": {
          "title": "CreateOrgOrderResponse.currency",
          "enum": [
            "INR"
          ],
          "type": "string"
        },
        "paymentProvider": {
          "$ref": "#/definitions/PaymentProviderMeta",
          "title": "CreateOrgOrderResponse.paymentProvider"
        },
        "paymentPending": {
          "title": "CreateOrgOrderResponse.paymentPending",
          "type": "boolean"
        },
        "message": {
          "title": "CreateOrgOrderResponse.message",
          "type": "string"
        }
      },
      "required": [
        "orderId",
        "status",
        "amount",
        "currency"
      ],
      "additionalProperties": false,
      "title": "CreateOrgOrderResponse",
      "type": "object"
    },
    "PaymentEventWebhook": {
      "properties": {
        "type": {
          "enum": [
            "PaymentSucceeded",
            "PaymentFailed"
          ],
          "title": "PaymentEventWebhook.type",
          "type": "string"
        },
        "orderId": {
          "title": "PaymentEventWebhook.orderId",
          "type": "string"
        },
        "orgId": {
          "title": "PaymentEventWebhook.orgId",
          "type": "string"
        },
        "paymentId": {
          "title": "PaymentEventWebhook.paymentId",
          "type": "string"
        },
        "reason": {
          "title": "PaymentEventWebhook.reason",
          "type": "string"
        }
      },
      "required": [
        "type",
        "orderId",
        "orgId"
      ],
      "additionalProperties": false,
      "title": "PaymentEventWebhook",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};