/**
 * Internal DTO Types
 * These match the User model from user-service
 */

export interface User {
  pk: string;
  sk: string;
  acceptedAppForms?: Array<{
    acceptedDate: number;
    docId: string;
    versionId: string;
  }>;
  accountStatus?: string;
  additionalEmailIDs?: string[];
  additionalPhoneNumbers?: string[];
  address?: string;
  appleHealthLastSync?: string;
  appName?: string;
  assignRoomNo?: string;
  bio?: string;
  bloodGroup?: string;
  changePassword?: boolean;
  city?: string;
  cloudOpt?: string;
  country?: string;
  countryCode?: string;
  createdDate: number;
  dateOfBirth?: string;
  department?: string;
  emailAddress: string;
  emailVerified?: boolean;
  emergencyContact?: Record<string, unknown>;
  ethnicity?: string;
  experienceInYears?: string;
  firstLoggedIn?: number;
  firstName?: string;
  fullName?: string;
  gender?: string;
  googleFitLastSync?: string;
  heightInCm?: string;
  heightInFeet?: string;
  insuranceDetails?: Record<string, unknown>;
  inviteCode?: string;
  invitedBy?: string;
  invitedID?: string;
  isActive?: boolean;
  isLoggedIn?: boolean;
  isRegisteredCompletely?: boolean;
  isRpmUser?: boolean;
  isTaskCompleted?: boolean;
  language?: string;
  lastAppointment?: string;
  lastName?: string;
  lastRequestTime?: number;
  lastUsedAccount?: number;
  licenseNumber?: string;
  locale?: string;
  logoutAt?: number;
  logoutRequired?: boolean;
  maritalStatus?: string;
  medicalHistory?: {
    allergies?: string[];
    chronicDiseases?: string[];
    symptoms?: string[];
  };
  middleName?: string;
  modifiedDate: number;
  mrn?: string;
  namePrefix?: string;
  organizationID: string;
  phoneCode?: string;
  phoneLocale?: string;
  phoneNumber: string;
  phoneVerified?: boolean;
  position?: string;
  postalCode?: string;
  prevLastUsedAccount?: number;
  profilePic?: string;
  referred?: Array<{
    id: string;
    name: string;
    profilePic: string;
  }>;
  region?: string;
  reporterEmail?: string;
  reporterId?: string;
  reporterName?: string;
  reporterProfilePic?: string;
  specialty?: string;
  srcRegisEntity?: string;
  state?: string;
  stateCode?: string;
  street?: string;
  userCat?: string[];
  userID: string;
  userTimeZone?: string;
  userType?: string;
  weightInKG?: string;
  weightInLbs?: string;
  zip?: string;
  itemType?: string;
}

/**
 * UserDTO type alias for User
 * Used in adapters for clarity
 */
export type UserDTO = User;

/**
 * ListUserOrganizationsDTO DTO Type
 * Auto-generated by FHIR Mapper Generator
 * @generated
 * 
 * This type represents the response from user-service /user/{id}/organizations endpoint
 */

export interface UserOrganization {
}

export type ListUserOrganizationsDTO = UserOrganization[];

/**
 * ListUserFilesDTO DTO Type
 * Auto-generated by FHIR Mapper Generator
 * @generated
 * 
 * This type represents the response from user-service /user/{id}/files endpoint
 */

export interface UserFile {
}

export type ListUserFilesDTO = UserFile[];


