import Handlebars from 'handlebars';
import { readFileSync } from 'fs';
import { join } from 'path';
import type {
  MappingConfig,
  FieldMapping,
} from './config-parser.js';

export class CodeGenerator {
  private templates: Map<string, HandlebarsTemplateDelegate> = new Map();
  private templateDir = '';

  constructor(templateDir?: string) {
    // Try multiple possible locations for templates
    const possiblePaths = [
      templateDir,
      join(process.cwd(), 'tools/fhir-mapper-generator/src/templates'),
      join(process.cwd(), 'src/templates'),
    ].filter(Boolean) as string[];
    
    // Find the first existing path
    for (const path of possiblePaths) {
      try {
        const testFile = join(path, 'service-client.hbs');
        readFileSync(testFile, 'utf-8');
        this.templateDir = path;
        break;
      } catch {
        continue;
      }
    }

    if (!this.templateDir) {
      throw new Error(
        'Could not find templates directory. Please specify templateDir in constructor or ensure templates are in tools/fhir-mapper-generator/src/templates'
      );
    }
    
    this.loadTemplates();
    this.registerHelpers();
  }

  private loadTemplates() {
    const templateFiles = [
      'service-client.hbs',
      'handler.hbs',
      'adapter.hbs',
    ];

    for (const file of templateFiles) {
      try {
        const content = readFileSync(join(this.templateDir, file), 'utf-8');
        this.templates.set(file, Handlebars.compile(content));
      } catch (error) {
        console.warn(`Failed to load template ${file}:`, error);
      }
    }
  }

  private registerHelpers() {
    // camelCase: first letter lowercase
    Handlebars.registerHelper('camelCase', (str: string) => {
      if (!str) return '';
      return str.charAt(0).toLowerCase() + str.slice(1);
    });

    // PascalCase: first letter uppercase
    Handlebars.registerHelper('pascalCase', (str: string) => {
      if (!str) return '';
      return str.charAt(0).toUpperCase() + str.slice(1);
    });

    // UPPER_SNAKE_CASE
    Handlebars.registerHelper('upperSnakeCase', (str: string) => {
      if (!str) return '';
      return str
        .replace(/([A-Z])/g, '_$1')
        .toUpperCase()
        .replace(/^_/, '');
    });

    // kebab-case
    Handlebars.registerHelper('kebabCase', (str: string) => {
      if (!str) return '';
      return str
        .replace(/([A-Z])/g, '-$1')
        .toLowerCase()
        .replace(/^-/, '');
    });
  }

  /**
   * Generate service client code
   */
  generateServiceClient(config: MappingConfig): string {
    const template = this.templates.get('service-client.hbs');
    if (!template) {
      throw new Error('Service client template not found');
    }

    const serviceName = config.service.name;
    const resourceType = config.fhirResource.resourceType;
    const responseType = config.service.responseType || `${resourceType}DTO`;

    // Build parameters for the get method
    const queryParams = config.service.queryParameters || [];
    const parameters: string[] = [];
    const queryParamsList: string[] = [];

    // ID parameter
    const idParam = this.extractIdFromEndpoint(config.service.apiEndpoint);
    parameters.push(`${idParam}: string`);

    // Query parameters
    queryParams.forEach((param) => {
      const paramName = param.optional ? `${param.name}?: ${param.type}` : `${param.name}: ${param.type}`;
      parameters.push(paramName);
      queryParamsList.push(param.name);
    });

    const context = {
      serviceName,
      ServiceName: this.pascalCase(serviceName),
      SERVICE_NAME: this.upperSnakeCase(serviceName),
      resourceName: this.camelCase(resourceType),
      Resource: resourceType,
      resource: resourceType.toLowerCase(),
      responseType,
      ResponseType: responseType,
      apiEndpoint: config.service.apiEndpoint,
      defaultPort: '3000',
      parameters: parameters.join(', '),
      queryParams: queryParams.map((p) => ({
        name: p.name,
        variableName: p.name,
      })),
      idParameter: idParam,
      autoGenerated: true,
    };

    return template(context);
  }

  /**
   * Generate handler code
   */
  generateHandler(config: MappingConfig): string {
    const template = this.templates.get('handler.hbs');
    if (!template) {
      throw new Error('Handler template not found');
    }

    const serviceName = config.service.name;
    const resourceType = config.fhirResource.resourceType;
    const responseType = config.service.responseType || `${resourceType}DTO`;
    const queryParams = config.service.queryParameters || [];
    const idParam = this.extractIdFromEndpoint(config.service.apiEndpoint);

    const context = {
      serviceName,
      serviceNameCamel: this.toCamelCase(serviceName),
      ServiceName: this.pascalCase(serviceName),
      Resource: resourceType,
      resource: resourceType.toLowerCase(),
      RESOURCE: resourceType.toUpperCase(),
      id: idParam,
      idParam,
      resourceId: `${this.camelCase(resourceType)}Id`,
      dtoVariable: this.camelCase(responseType),
      resourceVariable: this.camelCase(resourceType),
      hasQueryParams: queryParams.length > 0,
      queryParams: queryParams.map((p) => ({
        name: p.name,
        variableName: p.name,
      })),
      requiredQueryParams: queryParams.filter((p) => !p.optional),
      hasRequiredQueryParams: queryParams.some((p) => !p.optional),
      queryParamsList: queryParams.map((p) => p.name).join(', '),
      queryParamsCallList: queryParams.map((p) => p.name).join(', '),
      queryParamsLogList: queryParams.map((p) => `${p.name}`).join(', '),
      adapterParams: false,
      adapterParamsList: '',
    };

    return template(context);
  }

  /**
   * Generate adapter code
   */
  generateAdapter(config: MappingConfig): string {
    const template = this.templates.get('adapter.hbs');
    if (!template) {
      throw new Error('Adapter template not found');
    }

    const resourceType = config.fhirResource.resourceType;
    const dtoType = config.service.responseType || `${resourceType}DTO`;
    const idField = this.inferIdField(config.mappings);

    // Collect utility functions used
    const utilityFunctions = new Set<string>();
    const utilityImports: Record<string, string[]> = {};

    config.mappings.forEach((mapping) => {
      if (mapping.utilityFunctions) {
        mapping.utilityFunctions.forEach((func) => {
          utilityFunctions.add(func);
          // Determine which utility file
          if (func.includes('CodeableConcept') || func.includes('Coding')) {
            if (!utilityImports.coding) utilityImports.coding = [];
            utilityImports.coding.push(func);
          } else if (func.includes('Reference')) {
            if (!utilityImports.reference) utilityImports.reference = [];
            utilityImports.reference.push(func);
          } else if (func.includes('Date') || func.includes('DateTime')) {
            if (!utilityImports.date) utilityImports.date = [];
            utilityImports.date.push(func);
          }
        });
      }
    });

    // Add getCurrentFhirDateTime if not already added
    if (!utilityImports.date) utilityImports.date = [];
    if (!utilityImports.date.includes('getCurrentFhirDateTime')) {
      utilityImports.date.push('getCurrentFhirDateTime');
    }

    // Build mappings with transformations
    const processedMappings = config.mappings.map((mapping) => {
      const variableName = this.generateVariableName(mapping.target);
      const transformation = mapping.transformation || `dto.${mapping.source}`;

      return {
        ...mapping,
        variableName,
        transformation,
        type: this.inferType(mapping.target),
      };
    });

    // Build resource fields
    const resourceFields = processedMappings.map((mapping) => ({
      name: mapping.target.split('[')[0], // Remove array indices
      variableName: mapping.variableName,
      optional: mapping.optional !== false,
      isArray: mapping.isArray || false,
    }));

    // Build custom functions
    const customFunctions = (config.customTransformations || []).map((trans) => ({
      ...trans,
      parameters: this.formatParameters(trans.parameters || []),
      code: trans.code,
    }));

    const context = {
      Resource: resourceType,
      resource: resourceType.toLowerCase(),
      DTOType: dtoType,
      idField,
      mappings: processedMappings,
      resourceFields,
      utilityImports,
      hasCommonTypes: resourceFields.some((f) =>
        ['HumanName', 'ContactPoint', 'Address', 'Identifier'].includes(f.name)
      ),
      commonTypesList: this.getCommonTypes(resourceFields),
      hasCustomFunctions: customFunctions.length > 0,
      customFunctions,
      adapterParams: false,
      adapterParamsSignature: '',
      adapterParamsList: '',
      autoGenerated: true,
    };

    return template(context);
  }

  // Helper methods
  private extractIdFromEndpoint(endpoint: string): string {
    const match = endpoint.match(/\{(\w+)\}/);
    return match ? match[1] : 'id';
  }

  private inferIdField(mappings: FieldMapping[]): string {
    const idMapping = mappings.find((m) => m.target === 'id');
    return idMapping ? idMapping.source : 'id';
  }

  private generateVariableName(target: string): string {
    const baseName = target.split('[')[0].split('.')[0];
    return this.camelCase(baseName);
  }

  private inferType(target: string): string {
    // Simplified type inference - can be enhanced
    if (target.includes('name')) return 'HumanName';
    if (target.includes('telecom')) return 'ContactPoint';
    if (target.includes('address')) return 'Address';
    if (target.includes('identifier')) return 'Identifier';
    if (target.includes('code')) return 'CodeableConcept';
    if (target.includes('Reference')) return 'Reference';
    return 'unknown';
  }

  private formatParameters(
    parameters: Array<{ name: string; type: string }>
  ): string {
    return parameters.map((p) => `${p.name}: ${p.type}`).join(', ');
  }

  private getCommonTypes(resourceFields: Array<{ name: string }>): string {
    const commonTypes = new Set<string>();
    resourceFields.forEach((field) => {
      if (['HumanName', 'ContactPoint', 'Address', 'Identifier'].includes(field.name)) {
        commonTypes.add(field.name);
      }
    });
    return Array.from(commonTypes).join(', ');
  }

  private camelCase(str: string): string {
    return str.charAt(0).toLowerCase() + str.slice(1);
  }

  private toCamelCase(str: string): string {
    // Convert kebab-case or snake_case to camelCase
    return str
      .split(/[-_]/)
      .map((word, index) => {
        if (index === 0) {
          return word.toLowerCase();
        }
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
      })
      .join('');
  }

  private pascalCase(str: string): string {
    // Handle kebab-case and snake_case
    return str
      .split(/[-_]/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }

  private upperSnakeCase(str: string): string {
    return str
      .replace(/([A-Z])/g, '_$1')
      .toUpperCase()
      .replace(/^_/, '')
      .replace(/-/g, '_');
  }
}

