/**
 * DTO Type Generator
 * Generates TypeScript DTO interfaces for internal types
 */

import Handlebars from 'handlebars';
import { readFileSync } from 'fs';
import { join } from 'path';
import type { MappingConfig } from './config-parser.js';

export class DTOGenerator {
  private template: HandlebarsTemplateDelegate | null = null;
  private templateDir: string;

  constructor(templateDir: string) {
    this.templateDir = templateDir;
    this.loadTemplate();
  }

  private loadTemplate() {
    try {
      const content = readFileSync(join(this.templateDir, 'dto-type.hbs'), 'utf-8');
      this.template = Handlebars.compile(content);
    } catch (error) {
      console.warn('Failed to load DTO template:', error);
    }
  }

  /**
   * Generate DTO type code
   */
  generate(config: MappingConfig): string {
    if (!this.template) {
      throw new Error('DTO template not loaded');
    }

    const dtoType = config.service.responseType || `${config.fhirResource.resourceType}DTO`;
    const resourceType = config.fhirResource.resourceType;
    const serviceName = config.service.name;
    
    // Infer if it's an array type
    const isArray = resourceType.startsWith('List') || resourceType.includes('Array');
    
    // Extract item type
    let itemType = isArray 
      ? resourceType.replace(/^List/, '').replace(/Array$/, '')
      : dtoType.replace(/DTO$/, '');
    
    // Handle special cases
    if (itemType === 'UserOrganizations') itemType = 'UserOrganization';
    if (itemType === 'UserFiles') itemType = 'UserFile';
    
    // Infer fields from mappings or use defaults
    const fields = this.inferFields(config, isArray);

    return this.template({
      DTOType: dtoType,
      serviceName,
      endpointName: config.service.apiEndpoint,
      isArray,
      itemType,
      fields,
      autoGenerated: true,
    });
  }

  /**
   * Infer DTO fields from config
   */
  private inferFields(config: MappingConfig, isArray: boolean): Array<{
    name: string;
    type: string;
    required: boolean;
    description: string;
  }> {
    // If mappings exist, use them
    if (config.mappings && config.mappings.length > 0) {
      return config.mappings
        .filter(m => m.source !== 'userId' || !isArray) // Filter out userId for array items
        .map((m) => ({
          name: m.source,
          type: this.inferTypeScriptType(m.source),
          required: !m.optional,
          description: m.description || `${m.source} field`,
        }));
    }

    // Default fields based on resource type
    const resourceType = config.fhirResource.resourceType.toLowerCase();
    
    if (resourceType.includes('userorganization') || resourceType.includes('organization')) {
      return [
        { name: 'userId', type: 'string', required: true, description: 'User ID' },
        { name: 'organizationId', type: 'string', required: true, description: 'Organization ID' },
        { name: 'assignedAt', type: 'string', required: false, description: 'Assignment timestamp' },
      ];
    }
    
    if (resourceType.includes('userfile') || resourceType.includes('file')) {
      return [
        { name: 'userId', type: 'string', required: true, description: 'User ID' },
        { name: 'fileId', type: 'string', required: true, description: 'File ID' },
        { name: 'fileName', type: 'string', required: true, description: 'File name' },
        { name: 's3Key', type: 'string', required: false, description: 'S3 object key' },
        { name: 'uploadedAt', type: 'string', required: false, description: 'Upload timestamp' },
      ];
    }

    // Generic default
    return [
      { name: 'id', type: 'string', required: true, description: 'Resource ID' },
    ];
  }

  /**
   * Infer TypeScript type from field name
   */
  private inferTypeScriptType(fieldName: string): string {
    const lower = fieldName.toLowerCase();
    
    if (lower.includes('id')) return 'string';
    if (lower.includes('date') || lower.includes('time') || lower.includes('at')) return 'string';
    if (lower.includes('count') || lower.includes('number')) return 'number';
    if (lower.includes('is') || lower.includes('has')) return 'boolean';
    if (lower.includes('list') || lower.includes('array')) return 'unknown[]';
    
    return 'string';
  }
}

