/**
 * FHIR Model Generator
 * Generates FHIR R4 resource model interfaces
 */

import Handlebars from 'handlebars';
import { readFileSync } from 'fs';
import { join } from 'path';
import type { MappingConfig } from './config-parser.js';

export class FhirModelGenerator {
  private template: HandlebarsTemplateDelegate | null = null;
  private templateDir: string;

  constructor(templateDir: string) {
    this.templateDir = templateDir;
    this.loadTemplate();
  }

  private loadTemplate() {
    try {
      const content = readFileSync(join(this.templateDir, 'fhir-model.hbs'), 'utf-8');
      this.template = Handlebars.compile(content);
    } catch (error) {
      console.warn('Failed to load FHIR model template:', error);
    }
  }

  /**
   * Generate FHIR model code
   */
  generate(config: MappingConfig): string {
    if (!this.template) {
      throw new Error('FHIR model template not loaded');
    }

    const resourceType = config.fhirResource.resourceType;
    const fields = this.inferFields(config);
    const imports = this.getImports(fields);

    return this.template({
      Resource: resourceType,
      fields,
      hasImports: imports.length > 0,
      importsList: imports.join(', '),
      autoGenerated: true,
    });
  }

  /**
   * Infer FHIR model fields
   */
  private inferFields(config: MappingConfig): Array<{
    name: string;
    type: string;
    required: boolean;
    description: string;
  }> {
    const resourceType = config.fhirResource.resourceType;
    
    // For List resources, use FHIR List structure
    if (resourceType.startsWith('List')) {
      return [
        { 
          name: 'status', 
          type: "'current' | 'retired' | 'entered-in-error'", 
          required: true,
          description: 'The current state of the list' 
        },
        { 
          name: 'mode', 
          type: "'working' | 'snapshot' | 'changes'", 
          required: false,
          description: 'How this list was prepared' 
        },
        { 
          name: 'title', 
          type: 'string', 
          required: false,
          description: 'A label for the list' 
        },
        { 
          name: 'entry', 
          type: 'Array<{ item: Reference }>', 
          required: false,
          description: 'Entries in the list' 
        },
      ];
    }

    // Use mappings to infer fields
    if (config.mappings && config.mappings.length > 0) {
      return config.mappings.map((m) => ({
        name: m.target,
        type: this.inferFhirType(m.target),
        required: !m.optional,
        description: m.description || `${m.target} field`,
      }));
    }

    // Default
    return [
      { name: 'id', type: 'string', required: false, description: 'Logical id of this artifact' },
    ];
  }

  /**
   * Get imports needed for FHIR model
   */
  private getImports(fields: Array<{ type: string }>): string[] {
    const imports = new Set<string>();
    
    fields.forEach((field) => {
      if (field.type.includes('Reference')) imports.add('Reference');
      if (field.type.includes('Identifier')) imports.add('Identifier');
      if (field.type.includes('HumanName')) imports.add('HumanName');
      if (field.type.includes('ContactPoint')) imports.add('ContactPoint');
      if (field.type.includes('Address')) imports.add('Address');
      if (field.type.includes('CodeableConcept')) imports.add('CodeableConcept');
    });

    return Array.from(imports);
  }

  /**
   * Infer FHIR type from field name
   */
  private inferFhirType(fieldName: string): string {
    const lower = fieldName.toLowerCase();
    
    if (lower.includes('reference')) return 'Reference';
    if (lower.includes('identifier')) return 'Identifier[]';
    if (lower.includes('name')) return 'HumanName[]';
    if (lower.includes('telecom')) return 'ContactPoint[]';
    if (lower.includes('address')) return 'Address[]';
    if (lower.includes('code')) return 'CodeableConcept';
    
    return 'string';
  }
}

