/**
 * Helper Method Generator
 * Generates utility helper methods for FHIR resources
 */

import Handlebars from 'handlebars';
import { readFileSync } from 'fs';
import { join } from 'path';
import type { MappingConfig } from './config-parser.js';

export class HelperGenerator {
  private template: HandlebarsTemplateDelegate | null = null;
  private templateDir: string;

  constructor(templateDir: string) {
    this.templateDir = templateDir;
    this.loadTemplate();
  }

  private loadTemplate() {
    try {
      const content = readFileSync(join(this.templateDir, 'helper-method.hbs'), 'utf-8');
      this.template = Handlebars.compile(content);
    } catch (error) {
      console.warn('Failed to load helper method template:', error);
    }
  }

  /**
   * Generate helper method code
   */
  generate(config: MappingConfig): string {
    if (!this.template) {
      throw new Error('Helper method template not loaded');
    }

    const resourceType = config.fhirResource.resourceType;

    return this.template({
      Resource: resourceType,
      autoGenerated: true,
    });
  }

  /**
   * Get the utility file path for this helper
   */
  getUtilityFilePath(category: string = 'reference'): string {
    return `libs/fhir/src/utils/${category}.ts`;
  }
}

