/**
 * user-service Service Client
 * Production-ready client for calling internal user-service via REST
 * Auto-generated by FHIR Mapper Generator
 */

import axios, { AxiosError, AxiosInstance } from 'axios'
import { ListUserFilesDTO } from '@api-hub/fhir'
import { createLogger } from '@api-hub/logger'

const logger = createLogger({ service: 'fhir-gateway', redactPII: true })

export class UserServiceServiceClient {
  private readonly client: AxiosInstance
  private readonly baseUrl: string

  constructor(baseUrl?: string) {
    this.baseUrl = baseUrl || process.env.USER_SERVICE_SERVICE_URL || 'http://localhost:3000'
    this.client = this.createClient()
  }

  /**
   * Create configured axios instance
   */
  private createClient(): AxiosInstance {
    const client = axios.create({
      timeout: 30000,
      headers: {
        'Content-Type': 'application/json',
      },
      validateStatus: (status) => status < 500,
    })

    client.interceptors.request.use(
      (config) => {
        if (config.headers) {
          const authHeader = config.headers.Authorization || config.headers.authorization
          if (authHeader) {
            const authValue = String(authHeader).trim()
            config.headers.Authorization = authValue
            delete config.headers.authorization
          }
        }
        return config
      },
      (error) => {
        logger.error({
          event: 'user-service_service_request_error',
          err: {
            message: error.message,
            config: {
              url: error.config?.url,
              method: error.config?.method,
            },
          },
        })
        return Promise.reject(error)
      }
    )

    client.interceptors.response.use(
      (response) => {
        return response
      },
      (error: AxiosError) => {
        if (error.response) {
          logger.warn({
            event: 'user-service_service_response_error',
            status: error.response.status,
            statusText: error.response.statusText,
            url: error.config?.url,
          })
        } else if (error.request) {
          logger.error({
            event: 'user-service_service_no_response',
            message: 'No response received from user-service',
            url: error.config?.url,
          })
        }
        return Promise.reject(error)
      }
    )

    return client
  }

  /**
   * Get listUserFiles by ID
   */
  async getListUserFiles(
    id: string,
    correlationId?: string,
    authHeader?: string
  ): Promise<ListUserFilesDTO> {
    if (!authHeader) {
      throw new Error('Access token is required')
    }

    if (!id) {
      throw new Error('ListUserFiles ID is required')
    }

    let token = authHeader.trim()

    if (token.startsWith('Bearer ')) {
      token = token.substring(7).trim()
    }

    if (!token) {
      throw new Error('Access token cannot be empty')
    }

    const authorizationHeaderValue = `Bearer ${token}`.trim()
    const fullUrl = `${this.baseUrl.replace(/\/$/, '')}/user/${id}/files`

    try {
      const requestHeaders: Record<string, string> = {
        Authorization: authorizationHeaderValue,
      }

      if (correlationId) {
        requestHeaders['X-Correlation-Id'] = correlationId
      }

      const response = await this.client.get<{ data: ListUserFilesDTO }>(fullUrl, {
        headers: requestHeaders,
      })

      if (response.status === 200 && response.data?.data) {
        return response.data.data
      }

      if (response.status === 404) {
        throw new ListUserFilesNotFoundError(`ListUserFiles id not found`)
      }

      throw new Error(
        `Invalid response from user-service: status ${response.status}, data: ${JSON.stringify(response.data)}`
      )
    } catch (error) {
      if (error instanceof ListUserFilesNotFoundError) {
        throw error
      }

      if (axios.isAxiosError(error)) {
        const axiosError = error as AxiosError<{ title?: string; detail?: string; status?: number }>

        if (axiosError.response?.status === 401) {
          throw new Error('Unauthorized: Invalid or expired access token')
        }

        if (axiosError.response?.status === 403) {
          throw new Error('Forbidden: Insufficient permissions')
        }

        if (axiosError.response?.status === 404) {
          throw new ListUserFilesNotFoundError(`ListUserFiles id not found`)
        }

        if (axiosError.response?.status === 429) {
          throw new Error('Rate limit exceeded: Too many requests')
        }

        logger.error({
          event: 'user-service_service_client_error',
          err: {
            message: axiosError.message,
            status: axiosError.response?.status,
            statusText: axiosError.response?.statusText,
            data: axiosError.response?.data,
            url: axiosError.config?.url,
          },
          id,
          correlationId,
        })

        const errorData = axiosError.response?.data as
          | { detail?: string; message?: string; title?: string }
          | undefined
        const errorMessage =
          errorData?.detail ||
          errorData?.message ||
          errorData?.title ||
          axiosError.message ||
          'Unknown error occurred'

        throw new Error(`Failed to fetch listUserFiles: ${errorMessage}`)
      }

      if (error instanceof Error) {
        logger.error({
          event: 'user-service_service_client_unexpected_error',
          err: {
            message: error.message,
            stack: error.stack,
          },
          id,
          correlationId,
        })
        throw error
      }

      throw new Error('An unexpected error occurred while fetching listUserFiles')
    }
  }
}

export class ListUserFilesNotFoundError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'ListUserFilesNotFoundError'
    Object.setPrototypeOf(this, ListUserFilesNotFoundError.prototype)
  }
}
