export enum AppointmentStatus {
    SCHEDULED = 1,
    CHECKED_IN = 2,
    IN_PROGRESS = 3,
    COMPLETED = 4,
    CANCELLED = 5,
    NO_SHOW = 6,
  }
  
  export enum VisitType {
    OUTPATIENT = 1,
    INPATIENT = 2,
    EMERGENCY = 3,
    TELECONSULTATION = 4,
  }
  
  export enum VisitStatus {
    ACTIVE = 1,
    COMPLETED = 2,
    CANCELLED = 3,
  }
  
  export enum SSOErrorCode {
    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_VERIFICATION_FAILED = 'TOKEN_VERIFICATION_FAILED',
    USER_INACTIVE = 'USER_INACTIVE',
    USER_SERVICE_ERROR = 'USER_SERVICE_ERROR',
    ROLE_SERVICE_ERROR = 'ROLE_SERVICE_ERROR',
    COGNITO_AUTH_ERROR = 'COGNITO_AUTH_ERROR',
    DOWNSTREAM_SERVICE_ERROR = 'DOWNSTREAM_SERVICE_ERROR',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    INVALID_REQUEST = 'INVALID_REQUEST',
    TRU_TECH_SERVICE_ERROR = 'TRU_TECH_SERVICE_ERROR',
    INVALID_LAUNCH_TOKEN = "INVALID_LAUNCH_TOKEN",
  }
  
  
  export enum InviteErrorCode {
    INVALID_REQUEST = 'INVALID_REQUEST',
    NOT_FOUND = 'NOT_FOUND',
    RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
  }