#!/bin/sh

echo "Running affected lint..."

npx nx affected --target=lint --base=origin/main --head=HEAD

if [ $? -ne 0 ]; then
  echo "❌ Lint failed"
  exit 1
fi

echo "Running affected tests..." 
NX_DAEMON=true