#!/bin/sh

if [ -s "$HOME/.nvm/nvm.sh" ]; then
  . "$HOME/.nvm/nvm.sh"
  nvm use >/dev/null 2>&1
fi

echo "Running affected lint..."

npx nx affected --target=lint --base=origin/main --head=HEAD

if [ $? -ne 0 ]; then
  echo "❌ Lint failed"
  exit 1
fi

echo "Running affected tests..." 
NX_DAEMON=true