/**
 * FHIR Identity Utilities
 */

import { Reference } from '../models/r4/common';

/**
 * Create a FHIR reference
 */
export function createReference(
  resourceType: string,
  id: string,
  display?: string
): Reference {
  return {
    reference: `${resourceType}/${id}`,
    type: resourceType,
    ...(display && { display }),
  };
}

/**
 * Create a User reference
 * Auto-generated by FHIR Mapper Generator
 * @generated
 * @param id - User ID
 * @param display - Optional display text
 * @returns FHIR Reference to User
 */
export function createUserReference(id: string, display?: string): Reference {
  return createReference('User', id, display);
}

/**
 * Create a ListUserOrganizations reference
 * Auto-generated by FHIR Mapper Generator
 * @generated
 * @param id - ListUserOrganizations ID
 * @param display - Optional display text
 * @returns FHIR Reference to ListUserOrganizations
 */
export function createListUserOrganizationsReference(id: string, display?: string): Reference {
  return createReference('ListUserOrganizations', id, display);
}

/**
 * Create a ListUserFiles reference
 * Auto-generated by FHIR Mapper Generator
 * @generated
 * @param id - ListUserFiles ID
 * @param display - Optional display text
 * @returns FHIR Reference to ListUserFiles
 */
export function createListUserFilesReference(id: string, display?: string): Reference {
  return createReference('ListUserFiles', id, display);
}








