import * as fs from 'fs';
import * as path from 'path';

const RESOURCE_METADATA_DIR = path.resolve(
  __dirname,
  '../src/generated/resources/R4',
);

const OUTPUT_DIR = path.resolve(
  __dirname,
  '../src/generated/resource-config/R4',
);

if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, {
    recursive: true,
  });
}

interface ResourceMetadata {
  resourceType?: string;
  resource?: string;
  name?: string;
  url?: string;
  required?: string[];
}

function generateConfig(metadata: ResourceMetadata): string | null {
  const resourceName =
    metadata.resourceType || metadata.resource || metadata.name;

  if (!resourceName) {
    console.warn('Skipping invalid resource metadata');

    return null;
  }

  const profileUrl =
    metadata.url || `http://hl7.org/fhir/StructureDefinition/${resourceName}`;

  const generatedAt = new Date().toISOString();

  return `export default {

resource:'${resourceName}',

version:'R4',

profile:[
'${profileUrl}'
],

validation:{

enabled:true,

level:'BASIC',

requiredFields:${JSON.stringify(metadata.required ?? [], null, 2)}

},

detection:{

enabled:false,

fields:[],

strategy:'ANY'

},

mapping:{

file:'${resourceName}.mapping.json'

},

aliases:{},

references:[],

extensions:[],

transformers:[],

clientOverrides:true,

metadata:{

generated:true,

generatedAt:'${generatedAt}',

source:'HL7-R4'

}

};
`;
}

const files = fs
  .readdirSync(RESOURCE_METADATA_DIR)
  .filter((file) => file.endsWith('.metadata.json'));

console.error(`Generating ${files.length} configs`);

const indexImports: string[] = [];
const indexExports: string[] = [];

function toImportIdentifier(name: string): string {
  const sanitized = name.replace(/[^a-zA-Z0-9]/g, '_');
  return /^[a-zA-Z]/.test(sanitized) ? sanitized : `r_${sanitized}`;
}

for (const file of files) {
  const filePath = path.join(RESOURCE_METADATA_DIR, file);

  const metadata = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  const content = generateConfig(metadata);

  if (!content) {
    continue;
  }

  const resourceName =
    metadata.resourceType || metadata.resource || metadata.name;

  const outputFile = path.join(OUTPUT_DIR, `${resourceName}.config.ts`);

  fs.writeFileSync(outputFile, content);

  const importName = toImportIdentifier(resourceName);
  indexImports.push(
    `import ${importName} from './${resourceName}.config.js';`,
  );
  indexExports.push(importName);

  console.error(`Generated ${resourceName}.config.ts`);
}

const indexContent = [
  '// Auto-generated by scripts/generate-config.ts — do not edit manually',
  '',
  ...indexImports,
  '',
  `export { ${indexExports.join(', ')} };`,
  '',
].join('\n');

fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), indexContent);

console.error('FHIR config generation completed');
